### ISSUE TITLE
Session closed when running for a long time 

### ISSUE THREAD

**Issue by Julyyq** [Chatie/wechaty#1052]
### Provide Your Network Information

1. Where is the location of your server? 
    __Japan__
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
    __Vultr/Ubutun 16.04__

When running for a long time,(mostly over 24 hours),  the bot is down with the following error: 

<details>

```
2018-01-12 14:16:14,678 ERROR 2109 nodejs.TypeError: Cannot read property 'evaluate' of undefined
    at Bridge.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:599:50)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:594:16)
    at Bridge.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:403:35)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:395:16)
    at PuppetWeb.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:636:45)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:3:12)
    at PuppetWeb.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:615:16)
    at Wechaty.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:474:42)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at Wechaty.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:469:16)
    at Contact.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:273:30)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:3:12)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:3:12)
    at Contact.say (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:251:16)
    at Wechat.post (/root/wechatbot_watcher/app/service/wechat.js:32:44)
    at /root/wechatbot_watcher/app/service/price.js:71:43
    at _fulfilled (/root/wechatbot_watcher/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/root/wechatbot_watcher/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/root/wechatbot_watcher/node_modules/q/q.js:816:13)
    at /root/wechatbot_watcher/node_modules/q/q.js:624:44
    at runSingle (/root/wechatbot_watcher/node_modules/q/q.js:137:13)
    at flush (/root/wechatbot_watcher/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

pid: 2109

2018-01-12 14:17:47,482 ERROR 2099 nodejs.ClusterClientNoResponseError: client no response in 92359ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/root/wechatbot_watcher/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 2099

2018-01-12 14:17:47,630 ERROR 2109 nodejs.unhandledRejectionError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/root/wechatbot_watcher/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)
    at <anonymous>
name: 'unhandledRejectionError'
pid: 2109

2018-01-12 14:30:00,536 ERROR 2109 nodejs.unhandledRejectionError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at Session.send (/root/wechatbot_watcher/node_modules/puppeteer/lib/Connection.js:178:29)
    at ExecutionContext.evaluateHandle (/root/wechatbot_watcher/node_modules/puppeteer/lib/ExecutionContext.js:58:75)
    at ExecutionContext.evaluate (/root/wechatbot_watcher/node_modules/puppeteer/lib/ExecutionContext.js:37:31)
    at Frame.evaluate (/root/wechatbot_watcher/node_modules/puppeteer/lib/FrameManager.js:237:26)
    at Page.evaluate (/root/wechatbot_watcher/node_modules/puppeteer/lib/Page.js:608:43)
    at Bridge.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:599:51)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:594:16)
    at Bridge.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:403:35)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/bridge.js:395:16)
    at PuppetWeb.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:636:45)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:3:12)
    at PuppetWeb.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/puppet-web/puppet-web.js:615:16)
    at Wechaty.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:474:42)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at Wechaty.send (/root/wechatbot_watcher/node_modules/wechaty/dist/src/wechaty.js:469:16)
    at Contact.<anonymous> (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:273:30)
    at Generator.next (<anonymous>)
    at /root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:3:12)
    at Contact.say (/root/wechatbot_watcher/node_modules/wechaty/dist/src/contact.js:251:16)
    at Wechat.post (/root/wechatbot_watcher/app/service/wechat.js:32:44)
    at /root/wechatbot_watcher/app/service/price.js:71:43
    at _fulfilled (/root/wechatbot_watcher/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/root/wechatbot_watcher/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/root/wechatbot_watcher/node_modules/q/q.js:816:13)
    at /root/wechatbot_watcher/node_modules/q/q.js:624:44
    at runSingle (/root/wechatbot_watcher/node_modules/q/q.js:137:13)
    at flush (/root/wechatbot_watcher/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
name: 'unhandledRejectionError'
pid: 2109

```
</details>

I checked my log file and can't find my wechat account logout message. Is this a wechaty or puppet bug?

**Comment by zixia** [comment]
Can you **provide the steps to reproduce the problem** ?

**Comment by zixia** [comment]
Close this issue due to no reproducible steps provided, and no response for months.
