### ISSUE TITLE
出现 no Url 错误后，程序崩溃

### ISSUE THREAD

**Issue by j1wwy** [Chatie/wechaty#1055]
```
01:08:08 WARN MediaMessage ready() exception: no Url
01:08:08 ERR PuppetWebEvent onMessage() exception: Error: no Url
    at MediaMessage.<anonymous> (/var/www/ryqb/node_modules/_wechaty@0.13.41@wechaty/dist/src/message.js:585:43)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/ryqb/node_modules/_wechaty@0.13.41@wechaty/dist/src/message.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:32733) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: no Url
(node:32733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
06:27:08 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:heartbeat@browser, timeout:60000
06:29:22 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:31:27 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:33:31 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:35:34 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, 09:11:37 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
...
...
...
09:13:43 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
09:14:18 ERR PuppetWebBridge init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
09:14:21 ERR PuppetWeb initBridge() exception: Navigation Timeout Exceeded: 30000ms exceeded
09:14:21 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
09:14:21 ERR PuppetWeb init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:32733) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Navigation Timeout Exceeded: 30000ms exceeded
error: Forever detected script exited with code: 0
error: Script restart attempt #1
09:16:46 WARN Wechaty init() DEPRECATED and will be removed after Jun 2018. Use start() instead.
09:16:46 INFO Wechaty v0.13.41 starting...
Scan QR Code to login: 408
https://login.weixin.qq.com/qrcode/oaVy-kE5IQ==
```

**Comment by lijiarui** [comment]
Could you give more information about this issue, please?  Or we cannot find the exact reason about this problem.

**Comment by suntong** [comment]
Agree, unless the standard bug reporting template is followed, I think this issue should be closed.

**Comment by zixia** [comment]
@suntong Yes, you are right. 

Close this issue due to no reply for a month.
