### ISSUE TITLE
My session last only for 5 hours

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1059]
How to make it last 7x24?

### Provide Your Network Information

1. Where is the location of your server? (Out China, in reputable cloud farm)
1. Which cloud platform are you using? Private cloud platform

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

```
$ wechaty run doctor
wechaty: command not found
```

### Expected behavior

last 7x24.

### Actual behavior

last only for 5 hours

### Steps to reproduce the behavior (and fixes, if any)

run the [**The World’s Shortest ChatBot Code: 6 lines of JavaScript**](http://chatie.io/wechaty/#wechatyinstance) out of the box.

### Full Output Logs

```shell
docker run -it --rm --volume="$(pwd)":/bot zixia/wechaty mybot.ts
...
05:57:25 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:heartbeat@browser, timeout:60000
05:59:59 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:02:18 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:04:51 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:07:14 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:09:34 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:12:06 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:14:29 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:16:38 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scan listeners added. Use emitter.setMaxListeners() to increase limit
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 login listeners added. Use emitter.setMaxListeners() to increase limit
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 logout listeners added. Use emitter.setMaxListeners() to increase limit
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 heartbeat listeners added. Use emitter.setMaxListeners() to increase limit
06:18:48 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 watchdog listeners added. Use emitter.setMaxListeners() to increase limit
06:20:58 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:23:07 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:25:18 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:27:30 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:29:40 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:31:50 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:34:19 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:36:31 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:38:42 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:40:52 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:43:03 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:45:26 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:47:36 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:49:49 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:52:04 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:54:29 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:56:39 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
06:58:50 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:01:07 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:03:19 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:06:00 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:08:13 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:10:26 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
07:11:00 ERR PuppetWebBridge init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
07:11:03 ERR PuppetWeb initBridge() exception: Navigation Timeout Exceeded: 30000ms exceeded
07:11:03 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
07:11:03 ERR PuppetWeb init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:29) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/wechaty/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
    at <anonymous>
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The above is American NY time, i.e., 5am is 6pm in China. 

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

Don't know how to run it with docker, and moreover, the above `timeout` and `memory leak` might out show up during the full output logging. 

</details>

**Comment by suntong** [comment]
This is a **duplicate** of https://github.com/Chatie/wechaty/issues/981,
but I'll leave it _open_ till that one is closed, as that one miss the step of how to duplicate the problem.

**Comment by suntong** [comment]
I'm trying it again for the 2nd time, and this time is not much better, 

```
12:25:05 INFO Wechaty v0.13.55 starting...
... then ...
13:49:34 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:heartbeat@browser, timeout:60000
13:49:34 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
13:51:44 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
13:53:54 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
13:56:04 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
13:58:13 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
14:00:22 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
```

I.e., the bot _stopped working and responding_  after about 1 hour & 25 minutes. 

The platform that I initially chose was so unstable that I had to look for something else, and landed here. But if nobody can confirm that wechaty can last for a long time, ideally 7x24, it might be high time for me to take another leap...

**Comment by suntong** [comment]
and afterward, I just cannot login any more:

	14:46:42 INFO Wechaty v0.13.55 starting...
	14:47:23 ERR PuppetWebBridge init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:47:27 ERR PuppetWeb initBridge() exception: Navigation Timeout Exceeded: 30000ms exceeded
	14:47:27 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
	14:47:27 ERR PuppetWeb init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:47:27 ERR Wechaty start() exception: Navigation Timeout Exceeded: 30000ms exceeded
	(node:3247) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
		at Promise.then (/path/to/autoarch/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
		at <anonymous>
	(node:3247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
	(node:3247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


	14:47:43 INFO Wechaty v0.13.55 starting...
	14:47:44 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
	https://login.weixin.qq.com/qrcode/weW9HSAU_w==
	[408] Scan QR Code in above url to login: 
	already notified user for https://login.weixin.qq.com/qrcode/weW9HSAU_w==
	14:50:52 WARN PuppetWeb initScanWatchdog() on(reset) lastFood: https://login.weixin.qq.com/qrcode/weW9HSAU_w==, timePast: 120000
	14:50:58 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:heartbeat@browser, timeout:60000
	14:51:07 ERR PuppetWeb initScanWatchdog() on(reset) exception: Error: Protocol error (Page.reload): Target closed.
	14:51:07 ERR PuppetWeb initScanWatchdog() on(reset) try to recover by bridge.{quit,init}()
	14:51:07 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
	^C^C

then tried again, 

	14:51:22 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
	14:51:23 ERR PuppetWebBridge ding(ding() OK!) exception: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
	14:51:23 ERR PuppetWebBridge init() initPage() onLoad() exception: Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
	(node:124641) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
		at Promise (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:185:56)
		at new Promise (<anonymous>)
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:184:12)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
		at process._tickCallback (internal/process/next_tick.js:160:7)
	(node:124641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
	(node:124641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

then tried again, 

	14:51:55 INFO Wechaty v0.13.55 starting...
	14:52:36 ERR PuppetWebBridge init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:52:37 ERR PuppetWeb initBridge() exception: Navigation Timeout Exceeded: 30000ms exceeded
	14:52:37 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
	14:52:37 ERR PuppetWeb init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:52:37 ERR Wechaty start() exception: Navigation Timeout Exceeded: 30000ms exceeded
	(node:3685) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
		at Promise.then (/path/to/autoarch/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
		at <anonymous>
	(node:3685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
	(node:3685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

then tried again, 

	14:52:45 INFO Wechaty v0.13.55 starting...
	14:53:25 ERR PuppetWebBridge init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:53:25 ERR PuppetWeb initBridge() exception: Navigation Timeout Exceeded: 30000ms exceeded
	14:53:25 WARN PuppetWebBridge quit() page.close() exception: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
	14:53:25 ERR PuppetWeb init() exception: Error: Navigation Timeout Exceeded: 30000ms exceeded
	14:53:25 ERR Wechaty start() exception: Navigation Timeout Exceeded: 30000ms exceeded
	(node:3775) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
		at Promise.then (/path/to/autoarch/node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
		at <anonymous>
	(node:3775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
	(node:3775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

then tried again, 

	> node index.js
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:172:29)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
	15:06:59 ERR PuppetWebEvent onMessage() exception: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:172:29)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
	15:06:59 ERR PuppetWebEvent onMessage() exception: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:172:29)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
	(node:3876) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:172:29)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
	(node:3876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 312)
	(node:3876) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
		at CDPSession.send (/path/to/autoarch/node_modules/puppeteer/lib/Connection.js:172:29)
		at ExecutionContext.evaluateHandle (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:62:75)
		at ExecutionContext.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/ExecutionContext.js:41:31)
		at Frame.evaluate (/path/to/autoarch/node_modules/puppeteer/lib/FrameManager.js:290:20)
		at <anonymous>
	(node:3876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 313)
	15:09:45 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000
	^C15:14:05 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: Protocol error (Runtime.callFunctionOn): Target closed.
	15:14:05 ERR PuppetWebBridge ding(ding() OK!) exception: Protocol error (Runtime.callFunctionOn): Target closed.
	15:14:05 ERR PuppetWebBridge init() initPage() onLoad() exception: Error: Protocol error (Runtime.callFunctionOn): Target closed.
	(node:3876) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Protocol error: Connection closed. Most likely the page has been closed.
		at Console.assert (console.js:197:23)
		at Page.close (/path/to/autoarch/node_modules/puppeteer/lib/Page.js:798:13)
		at Bridge.<anonymous> (/path/to/autoarch/node_modules/wechaty/dist/src/puppet-web/bridge.js:138:28)
		at Generator.throw (<anonymous>)
		at rejected (/path/to/autoarch/node_modules/wechaty/dist/src/puppet-web/bridge.js:5:65)
		at <anonymous>
		at process._tickCallback (internal/process/next_tick.js:160:7)
	(node:3876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 316)

**Comment by zixia** [comment]
Hello @suntong,

Wechaty should be able to last for 7x24 without any problem because many friends of mine did that, so did I.

For example, I'm using https://github.com/zixia/wechaty-blinder for a long time in a Container, it runs all day and all night, sometimes I'll scan the QR Code to log in, but most of the time it was waiting to be scanned.

If you can reproduce this error message, please provide the minimum reproduce steps with the runable minimum code, then we will be able to have a look on it.
> (node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scan listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by suntong** [comment]
Oh, glad to know, 

_Steps to reproduce the behavior_, as put in OP, 

> run the The World’s Shortest ChatBot Code: 6 lines of JavaScript out of the box.

**Comment by zixia** [comment]
Could you please confirm that you can reproduce it in another machine/environment?

It's better to find someone else help you to reproduce it, because I'm using that 6 lines code many months but never met your issue.

**Comment by suntong** [comment]
Oh, OK. will do. 

The cloud platform that I'm using is _Azure_, which has been most/pretty stable for anything. OK, let me try with something less stable, like my home PC, or... 

BTW, zixia, do you have an Azure account to try with?

**Comment by suntong** [comment]
Oh, actually, what I run was

https://github.com/suntong/nodecl/blob/master/wx/bot1.ts

although it is not the 6 lines code, but look pretty close to me.

**Comment by zixia** [comment]
Glad to hear that, cheers!

**Comment by suntong** [comment]
:-) 

I suspect that MS is playing big-brother in the back, but let's wait a second opinion to confirm...
