### ISSUE TITLE
Pupeteer not work after upgrade to v1.1

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1103]
puppeteer v0.13 work without any problem.

with https://github.com/GoogleChrome/puppeteer/releases/tag/v1.1.0, `readyAngular` will hang because `window.angular` always be undefined.

```shell
# PuppetWebBridge
03:11:59 ERR PuppetWebBridge init() initPage() onLoad() exception: Error: waiting failed: timeout 30000ms exceeded
(node:32211) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/zixia/chatie/wechaty/node_modules/puppeteer/lib/FrameManager.js:789:58)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
(node:32211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Jiangmx** [comment]
After downgrade and upgrade puppeteer a few times,I got an error of **Chromium revision is not downloaded**.
### My solution is

1. download app from [https://storage.googleapis.com/chromium-browser-snapshots/Mac/526987/chrome-mac.zip](https://storage.googleapis.com/chromium-browser-snapshots/Mac/526987/chrome-mac.zip) 526987 is the chrome version your puppeteer need .Other OS [https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html)
2. move the app file into **{home}/node_modules/puppeteer/.local-chromium/mac-526987/chrome-mac**
### rules:
```
const downloadURLs = {
  linux: '%s/chromium-browser-snapshots/Linux_x64/%d/chrome-linux.zip',
  mac: '%s/chromium-browser-snapshots/Mac/%d/chrome-mac.zip',
  win32: '%s/chromium-browser-snapshots/Win/%d/chrome-win32.zip',
  win64: '%s/chromium-browser-snapshots/Win_x64/%d/chrome-win32.zip',
};
revisionInfo(revision) {
    const folderPath = this._getFolderPath(revision);
    let executablePath = '';
    if (this._platform === 'mac')
      executablePath = path.join(folderPath, 'chrome-mac', 'Chromium.app', 'Contents', 'MacOS', 'Chromium');
    else if (this._platform === 'linux')
      executablePath = path.join(folderPath, 'chrome-linux', 'chrome');
    else if (this._platform === 'win32' || this._platform === 'win64')
      executablePath = path.join(folderPath, 'chrome-win32', 'chrome.exe');
    else
      throw 'Unsupported platform: ' + this._platform;
    let url = downloadURLs[this._platform];
    url = util.format(url, this._downloadHost, revision);
    const local = fs.existsSync(folderPath);
    return {revision, executablePath, folderPath, local, url};
  }
````

**Comment by zixia** [comment]
v1.1.1 passed CI
