### ISSUE TITLE
findAll ,WARN Room parse() on a empty rawObj

### ISSUE THREAD

**Issue by FengJiaCheng** [Chatie/wechaty#1141]
调用room.findall报错。

环境：
1.ubuntu 14.04
2.Docker version 17.12.0-ce, build c97c6d6
3.镜像是build自 wechaty的`32f31b1056868fc211611da157fd5bcda9fb9e45`的提交

```
 03:24:13WARN Room parse() on a empty rawObj?
2018-03-22T03:24:13.774205519Z 03:24:13 ERR Room contactGetter(@@5ce07ac48456e24705edf614e903637ff6e17960de9f321ed814e8fd3aeff5d2) exception: no this.obj set after contactGetter
2018-03-22T03:24:13.807309847Z (node:32) UnhandledPromiseRejectionWarning: Error: no this.obj set after contactGetter
2018-03-22T03:24:13.807356522Z     at Room._callee2$ (/wechaty/dist/src/room.js:120:27)
2018-03-22T03:24:13.807363527Z     at tryCatch (/wechaty/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
2018-03-22T03:24:13.807367796Z     at Generator.invoke [as _invoke] (/wechaty/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
2018-03-22T03:24:13.807372042Z     at Generator.prototype.(anonymous function) [as next] (/wechaty/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
2018-03-22T03:24:13.807376387Z     at fulfilled (/wechaty/dist/src/room.js:4:58)
2018-03-22T03:24:13.807380515Z     at <anonymous>
2018-03-22T03:24:13.807403337Z (node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment]
Close this issue due to long time no activity and leak of the re-produce steps.
