### ISSUE TITLE
Cannot send image message on v0.15.21

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1175]
v0.15.21

```shell
02:19:12 SILL Message constructor()
02:19:12 SILL PuppeteerMessage constructor()
02:19:12 VERB PuppeteerMessage say(PuppeteerMessage<>, undefined)
02:19:12 SILL PuppetAccessory <PuppeteerMessage> get puppet()
02:19:12 SILL PuppetAccessory <PuppeteerContact> set puppet(PuppetPuppeteer)
02:19:12 SILL PuppetAccessory <PuppeteerMessage> get puppet()
02:19:12 VERB PuppetPuppeteer send(PuppeteerMessage<>)
02:19:12 SILL PuppetAccessory <NewClass> get puppet()
02:19:12 SILL PuppetAccessory <undefined> static get puppet()
02:19:12 SILL PuppetAccessory <PuppeteerContact> set puppet(PuppetPuppeteer)
02:19:12 SILL PuppeteerMessage type() = undefined
02:19:12 SILL PuppetPuppeteer send() TEXT message.
02:19:12 SILL PuppetPuppeteer send() destination: @91721c2272a6b3ac480dd8e64f53e765, text: undefined)
02:19:12 VERB PuppetPuppeteerBridge send(@91721c2272a6b3ac480dd8e64f53e765, undefined)
02:19:12 ERR PuppetPuppeteer send() exception: cannot say nothing
02:19:12 ERR Bot on(message) exception: Error: cannot say nothing
Error: cannot say nothing
    at Bridge.<anonymous> (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/bridge.ts:432:13)
    at Generator.next (<anonymous>)
    at /Users/zixia/chatie/wechaty/src/puppet-puppeteer/bridge.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/bridge.ts:3:12)
    at Bridge.send (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/bridge.ts:395:16)
    at PuppetPuppeteer.<anonymous> (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppet-puppeteer.ts:701:27)
    at Generator.next (<anonymous>)
    at /Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppet-puppeteer.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppet-puppeteer.ts:3:12)
    at PuppetPuppeteer.send (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppet-puppeteer.ts:595:16)
    at PuppeteerMessage.<anonymous> (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppeteer-message.ts:338:23)
    at Generator.next (<anonymous>)
    at /Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppeteer-message.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppeteer-message.ts:3:12)
    at PuppeteerMessage.say (/Users/zixia/chatie/wechaty/src/puppet-puppeteer/puppeteer-message.ts:213:16)
    at Object.<anonymous> (/Users/zixia/chatie/wechaty/examples/ding-dong-bot.ts:96:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zixia/chatie/wechaty/examples/ding-dong-bot.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by zixia** [comment]
It's a bug introduced from BREAKING CHANGE #1168
