### ISSUE TITLE
Update the peerDependencies of `rx-queue`: rxjs@6 from rxjs@5

### ISSUE THREAD

**Issue by lym152898** [Chatie/wechaty#1205]
(node:5731) UnhandledPromiseRejectionWarning: TypeError: rxjs.interval is not a function
    at ThrottleSubscriber.durationSelector (/home/linyimin/practice/wechaty/test/node_modules/_rx-queue@0.3.14@rx-queue/bundles/rx-queue.umd.js:181:99)
    at ThrottleSubscriber.tryDurationSelector (/home/linyimin/practice/wechaty/test/node_modules/_rxjs@5.5.10@rxjs/operators/throttle.js:107:25)
    at ThrottleSubscriber._next (/home/linyimin/practice/wechaty/test/node_modules/_rxjs@5.5.10@rxjs/operators/throttle.js:92:33)
    at ThrottleSubscriber.Subscriber.next (/home/linyimin/practice/wechaty/test/node_modules/_rxjs@5.5.10@rxjs/Subscriber.js:93:18)
    at Subject.next (/home/linyimin/practice/wechaty/test/node_modules/_rxjs@5.5.10@rxjs/Subject.js:55:25)
    at ThrottleQueue.next (/home/linyimin/practice/wechaty/test/node_modules/_rx-queue@0.3.14@rx-queue/bundles/rx-queue.umd.js:185:26)
    at PuppetWeb.on.data (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet-web/puppet-web.js:74:60)
    at emitOne (events.js:121:20)
    at PuppetWeb.emit (events.js:211:7)
    at PuppetWeb.emit (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet.js:34:22)
    at Watchdog.dog.on.food (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet-web/puppet-web.js:102:20)
    at emitTwo (events.js:126:13)
    at Watchdog.emit (events.js:214:7)
    at Watchdog.feed (/home/linyimin/practice/wechaty/test/node_modules/_watchdog@0.3.4@watchdog/bundles/watchdog.umd.js:188:18)
    at PuppetWeb.puppet.on.food (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet-web/puppet-web.js:98:43)
    at emitOne (events.js:116:13)
    at PuppetWeb.emit (events.js:211:7)
    at PuppetWeb.emit (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet.js:34:22)
    at PuppetWeb.<anonymous> (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet-web/event.js:53:14)
    at Generator.next (<anonymous>)
    at fulfilled (/home/linyimin/practice/wechaty/test/node_modules/_wechaty@0.14.1@wechaty/dist/src/puppet-web/event.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:5731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zixia** [comment]
This is because the RxJS v5.5 has some BREAKING CHANGES.

Try to install the specific `rxjs@5.5.0` by run: `npm install rxjs@5.5.0` and try again.

**Comment by lym152898** [comment]
OK,I will have a try. Thanks!

**Comment by lym152898** [comment]
I have installed the specific rxjs@5.5.0 by run: npm install rxjs@5.5.0 and try again.But it dose not work.

**Comment by zixia** [comment]
What Wechaty version are you using?

Please remember to submit the version first before you ask questions.

**Comment by timqian** [comment]
met same issue on 
node v10.0.0
npm v5.6.0
wechaty v0.14.1

**Comment by zixia** [comment]
@timqian Sorry I had made a mistake: 

We should upgrade `rxjs` to v6 to follow the requirement of `rx-queue`.

Wechaty v0.14.2 or above should fix this issue, please test and feel free to let me know if you are still having problems.

**Comment by zixia** [comment]
@lym152898 @timqian Could you please to confirm that whether the v0.14.2 or above version of Wechaty resolve this issue?

**Comment by lym152898** [comment]
Yes, the issue is resolved when use rxjs@6  in wechaty@0.14.4

**Comment by zixia** [comment]
Thank you for the confirmation.
