### ISSUE TITLE
How to run hot-import-bot example

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1222]
I was getting the following errors (enclosed in "Show Logs") when running the hot-import-bot examples. Running with `node index.js` will give me the same error as well. What could be wrong?  All my tools are of the latest version now:

Wechaty is v0.14.4, and

```
$ node -v
v10.1.0

$ npm -v
6.0.1

$ ts-node -v
ts-node v6.0.3
node v10.1.0
typescript v2.8.3
cache "/tmp/ts-node-ebbe..ce010e"
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here  

```shell
# PASTE FULL LOG OUTPUT AT HERE:
cd Chatie/wechaty/examples/hot-import-bot

Chatie/wechaty/examples/hot-import-bot$ ts-node index.js 
23:57:46 INFO Wechaty v0.14.4 starting...
23:57:46 ERR HotImport importFile(/path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-friend.js) rejected: SyntaxError: Unexpected token export
23:57:46 ERR HotImport importFile(/path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-login.js) rejected: SyntaxError: Unexpected token export
23:57:46 ERR HotImport importFile(/path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-message.js) rejected: SyntaxError: Unexpected token export
23:57:46 ERR HotImport importFile(/path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-scan.js) rejected: SyntaxError: Unexpected token export
23:57:46 ERR Wechaty onModulePath(friend, ./listeners/on-friend) hotImport() exception: SyntaxError: Unexpected token export
23:57:46 ERR Wechaty onModulePath(login, ./listeners/on-login) hotImport() exception: SyntaxError: Unexpected token export
23:57:46 ERR Wechaty onModulePath(message, ./listeners/on-message) hotImport() exception: SyntaxError: Unexpected token export
23:57:46 ERR Wechaty onModulePath(scan, ./listeners/on-scan) hotImport() exception: SyntaxError: Unexpected token export
(node:25428) UnhandledPromiseRejectionWarning: /path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-friend.js:19
export default async function onFriend (contact, request) {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise.resolve.then (/path/to/node_modules/hot-import/src/hot-import.ts:273:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/bin.ts:145:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
(node:25428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:25428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:25428) UnhandledPromiseRejectionWarning: /path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-login.js:19
export default async function onLogin (user) {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise.resolve.then (/path/to/node_modules/hot-import/src/hot-import.ts:273:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/bin.ts:145:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
(node:25428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:25428) UnhandledPromiseRejectionWarning: /path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-message.js:19
export default async function onMessage (message) {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise.resolve.then (/path/to/node_modules/hot-import/src/hot-import.ts:273:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/bin.ts:145:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
(node:25428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:25428) UnhandledPromiseRejectionWarning: /path/to/Chatie/wechaty/examples/hot-import-bot/listeners/on-scan.js:19
export default async function onScan (url, code) {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise.resolve.then (/path/to/node_modules/hot-import/src/hot-import.ts:273:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/bin.ts:145:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```
</details>

**Comment by zixia** [comment]
Will have a look into this after I finish the v0.15

**Comment by suntong** [comment]
Alright then. thx.

**Comment by suntong** [comment]
Thanks @zixia, so it can run within docker just fine. 

How can I make it run under normal command line as well, not within docker but just plain Linux shell? Thx.

**Comment by zixia** [comment]
Confirmed that the example cannot be run outside docker.

Merge to https://github.com/Chatie/wechaty-getting-started/issues/37
