### ISSUE TITLE
PadchatRpc WXGetChatRoomMember() result: {"message":"WS请求错误","status":-19} Error: no encodedText

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1309]
### Wechaty v0.15.140

```
04:11:16 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:17 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
04:11:17 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
04:11:17 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating 5 to Contact(41110) & Room(582) ...
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 中国投资人中心 | 创投群2(1804399209@chatroom)
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room EMBA商友汇懂事长联盟(2238151988@chatroom)
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 三赢资本投资人交流群(2096874722@chatroom)
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 天使之家（中关村天使联盟大群）(94443057@chatroom)
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 中国养猪博士50人圆桌会谈俱乐部(2400666233@chatroom)
04:11:20 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:20 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating 5 to Contact(41110) & Room(582) ...
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 第三届中国电信“i创”黑马大赛(7915130342@chatroom)
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room DaoCloud-北京技术交流群2(2381437533@chatroom)
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 公信宝交流社区1号(6971172435@chatroom)
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 中体飞行＆极限追踪群(3450818068@chatroom)
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 文天·领袖力量160学习7群(2590332226@chatroom)
04:11:23 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:23 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating 5 to Contact(41110) & Room(582) ...
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room BCF@k2工作群(3146641442@chatroom)
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room ACECE(3594076582@chatroom)
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 天使百人会(3172779818@chatroom)
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 猎云资本投资人1⃣️群(1733576801@chatroom)
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() updating Room 中国好项目1群(851650151@chatroom)
04:11:27 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:27 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:27 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
04:11:27 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
04:11:27 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
04:11:28 SILL PuppetPadchatBridge syncRoomMember(2012073244@chatroom)
04:11:28 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["2012073244@chatroom"])
04:11:28 VERB PuppetPadchatBridge startQueues() delayQueueExecutor.subscribe(syncRoomMember(2012073244@chatroom)) executed
04:11:28 SILL PadchatRpc WXGetChatRoomMember() result: {"message":"WS请求错误","status":-19}
Error: no encodedText
    at Function.padchatDecode (/home/ubuntu/workspace/src/puppet-padchat/pure-function-helper.ts:388:13)
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:682:73)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
decode error data:  undefined
04:11:28 WARN PadchatRpc WXGetChatRoomMember(2012073244@chatroom) result.member decode error: Error: no encodedText
memberListPayload { message: 'WS请求错误', status: -19, member: [] }
04:11:28 ERR Config ###########################
04:11:28 ERR Config unhandledRejection: Error: no memberListPayload [object Promise]
04:11:28 ERR Config ###########################
04:11:28 ERR Config process.on(unhandledRejection) promise.catch(no memberListPayload)
Config Error: no memberListPayload
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:710:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:20380) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:30 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:30 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:30 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:33 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:33 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:33 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:37 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:37 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:37 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:40 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:40 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:40 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:40 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
04:11:40 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
04:11:40 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
04:11:43 SILL PuppetPadchatBridge syncRoomMember(3897445405@chatroom)
04:11:43 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["3897445405@chatroom"])
04:11:43 VERB PuppetPadchatBridge startQueues() delayQueueExecutor.subscribe(syncRoomMember(3897445405@chatroom)) executed
04:11:43 SILL PadchatRpc WXGetChatRoomMember() result: {"message":"WS请求错误","status":-19}
Error: no encodedText
    at Function.padchatDecode (/home/ubuntu/workspace/src/puppet-padchat/pure-function-helper.ts:388:13)
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:682:73)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/workspace/src/puppet-padchat/padchat-rpc.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
decode error data:  undefined
04:11:43 WARN PadchatRpc WXGetChatRoomMember(3897445405@chatroom) result.member decode error: Error: no encodedText
memberListPayload { message: 'WS请求错误', status: -19, member: [] }
04:11:43 ERR Config ###########################
04:11:43 ERR Config unhandledRejection: Error: no memberListPayload [object Promise]
04:11:43 ERR Config ###########################
04:11:43 ERR Config process.on(unhandledRejection) promise.catch(no memberListPayload)
Config Error: no memberListPayload
    at Bridge.<anonymous> (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:710:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/workspace/src/puppet-padchat/bridge.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:20380) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:43 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:43 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:43 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:47 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:47 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:47 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:50 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:50 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:50 SILL PadchatRpc rpcCall(WXSyncContact, [])
syncContactList: { message: 'WS请求错误', status: -19 }
04:11:53 ERR PuppetPadchatBridge syncContactsAndRooms() cannot get array result!
04:11:53 SILL PuppetPadchatBridge syncContactsAndRooms() while() syncing WXSyncContact ...
04:11:53 SILL PadchatRpc rpcCall(WXSyncContact, [])
04:11:54 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
04:11:54 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
04:11:54 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
```

**Comment by zixia** [comment]
Duplicated with https://github.com/lijiarui/wechaty-puppet-padchat/issues/64
