### ISSUE TITLE
`contact.avatar()` cannot work as expect

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1321]
Wechaty version: v0.15.150

When running `contact-bot.ts` get the following error,
I change code related `contact.avatar()` as follows:
```ts
const MAX = 17
  for (let i = 0; i < contactList.length; i++ ) {
    const contact = contactList[i]

    console.log('======================')
    console.log(i)
    /**
     * Save avatar to file like: "1-name.jpg"
     */
    const file = await contact.avatar()
    const name = (contact.name() || cuid() ) + '.jpg'
    console.log(name)
    try {
      await file.toFile(name)
    } catch (error) {
      console.log(error)
    }

    log.info('Bot', 'Contact: "%s" with avatar file: "%s"',
                    contact.name(),
                    name,
            )

    if (i > MAX) {
      log.info('Bot', 'Contacts too many, I only show you the first %d ... ', MAX)
      break
    }
  }
```

error log：
```shell
19:15:00 INFO Bot personal 256: 张稀虹 : zz332191120
======================
0
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(D_70819983, )
defence.jpg
Error: save(/Users/egg/git/rui/wechaty/defence.jpg) file is already exist!
    at FileBox.<anonymous> (/Users/egg/git/rui/wechaty/node_modules/file-box/src/file-box.ts:383:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/node_modules/file-box/dist/src/file-box.js:4:58)
19:15:00 INFO Bot Contact: "defence" with avatar file: "defence.jpg"
======================
1
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(FENGZHILIANG1994, )
fzliang.jpg
Error: save(/Users/egg/git/rui/wechaty/fzliang.jpg) file is already exist!
    at FileBox.<anonymous> (/Users/egg/git/rui/wechaty/node_modules/file-box/src/file-box.ts:383:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/node_modules/file-box/dist/src/file-box.js:4:58)
19:15:00 INFO Bot Contact: "fzliang" with avatar file: "fzliang.jpg"
======================
2
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(GhostMaker, )
李岩.jpg
Error: save(/Users/egg/git/rui/wechaty/李岩.jpg) file is already exist!
    at FileBox.<anonymous> (/Users/egg/git/rui/wechaty/node_modules/file-box/src/file-box.ts:383:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/node_modules/file-box/dist/src/file-box.js:4:58)
19:15:00 INFO Bot Contact: "李岩" with avatar file: "李岩.jpg"
======================
3
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(JWJ0402, )
JWJ.jpg
Error: save(/Users/egg/git/rui/wechaty/JWJ.jpg) file is already exist!
    at FileBox.<anonymous> (/Users/egg/git/rui/wechaty/node_modules/file-box/src/file-box.ts:383:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/node_modules/file-box/dist/src/file-box.js:4:58)
19:15:00 INFO Bot Contact: "JWJ" with avatar file: "JWJ.jpg"
======================
4
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(L_U_B_Y, )
luby_xu.jpg
Error: save(/Users/egg/git/rui/wechaty/luby_xu.jpg) file is already exist!
    at FileBox.<anonymous> (/Users/egg/git/rui/wechaty/node_modules/file-box/src/file-box.ts:383:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/node_modules/file-box/dist/src/file-box.js:4:58)
19:15:00 INFO Bot Contact: "luby_xu" with avatar file: "luby_xu.jpg"
======================
5
19:15:00 VERB Contact avatar()
19:15:00 VERB PuppetPadchat contactAvatar(THINKERMAN_wang, )
辉.jpg
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() syncing 52 out of Contact(257) & Room(214) ...
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() updating Contact 朋友推荐消息(fmessage)
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() updating Contact 语音记事本(medianote)
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() updating Contact 漂流瓶(floatbottle)
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() updating Contact 栋梁(wxid_sgtv6p37zpeu22)
19:15:11 SILL PuppetPadchatManager syncContactsAndRooms() updating Contact 苏苏(wxid_lfrf5ttpdyvi22)
```

**Comment by zixia** [comment]
It's a confirmed bug from FileBox, and it was fixed.

**Comment by lijiarui** [comment]
fix
