### ISSUE TITLE
room-leave event throw error, cannot get leaver contact

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1323]
wechaty version: 0.15.150

run `room-bot.ts`, change leave-event related code as follows:
```ts
.on('room-leave', async function(room, leaverList) {
  log.info('Bot', 'EVENT: room-leave - Room %s lost member %s',
                  await room.topic(),
                  leaverList.map(c => c.name()).join(','),
              )
  const topic = await room.topic()
  const name  = leaverList[0] ? leaverList[0].name() : 'no contact!'
  room.say(`kick off ${name} from ${topic}!` )
})

```
get the following error:
```shell
20:02:25 SILL Accessory #20<Message> constructor()
20:02:25 VERB Message constructor(602210585485697964) for class Message
20:02:25 VERB Message ready()
20:02:25 SILL Puppet messagePayloadCache(602210585485697964) cache MISS
20:02:25 VERB Puppet messagePayload(id=602210585485697964, noCache=false)
20:02:25 SILL Puppet messagePayloadCache(602210585485697964) cache MISS
20:02:25 VERB PuppetPadChat messageRawPayloadParser({msg_id="602210585485697964"})
20:02:25 SILL PuppetPadchat messagePayload({"id":"602210585485697964","timestamp":1528891345,"text":"<msg>\n<op id='2'>\n<username>4174082170@chatroom</username>\n</op>\n</msg>","type":0,"fromId":"wxid_zj2cahpwzgie12","roomId":"4174082170@chatroom"})
20:02:25 SILL Puppet messagePayload(602210585485697964) cache SET
20:02:25 SILL Contact ready() @ PuppetPadchat<default>
20:02:25 SILL Contact ready() isReady() true
20:02:25 SILL Accessory #21<Room<>> constructor()
20:02:25 SILL Room constructor(4174082170@chatroom)
20:02:25 VERB Room ready()
20:02:25 VERB Room topic()
20:02:25 SILL Contact alias()
[线上机器人_3]<苏轼>:Message#Unknown(Room<线上机器人_3>▲Contact<苏轼>►)<<msg>
<op id='2'>
<username>4174082170@chatroom</username>
</op>
</msg>
20:02:25 VERB Puppet selfId()
20:02:28 SILL PuppetPadchatManager syncRoomMember(6604854403@chatroom)
20:02:28 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["6604854403@chatroom"])
20:02:28 VERB PuppetPadchatManager startQueues() delayQueueExecutor.subscribe(syncRoomMember(6604854403@chatroom)) executed
20:02:29 SILL PadchatRpc WXGetChatRoomMember() result: {"chatroom_id":700000006,"count":4,"member":"[{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver_1/wN7tTZj7LiaR7k8rqALz17nYnHvTSichOiclE7SB8ljd4u9sZLtJf7ibOa8jXYibTwU5rA7F7zISXG6SxzEKTPSnDaQ/0\",\"chatroom_nick_name\":\"\",\"invited_by\":\"wxid_7708837087612\",\"nick_name\":\"李佳芮\",\"small_head\":\"http://wx.qlogo.cn/mmhead/ver_1/wN7tTZj7LiaR7k8rqALz17nYnHvTSichOiclE7SB8ljd4u9sZLtJf7ibOa8jXYibTwU5rA7F7zISXG6SxzEKTPSnDaQ/132\",\"user_name\":\"qq512436430\"},{\"big_head\":\"http://wx.qlogo.cn/mmhead/ve
20:02:29 SILL PuppetPadchatManager syncRoomMember(6604854403@chatroom) total 6 members
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() syncing 5 out of Contact(258) & Room(214) ...
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() updating Room 小桔AA_6(6679885738@chatroom)
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() added sync room(6679885738@chatroom) task to delayQueueExecutor
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() updating Room 小桔AA_7(6444885432@chatroom)
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() added sync room(6444885432@chatroom) task to delayQueueExecutor
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() updating Room 小桔AA_7(6438884562@chatroom)
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() added sync room(6438884562@chatroom) task to delayQueueExecutor
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() updating Room 小桔测试AA_4(8406007304@chatroom)
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() added sync room(8406007304@chatroom) task to delayQueueExecutor
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() updating Room 小桔测试AA_5(6307884868@chatroom)
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() added sync room(6307884868@chatroom) task to delayQueueExecutor
20:02:32 SILL PuppetPadchatManager syncContactsAndRooms() while() syncing WXSyncContact ...
20:02:32 SILL PadchatRpc rpcCall(WXSyncContact, [])
20:02:32 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
20:02:32 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
20:02:32 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
20:02:33 VERB PuppetPadchat onPadchatMessage({id=4134018574514711479, type=Sys(5)})
rawPayload: { content: '你将"王宁"移出了群聊',
  continue: 1,
  description: '',
  from_user: '4174082170@chatroom',
  msg_id: '4134018574514711479',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 10000,
  timestamp: 1528891352,
  to_user: 'wxid_zj2cahpwzgie12',
  uin: 324216852 }
20:02:33 VERB PuppetPadchat onPadchatMessageFriendshipEvent({id=undefined})
20:02:33 VERB PuppetPadchat onPadchatMessageRoomEvent({id=undefined})
20:02:33 VERB Puppet roomMemberSearch(4174082170@chatroom, "王宁")
20:02:33 VERB Puppet roomMemberSearch(4174082170@chatroom, {"name":"王宁"})
20:02:33 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:02:33 SILL PuppetPadchatManager syncRoomMember(4174082170@chatroom)
20:02:33 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["4174082170@chatroom"])
20:02:33 SILL PadchatRpc WXGetChatRoomMember() result: {"chatroom_id":700000005,"count":2,"member":"[{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver_1/O5NAVwmeMl5n3rWks7QWefY3okwt2QAxPO1eiaBHvEztNPv3t9VBnkNS02cwgZxfx9VqaNRGBxvZMcVnGver1gy7LteMcDGZwn7rNLNqa7no/0\",\"chatroom_nick_name\":\"\",\"invited_by\":\"\",\"nick_name\":\"苏轼\",\"small_head\":\"http://wx.qlogo.cn/mmhead/ver_1/O5NAVwmeMl5n3rWks7QWefY3okwt2QAxPO1eiaBHvEztNPv3t9VBnkNS02cwgZxfx9VqaNRGBxvZMcVnGver1gy7LteMcDGZwn7rNLNqa7no/132\",\"user_name\":\"wxid_zj2cahpwzgie12\"},{\"big_head\":\"http:
20:02:33 SILL PuppetPadchatManager syncRoomMember(4174082170@chatroom) total 6 members
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:02:33 SILL PuppetPadchat roomMemberList()=2
20:02:33 VERB Puppet contactSearch(query={"name":"王宁"}, idList.length = 2)
20:02:33 SILL Puppet contactPayload(wxid_lredtm37y7rc22) cache MISS
20:02:33 SILL PuppetPadchat contactRawPayload(wxid_lredtm37y7rc22)
20:02:33 SILL PuppetPadchatManager contactRawPayload(wxid_lredtm37y7rc22)
20:02:33 SILL PuppetPadchatManager contactRawPayload(wxid_lredtm37y7rc22) retry() attempt=1
20:02:33 SILL PuppetPadchat contactRawPayloadParser({user_name="wxid_lredtm37y7rc22"})
20:02:33 SILL Puppet contactPayload(wxid_lredtm37y7rc22) cache SET
20:02:33 VERB Puppet contactQueryFilterFactory({"name":"王宁"})
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 SILL Puppet roomMemberPayloadCache(4174082170@chatroom) cache MISS
20:02:33 SILL PuppetPadchat roomMemberRawPayload(4174082170@chatroom)
20:02:33 VERB PuppetPadchatManager roomMemberRawPayload(4174082170@chatroom)
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 SILL Puppet roomMemberPayloadCache(4174082170@chatroom) cache MISS
20:02:33 SILL PuppetPadchat roomMemberRawPayload(4174082170@chatroom)
20:02:33 VERB PuppetPadchatManager roomMemberRawPayload(4174082170@chatroom)
20:02:33 SILL PuppetPadchat roomMemberRawPayloadParser([object Object])
20:02:33 SILL PuppetPadchat roomMemberRawPayloadParser([object Object])
20:02:33 SILL Puppet roomMemberPayload(4174082170@chatroom) cache SET
20:02:33 SILL Puppet roomMemberPayload(4174082170@chatroom) cache SET
20:02:33 VERB Puppet roomMemberSearch(4174082170@chatroom, {"contactAlias":"王宁"})
20:02:33 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:02:33 SILL PuppetPadchat roomMemberList()=2
20:02:33 VERB Puppet contactSearch(query={"alias":"王宁"}, idList.length = 2)
20:02:33 VERB Puppet contactQueryFilterFactory({"alias":"王宁"})
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 VERB Puppet roomMemberSearch(4174082170@chatroom, {"roomAlias":"王宁"})
20:02:33 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:02:33 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:02:33 SILL PuppetPadchat roomMemberList()=2
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:02:33 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:02:33 VERB Puppet roomMemberSearch(4174082170@chatroom, undefined)
20:02:33 VERB Room ready()
20:02:33 SILL Contact ready() @ PuppetPadchat<default>
20:02:33 SILL Contact ready() isReady() true
20:02:33 VERB Room topic()
20:02:33 INFO Bot EVENT: room-leave - Room 线上机器人_3 lost member
20:02:33 VERB Room topic()
20:02:33 VERB Room say(kick off no contact! from 线上机器人_3!, )
20:02:33 ERR Config ###########################
20:02:33 ERR Config unhandledRejection: TypeError: Cannot read property 'id' of undefined [object Promise]
20:02:33 ERR Config ###########################
20:02:33 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'id' of undefined)
Config TypeError: Cannot read property 'id' of undefined
    at AnotherOriginalClass.<anonymous> (/Users/egg/git/rui/wechaty/src/room.ts:321:35)
    at Generator.next (<anonymous>)
    at /Users/egg/git/rui/wechaty/src/room.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/egg/git/rui/wechaty/src/room.ts:23:12)
    at AnotherOriginalClass.say (/Users/egg/git/rui/wechaty/src/room.ts:254:16)
    at Wechaty.<anonymous> (/Users/egg/git/rui/wechaty/examples/room-bot.ts:144:8)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/examples/room-bot.ts:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18399) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
20:02:34 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
20:02:35 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}

```

**Comment by lijiarui** [comment]
fix but get a new error: #1329
