### ISSUE TITLE
[room topic event]  throw error: no changerId found

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1326]
#### Wechaty version: 0.15.150

Cannot get changer when a changer change the toom topic

code as follows:
```ts
.on('room-topic', function(room, topic, oldTopic, changer) {
  try {
    log.info('Bot', 'EVENT: room-topic - Room %s change topic from %s to %s by member %s',
                    room,
                    oldTopic,
                    topic,
                    changer,
                )
    room.say(`room-topic - change topic from ${oldTopic} to ${topic} by member ${changer.name()}` )
  } catch (e) {
    log.error('Bot', 'room-topic event exception: %s', e.stack)
  }
})

```

```shell
20:33:36 SILL PuppetPadchatManager syncRoomMember(6433887586@chatroom)
20:33:36 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["6433887586@chatroom"])
20:33:36 VERB PuppetPadchatManager startQueues() delayQueueExecutor.subscribe(syncRoomMember(6433887586@chatroom)) executed
20:33:36 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
20:33:36 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
20:33:36 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
20:33:36 SILL PadchatRpc WXGetChatRoomMember() result: {"chatroom_id":700000001,"count":3,"member":"[{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver_1/Y9W8tLiasksdThST5JCJpsfhZDhxNFVrQfdTlicudK1T7g1Y93icScbEIlGRfWZH6I7pyyfC9ECF8tw70Q4sLVTLA/0\",\"chatroom_nick_name\":\"\",\"invited_by\":\"wxid_zj2cahpwzgie12\",\"nick_name\":\"梦君君\",\"small_head\":\"http://wx.qlogo.cn/mmhead/ver_1/Y9W8tLiasksdThST5JCJpsfhZDhxNFVrQfdTlicudK1T7g1Y93icScbEIlGRfWZH6I7pyyfC9ECF8tw70Q4sLVTLA/132\",\"user_name\":\"mengjunjun001\"},{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver
20:33:36 SILL PuppetPadchatManager syncRoomMember(6433887586@chatroom) total 6 members
20:33:46 VERB PuppetPadchat onPadchatMessage({id=6335934255263293521, type=Sys(5)})
rawPayload: { content: '"李佳芮"修改群名为“线上机器”',
  continue: 1,
  description: '',
  from_user: '4174082170@chatroom',
  msg_id: '6335934255263293521',
  msg_source: '',
  msg_type: 5,
  status: 1,
  sub_type: 10000,
  timestamp: 1528893225,
  to_user: 'wxid_zj2cahpwzgie12',
  uin: 324216852 }
20:33:46 VERB PuppetPadchat onPadchatMessageFriendshipEvent({id=undefined})
20:33:46 VERB PuppetPadchat onPadchatMessageRoomEvent({id=undefined})
20:33:46 VERB Puppet roomPayload(id=4174082170@chatroom, noCache=false)
20:33:46 VERB Puppet roomMemberSearch(4174082170@chatroom, "李佳芮")
20:33:46 VERB Puppet roomMemberSearch(4174082170@chatroom, {"name":"李佳芮"})
20:33:46 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:33:46 SILL PuppetPadchat roomMemberList()=2
20:33:46 VERB Puppet contactSearch(query={"name":"李佳芮"}, idList.length = 2)
20:33:46 VERB Puppet contactQueryFilterFactory({"name":"李佳芮"})
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 VERB Puppet roomMemberSearch(4174082170@chatroom, {"contactAlias":"李佳芮"})
20:33:46 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:33:46 SILL PuppetPadchat roomMemberList()=2
20:33:46 VERB Puppet contactSearch(query={"alias":"李佳芮"}, idList.length = 2)
20:33:46 VERB Puppet contactQueryFilterFactory({"alias":"李佳芮"})
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 VERB Puppet roomMemberSearch(4174082170@chatroom, {"roomAlias":"李佳芮"})
20:33:46 VERB PuppetPadchat roomMemberList(4174082170@chatroom)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170)
20:33:46 VERB PuppetPadchatManager getRoomMemberIdList(4174082170) length=2
20:33:46 SILL PuppetPadchat roomMemberList()=2
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_zj2cahpwzgie12 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 VERB Puppet roomMemberPayload(roomId=4174082170@chatroom, contactId=wxid_lredtm37y7rc22 noCache=false)
20:33:46 SILL Puppet roomMemberPayloadCache(id=4174082170@chatroom) @ PuppetPadchat<default>
20:33:46 ERR Config ###########################
20:33:46 ERR Config unhandledRejection: Error: no changerId found [object Promise]
20:33:46 ERR Config ###########################
20:33:46 ERR Config process.on(unhandledRejection) promise.catch(no changerId found)
Config Error: no changerId found
    at PuppetPadchat.<anonymous> (/Users/egg/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:393:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/src/puppet-padchat/puppet-padchat.ts:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18495) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
20:33:46 SILL PadchatRpc onSocketTencent() discard empty message msg_id payoad: {"continue":0,"msg_type":32768,"status":1,"uin":324216852}
20:33:51 SILL PuppetPadchatManager syncRoomMember(8463009856@chatroom)
20:33:51 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["8463009856@chatroom"])
20:33:51 VERB PuppetPadchatManager startQueues() delayQueueExecutor.subscribe(syncRoomMember(8463009856@chatroom)) executed
20:33:51 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
20:33:51 SILL PuppetPadchat startWatchdog() bridge.on(heartbeat)
20:33:51 SILL PuppetPadchat startWatchdog() watchdog.on(feed, food={type=undefined, data=ws.on(message)})
20:33:51 SILL PadchatRpc WXGetChatRoomMember() result: {"chatroom_id":700000001,"count":3,"member":"[{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver_1/Y9W8tLiasksdThST5JCJpsfhZDhxNFVrQfdTlicudK1T7g1Y93icScbEIlGRfWZH6I7pyyfC9ECF8tw70Q4sLVTLA/0\",\"chatroom_nick_name\":\"\",\"invited_by\":\"wxid_zj2cahpwzgie12\",\"nick_name\":\"梦君君\",\"small_head\":\"http://wx.qlogo.cn/mmhead/ver_1/Y9W8tLiasksdThST5JCJpsfhZDhxNFVrQfdTlicudK1T7g1Y93icScbEIlGRfWZH6I7pyyfC9ECF8tw70Q4sLVTLA/132\",\"user_name\":\"mengjunjun001\"},{\"big_head\":\"http://wx.qlogo.cn/mmhead/ver
20:33:51 SILL PuppetPadchatManager syncRoomMember(8463009856@chatroom) total 6 members
20:34:06 SILL PuppetPadchatManager syncRoomMember(6959885422@chatroom)
20:34:06 SILL PadchatRpc rpcCall(WXGetChatRoomMember, ["6959885422@chatroom"])
20:34:06 VERB PuppetPadchatManager startQueues() delayQueueExecutor.subscribe(syncRoomMember(6959885422@chatroom)) executed

```

**Comment by zixia** [comment]
I believe this issue has been resolved.

**Comment by lijiarui** [comment]
fixed
