### ISSUE TITLE
room-leave error

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1334]
```shell
23:58:37 SILL PadchatRpc rpcCall(WXSendMsg, ["6350854677@chatroom","kick off no contact! from ding - welcome 太阁_传话助手!",""])
23:58:37 ERR Config ###########################
23:58:37 ERR Config unhandledRejection: TypeError: leaver.name is not a function [object Promise]
23:58:37 ERR Config ###########################
23:58:37 ERR Config process.on(unhandledRejection) promise.catch(leaver.name is not a function)
Config TypeError: leaver.name is not a function
    at AnotherOriginalClass.room.on (/Users/egg/git/rui/wechaty/examples/room-bot.ts:290:70)
    at AnotherOriginalClass.emit (events.js:182:13)
    at AnotherOriginalClass.EventEmitter.emit (domain.js:442:20)
    at AnotherOriginalClass.emit (/Users/egg/git/rui/wechaty/src/room.ts:345:18)
    at Wechaty.<anonymous> (/Users/egg/git/rui/wechaty/src/wechaty.ts:630:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/egg/git/rui/wechaty/src/wechaty.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by zixia** [comment]
Could you please to confirm whether this issue has been fixed?

Please notice that the arguments of the `room-leave` event had been fixed to `Contact[]`

**Comment by lijiarui** [comment]
fixed
