### ISSUE TITLE
WXGetContact cannot get user_name

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1358]
`6061139518@chatroom` is a Chatroom that the bot was invited into it before, but had been removed out later.

```
16:42:13 WARN PadchatRpc WXGetContact cannot get user_name, id: 6061139518@chatroom, "{"big_head":"","city":"","country":"","intro":"","label":"","message":"","nick_name":"","provincia":"","py_initial":"","quan_pin":"","remark":"","remark_py_initial":"","remark_quan_pin":"","sex":0,"signature":"","small_head":"","status":0,"stranger":"","ticket":"","user_name":""}"
(node:66580) UnhandledPromiseRejectionWarning: Error: tryRawPayload empty
    at PadchatManager.<anonymous> (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:958:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:66580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
16:42:13 WARN PadchatRpc WXGetContact cannot get user_name, id: 6061139518@chatroom, "{"big_head":"","city":"","country":"","intro":"","label":"","message":"","nick_name":"","provincia":"","py_initial":"","quan_pin":"","remark":"","remark_py_initial":"","remark_quan_pin":"","sex":0,"signature":"","small_head":"","status":0,"stranger":"","ticket":"","user_name":""}"
(node:66580) UnhandledPromiseRejectionWarning: Error: tryRawPayload empty
    at PadchatManager.<anonymous> (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:958:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:66580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

**Comment by zixia** [comment]
Close this issue because it will be continue discussing on its own repo.
