### ISSUE TITLE
BREAKING CHANGE v0.16  Contact, FriendRequest, Message, and Room classes will not be able to instantiate directly

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1364]
see more in #1217 #1161 

### Before
```ts
import { Contact } from 'wechaty'
const contact = await Contact.find({name: '李佳芮'})

import { Room } from 'wechaty'
const roomList = await Room.findAll()

const room = await Room.create(contactList, roomTopic)

```
### After
```ts
import { Wechaty } from 'wechaty'

const wechaty = Wechaty.instance()

const contact = await wechaty.Contact.find({name: '李佳芮'})

const roomList = await wechaty.Room.findAll()

const room = await wechaty.Room.create(contactList, roomTopic)
```

Or, it may get error log as follows:
```shell
Error: static puppet not found for Room
    at Function.get puppet [as puppet] (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/src/accessory.ts:54:11)
    at Function.<anonymous> (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/src/user/room.ts:123:37)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:23:12)
    at Function.findAll (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:123:16)
    at Function.<anonymous> (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/src/user/room.ts:150:33)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:23:12)
    at Function.find (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/user/room.js:149:16)
    at Function.<anonymous> (/Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:33:34)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:3:12)
    at matchList.forEach (/Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:31:46)
    at Array.forEach (<anonymous>)
    at Function.<anonymous> (/Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:31:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/xiaoju-bot/src/bot/room-add.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by zixia** [comment]
1. Breaking change is very rare and there's no need to create a new issue tag for it. Please remove and clean it
2. Please add the version to the title, as I had already replied you in the other issue.

**Comment by lijiarui** [comment]
When I  migration from `puppeteer` to `puppet-padchat`, I found nearly 10 breaking changes, if we have this label, maybe it will make it easier for developers to find break changes.

At least, I think this label should keep for a while when alpha test is finished. Then I will remove and clean it.

**Comment by zixia** [comment]
> At least, I think this label should keep for a while when alpha test is finished. Then I will remove and clean it.

OK.

**Comment by zixia** [comment]
Merge to #1217
