### ISSUE TITLE
 no encodedText error in `padchat-decode.ts`

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1365]
Wechaty version

wechaty@0.15.202
npm: wechaty@next

```shell
Error: no encodedText
    at Object.padchatDecode (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/src/puppet-padchat/pure-function-helpers/padchat-decode.ts:4:11)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/src/puppet-padchat/padchat-rpc.ts:702:64)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/xiaoju-bot/node_modules/wechaty/dist/src/puppet-padchat/padchat-rpc.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
decode error data:  undefined
16:21:19 WARN PadchatRpc WXGetChatRoomMember(9486025987@chatroom) result.member decode error: Error: no encodedText
```

**Comment by zixia** [comment]
Move to https://github.com/lijiarui/wechaty-puppet-padchat/issues/66
