### ISSUE TITLE
PuppetPadchat: Cannot read property 'user_name' of undefined

### ISSUE THREAD

**Issue by qhduan** [Chatie/wechaty#1392]
latest docker image

```
zixia/wechaty                                   latest              8ff60183ce6f        14 hours ago        1.32GB
```

```shell
# PASTE FULL LOG OUTPUT AT HERE:

16:01:25 ERR Config ###########################
16:01:25 ERR Config unhandledRejection: TypeError: Cannot read property 'user_name' of undefined [object Promise]
16:01:25 ERR Config ###########################
16:01:25 ERR Config ###########################
16:01:25 ERR Config unhandledRejection: TypeError: Cannot read property 'user_name' of undefined [object Promise]
16:01:25 ERR Config ###########################
16:01:25 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'user_name' of undefined)
Config TypeError: Cannot read property 'user_name' of undefined
    at PuppetPadchat.<anonymous> (/wechaty/src/puppet-padchat/puppet-padchat.ts:943:30)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/puppet-padchat/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/puppet-padchat/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/wechaty/dist/src/puppet-padchat/puppet-padchat.js:697:16)
    at PuppetPadchat.<anonymous> (/wechaty/src/puppet/puppet.ts:913:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet/puppet.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
16:01:25 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'user_name' of undefined)
Config TypeError: Cannot read property 'user_name' of undefined
    at PuppetPadchat.<anonymous> (/wechaty/src/puppet-padchat/puppet-padchat.ts:943:30)
    at Generator.next (<anonymous>)
    at /wechaty/dist/src/puppet-padchat/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/wechaty/dist/src/puppet-padchat/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/wechaty/dist/src/puppet-padchat/puppet-padchat.js:697:16)
    at PuppetPadchat.<anonymous> (/wechaty/src/puppet/puppet.ts:913:35)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet/puppet.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by zixia** [comment]
### Need More Information

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment]
Close this issue due to inactive for more than two weeks.
