### ISSUE TITLE
It reports errors when the room delete one member.

### ISSUE THREAD

**Issue by zhoumh1988** [Chatie/wechaty#1415]
```
0|mybot    | 16:55:04 WARN Room find() got more than one(2) result
0|mybot    | 16:55:04 WARN PadchatRpc WXAddChatRoomMember() status = 0 but message is not OK:
0|mybot    | MemberList are wrong
0|mybot    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|mybot    | Error: WXDeleteChatRoomMember error! canot get result from websocket server
0|mybot    |     at PadchatManager.<anonymous> (/Users/zhouminghua/Documents/mp/puppetpadchat/node_modules/wechaty/dist/src/puppet-padchat/padchat-rpc.js:655:23)
0|mybot    |     at Generator.next (<anonymous>)
0|mybot    |     at fulfilled (/Users/zhouminghua/Documents/mp/puppetpadchat/node_modules/wechaty/dist/src/puppet-padchat/padchat-rpc.js:4:58)
0|mybot    |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
My code：
```node
    if (/out/.test(content) && room && room.id == 'roomid') {
        await room.say("Remove from the room", sender);
        await room.del(sender);
        return;
    }
```

**Comment by zhoumh1988** [comment]
Beacuse the room is not mine. My mistake
