### ISSUE TITLE
PuppetPadchat:My wechat accou can not login.

### ISSUE THREAD

**Issue by zhoumh1988** [Chatie/wechaty#1416]
```
0|mybot    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|mybot    | OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/contact-raw-payload/LOCK: Resource temporarily unavailable
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/levelup/lib/levelup.js:88:23
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/deferred-leveldown.js:19:21
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:594:16
0|mybot    |     at Immediate._onImmediate (/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:282:13)
0|mybot    |     at runCallback (timers.js:810:20)
0|mybot    |     at tryOnImmediate (timers.js:768:5)
0|mybot    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config unhandledRejection: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/contact-raw-payload/LOCK: Resource temporarily unavailable [object Promise]
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config unhandledRejection: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-member-raw-payload/LOCK: Resource temporarily unavailable [object Promise]
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config unhandledRejection: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-raw-payload/LOCK: Resource temporarily unavailable [object Promise]
0|mybot    | 17:10:04 ERR Config ###########################
0|mybot    | 17:10:04 ERR Config process.on(unhandledRejection) promise.catch(EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/contact-raw-payload/LOCK: Resource temporarily unavailable)
0|mybot    | Config { OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/contact-raw-payload/LOCK: Resource temporarily unavailable
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/levelup/lib/levelup.js:88:23
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/deferred-leveldown.js:19:21
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:594:16
0|mybot    |     at Immediate._onImmediate (/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:282:13)
0|mybot    |     at runCallback (timers.js:810:20)
0|mybot    |     at tryOnImmediate (timers.js:768:5)
0|mybot    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|mybot    |   stackframes: 
0|mybot    |    [ { file_name: '/data/server/project/puppetpadchat/node_modules/levelup/lib/levelup.js',
0|mybot    |        line_number: 88 },
0|mybot    |      { file_name: '/data/server/project/puppetpadchat/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js',
0|mybot    |        line_number: 39 },
0|mybot    |      { file_name: '/data/server/project/puppetpadchat/node_modules/deferred-leveldown/deferred-leveldown.js',
0|mybot    |        line_number: 19 },
0|mybot    |      { file_name: '/data/server/project/puppetpadchat/node_modules/abstract-leveldown/abstract-leveldown.js',
0|mybot    |        line_number: 39 },
0|mybot    |      { file_name: '/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js',
0|mybot    |        line_number: 594 },
0|mybot    |      { file_name: '/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js',
0|mybot    |        line_number: 282 },
0|mybot    |      { file_name: 'timers.js', line_number: 810 },
0|mybot    |      { file_name: 'timers.js', line_number: 768 },
0|mybot    |      { file_name: 'timers.js', line_number: 745 } ] }
0|mybot    | 17:10:04 ERR Config process.on(unhandledRejection) promise.catch(EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-member-raw-payload/LOCK: Resource temporarily unavailable)
0|mybot    | Config OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-member-raw-payload/LOCK: Resource temporarily unavailable
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/levelup/lib/levelup.js:88:23
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/deferred-leveldown.js:19:21
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:594:16
0|mybot    |     at Immediate._onImmediate (/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:282:13)
0|mybot    |     at runCallback (timers.js:810:20)
0|mybot    |     at tryOnImmediate (timers.js:768:5)
0|mybot    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|mybot    | 17:10:04 ERR Config process.on(unhandledRejection) promise.catch(EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-raw-payload/LOCK: Resource temporarily unavailable)
0|mybot    | Config OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-raw-payload/LOCK: Resource temporarily unavailable
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/levelup/lib/levelup.js:88:23
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/deferred-leveldown/deferred-leveldown.js:19:21
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
0|mybot    |     at /data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:594:16
0|mybot    |     at Immediate._onImmediate (/data/server/project/puppetpadchat/node_modules/abstract-nosql/abstract-nosql.js:282:13)
0|mybot    |     at runCallback (timers.js:810:20)
0|mybot    |     at tryOnImmediate (timers.js:768:5)
0|mybot    |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|mybot    | (node:29142) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
0|mybot    | (node:29142) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
0|mybot    | (node:29142) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Comment by zixia** [comment]
> 0|mybot    | Config OpenError: EIO, IO error: lock /root/.wechaty/puppet-padchat-cache/padchat-token-LittleStrongZhou/zhoumh1988/room-raw-payload/LOCK: Resource temporarily unavailable

This message means that you have already had a instance running at the same time.

**Comment by zhoumh1988** [comment]
That means the token only used one instance?

**Comment by lijiarui** [comment]
No, it means you can run one instance **at the same time**.
