### ISSUE TITLE
ReadError: Database is not open [object Promise] - FlashStoreSync was closed when need writing

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1433]
```
02:00:04 WARN PadchatRpc initWebSocket() ws.on(close) 1005
02:00:04 WARN PuppetPadchat startManager() manager.on(reset) for ws.on(close, 1005. Restarting PuppetPadchat ... 
02:00:04 WARN PuppetPadchat logout() this.id not exist
02:00:06 ERR Config ###########################
02:00:06 ERR Config unhandledRejection: ReadError: Database is not open [object Promise]
02:00:06 ERR Config ###########################
02:00:06 ERR Config process.on(unhandledRejection) promise.catch(Database is not open)
Config ReadError: Database is not open
    at maybeError (/home/zixia/chatie/wechaty/node_modules/levelup/lib/levelup.js:288:32)
    at LevelUP.del (/home/zixia/chatie/wechaty/node_modules/levelup/lib/levelup.js:206:7)
    at FlashStore$1.<anonymous> (/home/zixia/chatie/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:242:63)
    at step (/home/zixia/chatie/wechaty/node_modules/flash-store/dist/flash-store.js:1:18)
    at Object.next (/home/zixia/chatie/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:4:53)
    at /home/zixia/chatie/wechaty/node_modules/flash-store/dist/flash-store.js:57:52
    at new Promise (<anonymous>)
    at __awaiter$1 (/home/zixia/chatie/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:58:16)
    at FlashStore$1.delete (/home/zixia/chatie/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:237:20)
    at FlashStoreSync.delete (/home/zixia/chatie/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:842:53)
    at PadchatManager.<anonymous> (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:292:41)
    at Generator.next (<anonymous>)
    at fulfilled (/home/zixia/chatie/wechaty/src/puppet-padchat/padchat-manager.ts:4:58)
(node:64834) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 28)
```

**Comment by zhaokefei** [comment]
I also encountered a similar problem. 

### I manually performed an exit login on my phone and then the following error occurred.
![2951531100929_ pic_hd](https://user-images.githubusercontent.com/16509241/42428421-20df177e-8366-11e8-841c-a00421ee1eea.jpg)

**Comment by zixia** [comment]
@zhaokefei Could you please set the log level to `silly` by set `WECHATY_LOG=silly` and post the text log message to this issue again? That would be more helpful.

**Comment by zixia** [comment]
Close this issue because we did not see this problem for more than 30 days and no one could be able to provide the reproduce steps.
