### ISSUE TITLE
v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) ()

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1438]
```sh
zixia@sg:~/chatie/wechaty$ ls -l core 
-rw------- 1 zixia zixia 1651720192 Jul  1 05:04 core

zixia@sg:~/chatie/wechaty$ gdb /usr/bin/node core
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/node...(no debugging symbols found)...done.
[New LWP 56552]
[New LWP 56554]
[New LWP 56558]
[New LWP 56565]
[New LWP 56566]
[New LWP 56567]
[New LWP 56568]
[New LWP 56663]
[New LWP 56557]
[New LWP 56556]
[New LWP 56555]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `node ./node_modules/.bin/ts-node examples/ding-dong-bot.ts'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f8f754d1428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8f76945740 (LWP 56552))]
(gdb) bt
#0  0x00007f8f754d1428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f8f754d302a in __GI_abort () at abort.c:89
#2  0x0000000000893721 in node::Abort() ()
#3  0x000000000089375c in ?? ()
#4  0x0000000000a73f2e in v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) ()
#5  0x0000000000a74148 in v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) ()
#6  0x0000000000e616b2 in v8::internal::Heap::FatalProcessOutOfMemory(char const*) ()
#7  0x0000000000e6d5da in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#8  0x0000000000e6df44 in v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ()
#9  0x0000000000e70875 in v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) ()
#10 0x0000000000e38da4 in v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) ()
#11 0x00000000010d908e in v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) ()
#12 0x000017b7da5841bd in ?? ()
#13 0x000017b700000e16 in ?? ()
#14 0x000017b7da584121 in ?? ()
#15 0x00007ffc98b19270 in ?? ()
#16 0x0000000000000006 in ?? ()
#17 0x00007ffc98b192f0 in ?? ()
#18 0x000017b7dad295dd in ?? ()
#19 0x0000003800000000 in ?? ()
#20 0x0000000000000004 in ?? ()
#21 0x00007ffc98b19330 in ?? ()
#22 0x00000000028781e0 in ?? ()
#23 0x00007ffc98b19418 in ?? ()
#24 0x00000000028f17c0 in ?? ()
#25 0x00002b220e8a7ff1 in ?? ()
#26 0x00001e694ca2ffc1 in ?? ()
#27 0x00002ee6a74ab621 in ?? ()
#28 0x00002160207605e9 in ?? ()
#29 0x00007ffc98b19330 in ?? ()
#30 0x000017b7da58c223 in ?? ()
#31 0x00000b967e04d911 in ?? ()
#32 0x000031275d9db8b9 in ?? ()
#33 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by zixia** [comment]
Duplicated with #1435
