### ISSUE TITLE
PuppetPadChat:Contact.avatar() Error

### ISSUE THREAD

**Issue by zhoumh1988** [Chatie/wechaty#1473]
```ssh
0|lightbot | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|lightbot | Error: no avatar
0|lightbot |     at PuppetPadchat.<anonymous> (/Users/zhouminghua/Documents/mp/lightbot/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:449:23)
0|lightbot |     at Generator.next (<anonymous>)
0|lightbot |     at fulfilled (/Users/zhouminghua/Documents/mp/lightbot/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:22:58)
0|lightbot |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
When I get contact avatar.

```node
let rooms = bot.Room.findAll();
rooms.forEach(async r => {
    let members = await r.memberList();
    membders.forEach(aynsc c => {
        let avatar = await contact.avatar();
    });
});
```

**Comment by lijiarui** [comment]
Are you sure room or contact exist?

Could you change as follows and have a try:

```
let rooms = bot.Room.findAll();
rooms.forEach(async r => {
    if (r) {
      let members = await r.memberList();
      membders.forEach(aynsc c => {
          if (c) {
             let avatar = await contact.avatar();
          }
    });
    }
});
```

**Comment by zhoumh1988** [comment]
Why memberList has the contact who not exist in the room.
I test, it works.

**Comment by lijiarui** [comment]
when the contact exist the room byhimself, wechaty cannot detect that thing.

**Comment by zhoumh1988** [comment]
OK,I know.

**Comment by zixia** [comment]
@zhoumh1988 Thanks for reporting. 

I reopen this because we should deal with this situation instead of an unhandledRejection.
