### ISSUE TITLE
When i'm trying to create a room, it show me that it could not find roomId.

### ISSUE THREAD

**Issue by apiaoqzh** [Chatie/wechaty#1495]
### When i'm trying to create a room, it show me that it could not find roomId.
The output like this:
```
00:51:05 WARN PuppetPuppeteer roomCreate(@ad23585c5a4d37bd51857045f1956eb7,@c62b31b53d52750d554d7e8ad90c51324475f54df3930e80e3eb2d29aadf6f5a, ding) rejected: PuppetPuppeteer.roomCreate() roomId "" not found
00:51:05 ERR Room create() exception: Error: PuppetPuppeteer.roomCreate() roomId "" not found
    at PuppetPuppeteer.<anonymous> (/home/other/inrice-wechaty-demo/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:731:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/other/inrice-wechaty-demo/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:19657) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: PuppetPuppeteer.roomCreate() roomId "" not found
(node:19657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This is my code:
```ts
  async function createRoom () {
  const apiao = await bot.Contact.find({alias: 'GM.apiao'})
  const yujia = await bot.Contact.find({alias: 'GM.宇佳'})
  const contactList = [apiao, yujia]
  const room = await bot.Room.create(contactList, 'ding')
  await room.say('建群成功')
}
```

**Comment by lijiarui** [comment]
Web wechat can create room at this period, please try your web wechat on http://wx.qq.com/ , to see whether you can create room manually.

This function only support by wechaty-puppet-padchat at this period.

**Comment by zixia** [comment]
Close this issue for no response for more than 5 days.
