### ISSUE TITLE
pacchat: ERR! 404 Not Found: padchat@latest

### ISSUE THREAD

**Issue by kis87988** [Chatie/wechaty#1496]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) U.S.
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? self
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
docker 
wechaty version: 0.19.104

### Expected behavior
run wechaty with docker container

### Actual behavior
Padchat@latest version not found 

### Steps to reproduce the behavior (and fixes, if any)

> If you know c9 IDE, please goto https://ide.c9.io/zixia/wechaty-bug-reproducer to apply a write access for the workspace so that you can put your reproduceable code over there. If you did that, your issue will be classified with HIGH priority and we will deal with the high priority issues first.

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:
 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           
WECHATY Environment Variables: 4
WECHATY_PUPPET=padchat
WECHATY_LOG=silly
WECHATY_PUPPET_PADCHAT_TOKEN=padchat-token-kis87988
WECHATY_DOCKER=1

Starting Docker Container for Wechaty v0.19.104 with Node.js v10.7.0 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended on your bot script.
Executing ts-node WilliamDABot.ts
11:20:16 SILL Config WECHATY_LOG set level to silly
11:20:16 INFO Config registering process.on("unhandledRejection") for development/debug
11:20:16 VERB Config constructor()
11:20:17 SILL Accessory #0<Wechaty> constructor()
11:20:17 VERB Wechaty contructor()
11:20:17 VERB MemoryCard constructor(Ponyo)
11:20:17 VERB StateSwitch constructor(name=Wechaty)
11:20:17 VERB Wechaty on(logout, function) registered
11:20:17 VERB Wechaty onFunction(logout)
11:20:17 VERB Wechaty on(login, function) registered
11:20:17 VERB Wechaty onFunction(login)
11:20:17 VERB Wechaty on(scan, function) registered
11:20:17 VERB Wechaty onFunction(scan)
11:20:17 VERB Wechaty on(room-join, function) registered
11:20:17 VERB Wechaty onFunction(room-join)
11:20:17 VERB Wechaty on(friendship, function) registered
11:20:17 VERB Wechaty onFunction(friendship)
11:20:17 VERB Wechaty on(message, function) registered
11:20:17 VERB Wechaty onFunction(message)
11:20:17 VERB Wechaty on(error, function) registered
11:20:17 VERB Wechaty onFunction(error)
11:20:17 SILL Wechaty version() form development environment is not availble: ENOENT: no such file or directory, stat '/wechaty/dist/.git'
11:20:17 INFO Wechaty <padchat> start() v0.19.104 is starting...
11:20:17 VERB Wechaty puppet: undefined
11:20:17 VERB Wechaty profile: Ponyo
11:20:17 VERB Wechaty id: cjjx63qbl00000qum3a1s1tcc
11:20:17 SILL StateSwitch <Wechaty> on() is false
11:20:17 SILL StateSwitch <Wechaty> on() is false
11:20:17 VERB StateSwitch <Wechaty> on(pending) <- (false)
11:20:17 VERB MemoryCard load() file: /bot/Ponyo.memory-card.json
11:20:17 VERB Wechaty initPuppet() 
11:20:17 VERB MemoryCard sub(padchat)
11:20:17 VERB MemoryCard static sub(MemoryCard<Ponyo>, padchat)
11:20:17 VERB MemoryCard constructor(Ponyo)
11:20:17 VERB PuppetManager resolve({wechaty: Wechaty#cjjx63qbl00000qum3a1s1tcc<>(Ponyo), puppet: padchat, puppetOptions: undefined})
11:20:17 VERB PuppetManager resolveName(padchat)
11:20:17 VERB PuppetManager checkModule(padchat)
11:20:17 INFO PuppetManager install(padchat@latest) please wait ...
npm: npm
npm:  WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".

npm: npm
npm:  ERR! code E404

npm: npm
npm:  ERR! 404 Not Found: padchat@latest

npm: 

npm: npm ERR! A complete log of this run can be found in:
npm ERR!
npm:      /bot/.npm/_logs/2018-07-22T18_20_26_334Z-debug.log

{ Error: Command failed: npm install padchat@latest 
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: padchat@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2018-07-22T18_20_26_334Z-debug.log

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: [33mfalse[39m,
  code: [33m1[39m,
  signal: [1mnull[22m,
  cmd: [32m'npm install padchat@latest '[39m }
11:20:26 ERR Wechaty start() exception: Command failed: npm install padchat@latest 
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: padchat@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2018-07-22T18_20_26_334Z-debug.log

11:20:26 ERR Bot error: Error: Command failed: npm install padchat@latest 
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: padchat@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2018-07-22T18_20_26_334Z-debug.log

11:20:26 SILL Wechaty version() form development environment is not availble: ENOENT: no such file or directory, stat '/wechaty/dist/.git'
11:20:26 INFO Wechaty <padchat> stop() v0.19.104 is stoping ...
11:20:26 SILL StateSwitch <Wechaty> off() is false
11:20:26 SILL StateSwitch <Wechaty> off() is false
11:20:26 VERB StateSwitch <Wechaty> off(pending) <- (false)
11:20:26 VERB MemoryCard <> save() file: /bot/Ponyo.memory-card.json
11:20:26 ERR Config ###########################
11:20:26 ERR Config unhandledRejection: Error: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217 [object Promise]
11:20:26 ERR Config ###########################
11:20:26 ERR Config process.on(unhandledRejection) promise.catch(static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217)
Config Error: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217
    at Function.get puppet [as puppet] (/wechaty/src/accessory.ts:60:11)
    at Wechaty.get puppet [as puppet] (/wechaty/src/accessory.ts:149:44)
    at Wechaty.logonoff (/wechaty/src/wechaty.ts:892:17)
    at Object.<anonymous> (/bot/WilliamDABot.ts:345:11)
    at Generator.next (<anonymous>)
    at /bot/WilliamDABot.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/WilliamDABot.ts:3:12)
    at Wechaty.bot.on (/bot/WilliamDABot.ts:341:27)
    at Wechaty.on.args (/wechaty/src/wechaty.ts:506:18)
    at Wechaty.emit (events.js:182:13)
    at Wechaty.EventEmitter.emit (domain.js:442:20)
    at Wechaty.emit (/wechaty/src/wechaty.ts:290:18)
    at Wechaty.<anonymous> (/wechaty/src/wechaty.ts:778:12)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/dist/src/wechaty.js:5:65)
(node:26) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
11:20:26 WARN Wechaty stop() puppet.stop() exception: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217
11:20:26 SILL StateSwitch <Wechaty> off() is pending
11:20:26 VERB StateSwitch <Wechaty> off(true) <- (pending)
11:20:26 INFO Bot finis(99, uncaughtException)
11:20:26 ERR Config ###########################
11:20:26 ERR Config unhandledRejection: Error: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217 [object Promise]
11:20:26 ERR Config ###########################
11:20:26 ERR Config process.on(unhandledRejection) promise.catch(static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217)
Config Error: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217
    at Function.get puppet [as puppet] (/wechaty/src/accessory.ts:60:11)
    at Wechaty.get puppet [as puppet] (/wechaty/src/accessory.ts:149:44)
    at Wechaty.logonoff (/wechaty/src/wechaty.ts:892:17)
    at Object.<anonymous> (/bot/WilliamDABot.ts:378:12)
    at Generator.next (<anonymous>)
    at /bot/WilliamDABot.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/WilliamDABot.ts:3:12)
    at process.finis_1.finis (/bot/WilliamDABot.ts:374:30)
    at process.emit (events.js:182:13)
    at process.EventEmitter.emit (domain.js:442:20)
    at process.emit (/wechaty/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:454:21)
    at process.on.err (/wechaty/node_modules/finis/index.js:28:50)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process.emit (/wechaty/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:454:21)
    at process._fatalException (internal/bootstrap/node.js:472:27)
(node:26) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
Error: static puppet not found for Wechaty, please see issue #1217: https://github.com/Chatie/wechaty/issues/1217
    at Function.get puppet [as puppet] (/wechaty/src/accessory.ts:60:11)
    at Wechaty.get puppet [as puppet] (/wechaty/src/accessory.ts:149:44)
    at Immediate.setImmediate (/wechaty/src/wechaty.ts:855:29)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
11:20:26 INFO Bot finis(1, exit)
  ____  _   _  ____   ____  _____ ____   ___  ____ _____  
 | __ )| | | |/ ___| |  _ \| ____|  _ \ / _ \|  _ \_   _| 
 |  _ \| | | | |  _  | |_) |  _| | |_) | | | | |_) || |   
 | |_) | |_| | |_| | |  _ <| |___|  __/| |_| |  _ < | |   
 |____/ \___/ \____| |_| \_\_____|_|    \___/|_| \_\|_|   
                                                          
Press ENTER to continue ... 


```
</details>

**Comment by kis87988** [comment]
I check the commit log and found the issue is ENV variables should use full name.
ref: https://github.com/Chatie/wechaty/commit/0eda15b2cbb5b48f93e210702e6d4a6bf71d2390

**Comment by zixia** [comment]
Yes, we had decided to change puppet name yesterday.

Sorry for the breaking change.

**Comment by zixia** [comment]
I added a compatible code to allow the `padchat` to be used with the latest version of the master code.

So the new design will not break the old codes. Please let me know if you still have problems.
