### ISSUE TITLE
在服务器上不能启动

### ISSUE THREAD

**Issue by lv-jie** [Chatie/wechaty#1515]
14:22:07 INFO Wechaty <default> start() v0.18.5 is starting...
14:22:07 INFO Wechaty initPuppet() using puppet: default
14:22:07 INFO Wechaty initPuppet() inited puppet: Puppet#0<PuppetPuppeteer>(default)
14:22:07 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

14:22:07 ERR PuppetPuppeteer initBridge() exception: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: no page
    at Bridge.<anonymous> (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:253:23)
    at Generator.next (<anonymous>)
    at /home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:22:12)
    at Bridge.stop (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:250:16)
    at PuppetPuppeteer.<anonymous> (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:219:35)
    at Generator.throw (<anonymous>)
    at rejected (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
14:22:07 ERR PuppetPuppeteer start() exception: Error: Error: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/dist/src/wechaty.js:415:44)
    at emitOne (events.js:116:13)
    at PuppetPuppeteer.emit (events.js:211:7)
    at PuppetPuppeteer.emit (/home/webgame/nodeSever/hongbao/node_modules/_wechaty-puppet@0.8.5@wechaty-puppet/dist/src/puppet.js:168:22)
    at PuppetPuppeteer.<anonymous> (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
14:22:07 ERR Wechaty start() exception: Error: Error: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome!
/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/dist/src/wechaty.js:415:44)
    at emitOne (events.js:116:13)
    at PuppetPuppeteer.emit (events.js:211:7)
    at PuppetPuppeteer.emit (/home/webgame/nodeSever/hongbao/node_modules/_wechaty-puppet@0.8.5@wechaty-puppet/dist/src/puppet.js:168:22)
    at PuppetPuppeteer.<anonymous> (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/home/webgame/nodeSever/hongbao/node_modules/_wechaty@0.18.5@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by zixia** [comment]
If you are using Ubuntu Linux, try to run:
```
sudo apt-get install libxss1
```

**Comment by zixia** [comment]
Merge to #1152

**Comment by heiyanshooter** [comment]
centos的用户可以安装这些依赖

 1.yum install libXScrnSaver*

2.yum install epel-release

3.yum install libappindicator-gtk3

原文：https://blog.csdn.net/f1370335844/article/details/80460071

**Comment by PIPIPIKa** [comment]
I use ubuntu in Windows. And igot the same erro. But after i running  "apt-get install libxss1" i still get these errors.---->

**Comment by PIPIPIKa** [comment]
node bot.js
23:40:06 INFO Wechaty <default> start() v0.26.1 is starting...
23:40:07 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

23:40:07 ERR PuppetPuppeteer initBridge() exception: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

23:40:07 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
23:40:07 ERR PuppetPuppeteer start() exception: Error: Error: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (/root/node_modules/wechaty/dist/src/wechaty.js:437:44)
    at PuppetPuppeteer.emit (events.js:198:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:448:20)
    at PuppetPuppeteer.emit (/root/node_modules/wechaty-puppet/dist/src/puppet.js:164:22)
    at PuppetPuppeteer.<anonymous> (/root/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/root/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
23:40:07 ERR Wechaty start() exception: Error: Error: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:95) UnhandledPromiseRejectionWarning: Error: Error: Error: Error: Failed to launch chrome!
/root/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (/root/node_modules/wechaty/dist/src/wechaty.js:437:44)
    at PuppetPuppeteer.emit (events.js:198:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:448:20)
    at PuppetPuppeteer.emit (/root/node_modules/wechaty-puppet/dist/src/puppet.js:164:22)
    at PuppetPuppeteer.<anonymous> (/root/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/root/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:95) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:95) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by matrixhome** [comment]
> I use ubuntu in Windows. And igot the same erro. But after i running "apt-get install libxss1" i still get these errors.---->

 i still get these errors too.

**Comment by PIPIPIKa** [comment]
i guess maybe it doesn’t  support ubuntu so perfect as i followed every
step of its instructions.

matrixhome <notifications@github.com>于2019年6月12日 周三17:02写道：

**Comment by timqian** [comment]
`libxss1` seems not enough, try install all the following libs(works for me)
```bash
sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```

ref: https://github.com/GoogleChrome/puppeteer/issues/3443#issuecomment-433096772

**Comment by PIPIPIKa** [comment]
i’ll try later,thanks

Tim Qian <notifications@github.com>于2019年6月19日 周三08:57写道：

**Comment by TcTOrz** [comment]
> centos的用户可以安装这些依赖
> 
> 1.yum install libXScrnSaver*
> 
> 2.yum install epel-release
> 
> 3.yum install libappindicator-gtk3
> 
> 原文：https://blog.csdn.net/f1370335844/article/details/80460071



> centos的用户可以安装这些依赖
> 
> 1.yum install libXScrnSaver*
> 
> 2.yum install epel-release
> 
> 3.yum install libappindicator-gtk3
> 
> 原文：https://blog.csdn.net/f1370335844/article/details/80460071

It does't work.My linux version is CentOS Linux release 7.6.1810 (Core)

**Comment by Jasonlovesharon** [comment]
> > centos的用户可以安装这些依赖
> > 1.yum install libXScrnSaver*
> > 2.yum install epel-release
> > 3.yum install libappindicator-gtk3
> > 原文：https://blog.csdn.net/f1370335844/article/details/80460071
> 
> > centos的用户可以安装这些依赖
> > 1.yum install libXScrnSaver*
> > 2.yum install epel-release
> > 3.yum install libappindicator-gtk3
> > 原文：https://blog.csdn.net/f1370335844/article/details/80460071
> 
> It does't work.My linux version is CentOS Linux release 7.6.1810 (Core)

Have you resulved this problems now ? My linux is CentOS also,I tried to figure out this problems two days ,but noting can work!!!!

**Comment by onerou** [comment]
> > > centos的用户可以安装这些依赖项
> > > 1.yum安装libXScrnSaver * 
> > > 2.yum安装epel-release 
> > > 3.yum安装libappindicator-gtk3作家
> > > ：[https](https://blog.csdn.net/f1370335844/article/details/80460071) : //blog.csdn.net/f1370335844/article/details/80460071[](https://blog.csdn.net/f1370335844/article/details/80460071)
> > 
> > 
> > > centos的用户可以安装这些依赖项
> > > 1.yum安装libXScrnSaver * 
> > > 2.yum安装epel-release 
> > > 3.yum安装libappindicator-gtk3作家
> > > ：[https](https://blog.csdn.net/f1370335844/article/details/80460071) : //blog.csdn.net/f1370335844/article/details/80460071[](https://blog.csdn.net/f1370335844/article/details/80460071)
> > 
> > 
> > 它不起作用。我的Linux版本是CentOS Linux版本7.6.1810（核心）
> 
> 您现在解决了这个问题吗？我的Linux也是CentOS，我试图在两天之内解决这个问题，但注意可以正常工作！！！

Have you resulved this problems now ? My linux is CentOS also

**Comment by izjing** [comment]
Please try installing      
 `sudo yum install -y chromium`

**Comment by SFFI** [comment]
npm WARN config init.module Use `--init-module` instead.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /root/wechat/node_modules/sidecar
npm ERR! dest /root/wechat/node_modules/.sidecar-OE2fx7YE
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/root/wechat/node_modules/sidecar' -> '/root/wechat/node_modules/.sidecar-OE2fx7YE'

npm ERR! A complete log of this run can be found in:
npm ERR!     /www/server/nodejs/v16.9.0/cache/_logs/2022-09-12T10_08_49_610Z-debug-0.log

**Comment by 11477872997** [comment]
docker err
07:21:09 ERR PuppetWeChatBridge start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
2024-01-20 15:21:09 07:21:09 ERR PuppetWeChat initBridge() exception: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
2024-01-20 15:21:09 07:21:09 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
2024-01-20 15:21:09 07:21:09 ERR StarterBot Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).

**Comment by ku666** [comment]
> docker err 07:21:09 ERR PuppetWeChatBridge start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053). 2024-01-20 15:21:09 07:21:09 ERR PuppetWeChat initBridge() exception: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053). 2024-01-20 15:21:09 07:21:09 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page 2024-01-20 15:21:09 07:21:09 ERR StarterBot Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).

How did you solve it in the end?
