### ISSUE TITLE
Feat: add `Message.find` to search in cache.

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#1534]
For some scenarios like find the recent messages by text.

This might be a workaround for #1531

**Comment by zixia** [comment]
@kis87988 Would you like to try this new method to see if it could help you to find someone who had said something in a room before?

It had been published on Wechaty v0.19.145 or later versions.

**Comment by kis87988** [comment]
Sure, I will try and test it out.

**Comment by kis87988** [comment]
Did I use it right?
``` ts
        const room = bot.Room.load("chatroom@123456")
        room.say("match[2]")
        await delay(10000) //delay 10s
        const match=["這是一個測試的文字1","這是一個測試的文字1","這是一個測試的文字"]
        const find_content = match[2]
        console.log("find_content:", find_content)
        const found_msg = await bot.Message.find({text:new RegExp(find_content,"igm"),
                                                                               roomId:room.id, 
                                                                               type: Message.Type.Text})
        if(found_msg)
        {
          console.log(found_msg)
          console.log(found_msg.text())
          console.log(found_msg.from())
        }
        else
        {
          console.log(`not found message${content}`)
        }
```

```log
find_content: 没有没有
16:49:23 VERB Message findAll([object Object])
16:49:23 SILL Accessory #1333<Message> constructor()
16:49:23 VERB Message constructor([object Object]) for class Message
16:49:23 SILL Accessory #1334<Message> constructor()
16:49:23 VERB Message constructor([object Object]) for class Message
Message {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: { MsgId: 'id1' },
  [Symbol(name)]: 'Message',
  [Symbol(counter)]: 1333 }
16:49:23 ERR Config ###########################
16:49:23 ERR Config unhandledRejection: Error: no payload [object Promise]
16:49:23 ERR Config ###########################
16:49:23 ERR Config process.on(unhandledRejection) promise.catch(no payload)
Config Error: no payload
    at AnotherOriginalClass.text (/bot/node_modules/wechaty/src/user/message.ts:321:13)
    at Object.<anonymous> (/bot/WilliamDABot.ts:324:33)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/WilliamDABot.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
16:49:43 SILL PadchatRpc initHeartbeat() debounceQueue.subscribe(ws.on(message))
```

**Comment by zixia** [comment]
Why there's a data like ` id: { MsgId: 'id1' }`?

I do not think the `id1` is the real id from padchat, can you explain it?

**Comment by kis87988** [comment]
um.. 
Does that mean the message not found?
or my code is wrong:(

**Comment by zixia** [comment]
I have no idea about this problem, I will do a test by myself later.

**Comment by zixia** [comment]
I had just tested with the following code, it works without any problem with Wechaty v0.19.149

```ts
  if (msg.text() === 'find') {
    console.log('find start')
    const messageList = await this.Message.findAll({ text: /test/i })
    console.log('length:', messageList.length)
    for (const m of messageList) {
      console.log(m.from() + '')
      console.log(m.to() + '')
      console.log(m.room() + '')
      console.log(m.text() + '')
    }
    console.log('find done')
  }
```

**Comment by kis87988** [comment]
Yes, it is working now.  thanks!

**Comment by zixia** [comment]
Did you found the reason of why it didn't work before?

And please close this issue if you have no more questions. Thanks

**Comment by kis87988** [comment]
@zixia 
No, I put exactly same code. I guess it may be some version, connection, or cache issue.
And I can not close this one because ...I am not the issuer 😄

**Comment by zixia** [comment]
Ok, let me do this. :P

**Comment by xmsz** [comment]
您好，在onMessage中如何筛选聊天记录
使用Message.find({ text: "2" });会出现
```
WARN Message findAll() rejected: filterValue not found for filterKey: fromId
Error: filterValue not found for filterKey: fromId
```
