### ISSUE TITLE
memory-card cannot save successfully

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#1537]
### Version

wechaty version: 0.19.139
wechaty-puppet-padchat: 0.9.22

### Steps to reproduce the behavior (and fixes, if any)

Cannot relogin with memory card with the latest code

### Simple Log Output Logs

```
17:36:19 VERB MemoryCard <puppet> set(WECHATY_PUPPET_PADCHAT, [object Object])
17:36:19 VERB MemoryCard <default>puppet save() to N/A
17:36:19 VERB MemoryCard <default> save() to StorageFile</Users/jiaruili/git/rui/wechaty/default.memory-card.json>
17:36:19 VERB StorageFile save() to /Users/jiaruili/git/rui/wechaty/default.memory-card.json
17:36:19 VERB PuppetPadchatManager initCache(3456789087654345678987654345678, qq512436430)
TypeError: task.finally is not a function
    at FlashStoreSync.asyncBusyAdd (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:757:50)
    at new FlashStoreSync (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:709:18)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:139:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
    at <anonymous>
17:36:19 ERR Wechaty start() exception: task.finally is not a function
Bot error: TypeError: task.finally is not a function
    at FlashStoreSync.asyncBusyAdd (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:757:50)
    at new FlashStoreSync (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:709:18)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:139:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
    at <anonymous>
```

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:

WECHATY_LOG=silly WECHATY_PUPPET=padchat WECHATY_PUPPET_PADCHAT_TOKEN='3456789087654345678987654345678' ts-node examples/ding-dong-bot.ts 2>&1 | tee logroomfind
17:36:18 SILL Config WECHATY_LOG set level to silly
17:36:18 INFO Config registering process.on("unhandledRejection") for development/debug
17:36:18 VERB Config constructor()
17:36:18 SILL Accessory #0<Wechaty> constructor()
17:36:18 VERB Wechaty contructor()
17:36:18 VERB MemoryCard constructor({"name":"default"})
17:36:18 VERB MemoryCard getStorage() for storage type: N/A
17:36:18 VERB getStorage name: default, options: {"type":"file"}
17:36:18 VERB StorageFile constructor(default, ...)
17:36:18 VERB StorageBackend constructor(default, { type: file })
17:36:18 VERB StateSwitch constructor(name=Wechaty)
17:36:18 VERB StateSwitch constructor(name=WechatyReady)
17:36:18 VERB Wechaty on(logout, function) registered
17:36:18 VERB Wechaty onFunction(logout)
17:36:18 VERB Wechaty on(login, function) registered
17:36:18 VERB Wechaty onFunction(login)
17:36:18 VERB Wechaty on(scan, function) registered
17:36:18 VERB Wechaty onFunction(scan)
17:36:18 VERB Wechaty on(error, function) registered
17:36:18 VERB Wechaty onFunction(error)
17:36:18 VERB Wechaty on(message, function) registered
17:36:18 VERB Wechaty onFunction(message)
17:36:18 VERB Wechaty on(room-topic, function) registered
17:36:18 VERB Wechaty onFunction(room-topic)
17:36:18 INFO Wechaty <padchat> start() v#git[e648ce5] is starting...
17:36:18 VERB Wechaty puppet: undefined
17:36:18 VERB Wechaty profile: default
17:36:18 VERB Wechaty id: cjknsr2de0000vgwdhzjkhkx3
17:36:18 SILL StateSwitch <Wechaty> on() is false
17:36:18 SILL StateSwitch <WechatyReady> off() is true
17:36:18 VERB StateSwitch <WechatyReady> off(true) <- (true)
17:36:18 SILL StateSwitch <Wechaty> on() is false
17:36:18 VERB StateSwitch <Wechaty> on(pending) <- (false)
17:36:18 VERB MemoryCard load() from storage: StorageFile</Users/jiaruili/git/rui/wechaty/default.memory-card.json>
17:36:18 VERB StorageFile load() from /Users/jiaruili/git/rui/wechaty/default.memory-card.json

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/chatie/wechaty --------
          Version: 0.19.139

I'm a bot, my superpower is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me to more superpowers!

Please wait... I'm trying to login in...


17:36:18 VERB Wechaty initPuppet()
17:36:18 VERB MemoryCard multiplex(puppet)
17:36:18 VERB MemoryCard static multiplex(MemoryCard<default>, puppet)
17:36:18 VERB MemoryCard constructor({"name":"default","multiplex":{"name":"puppet","parent":{"options":{"name":"default"},"name":"default","payload":{"WECHATY_PUPPET_PADCHAT":{"device":{"qq512436430":{"data":"YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDY3M2ZlYzYwNDBmOTZlNGMyZDNmNDVmZTdiZTRkNGRhXxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw==","token":"NIIuVG7MWYFnfuj9g89O7zgmtM58jrQDpzNanaLVzYTdQiGk4QLImM6BuSbCnqAG8O8GFY/HW7OnuzqPnMH2Gb1mK1f3NORqgIRatEG2vbMJBjXpzYNP3oHg3Aa5BV4lVn+fqri25aw6fgpT3YWYAkE/FxFjAQ1wx/yzm9NdpkeRdbD6xvCqcod8elCklxi5SNHG+CSsPpA+IrnE40hdlCuRBpBoeTgCLk3AEQbGQmxRXh5/dv3AL79PcCUOWPby7wZo3WngtCCwmXMtquz6T6KRNrZJktpob1UHQ8Gd0NGKm7EpALVwOXrCdXLtu+Le+JTQZE8nzu6LvIbqEiucecFdrnAvhzUZC9bMhQbRyGe9w3zoCzMqnP2O8Wzbzasstn6JKBENv5OBWgdbSfitJ+hxGcq7jyfoRaHIUkDQxzBVXH9c3wVd0Fur1GlRF0cw+r84PLwQDKbr6nJFsmrg+bOTAHvsDINKchC+w4A+B3lQAmRBQstYx3AymbESEZbRIC/SgRXBu7nR3wZW15WdIGGj04h0hd1QWhCgeZiCA56k/Fx0RroXP2KE1OCKgVWYZM5qkUNYFBNdocXIAoyo+/VhYPQd3uWtM1OqRrfn6CLnAfmRcJ03lIwl8nUBeIfB"}},"currentUserId":"qq512436430"},"\rpadchat\nWECHATY_PUPPET_PADCHAT":{"device":{"qq512436430":{"data":"YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIGY1NTg5MDc3ZTUwNWY5MjY3NGU2Yzk1NDY0MTk5MzM2XxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw==","token":"yPvvEdRUkK6WLei0T06vP5VmQ5N9y8ZdN5/LQGDH9RNOr8JhIEGquNzfQ3hgQ0CWPl/dEtfK7QosuT5MnFK1pvHoC52IhC1xf2e5US4wUGkEPKlOjPiBGwgijN3uQZG80w1brQwkBzlEbCJe9I3XdhpCNjuH2hCXECFu8Sb4V8n6AYINdI0hLUtZSl9k+Ani7G0C24Pmiw1duWhbWs9o4v9UrDDp9xuqqYXBueYpaNBY8pJ7z/11LSs/GR4kJEv7B/C20eX/gwS09uF0GODjXlc9Hh0MEAllXL2ENtXd3JL+CbTsxzUR15WUEZtaTwQrimf0H6U4hSmTumgVgtO+1XfUCGbd23Ut1P5GFtSU5+RwfHSEK6n4EwQ3Xduu337a5JgUp8hpGGAhNfjdnF4MvyGfJaDedldbq7Cr5a3ZtTWTl7T0EiFr+/wN3c5QxaIDdSsI7YwNKtg1nOaqtxR1RtwWvndPPAcJdYQHUK/3bGXgjj+mj+GIz0BORd32ZsGwhEbAF3p8ggvsN7Uog6tTbeq516C+mJkj9bNK+FAdhKOgxznNZAtF0UCGxFCp1yB8LXEkfwmPkhu/27u/ryxZASCa1j8nnBxOEKqINohQq90aKeSbOauPQEDqYYwvA+QX"}},"currentUserId":"qq512436430"},"\rpuppet\nWECHATY_PUPPET_PADCHAT":{"device":{"qq512436430":{"data":"YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDVkYzE3YTY0MWQ3NTY0MmMyMzA5ZjM1MDY5MTQ0Y2Y2XxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw==","token":"+kLRS1fw/BEIiDITxNKuK4zByjJIbtcX+1OP6Xv/cZNqqldW8D9a1MRX2+mko5+tIXNeihfZijUUwuQ5LLLmhFNGURQh2cYiXR3UOi97Dpwta4WmXkvLVFLH+aRTVLsqMyzLZfDFPbc4pS99t+faK5wFGOkxx4705fy7OFklWmDl46DTAKM1rqUtPJeS+ZeQ85Y4cpOD2mYQcNStTHSVLFmBahocPFo/MD5pemCThsBE6jwFOI/NJ812+Q5L3kMPJEq8hedJOBCt3zofaAL5N4tLGTqQ3lcNcL9U2kWpAUqTygYJTea805PP/ueOfck9Hm58RROmu3esz7H3Ot86pL1EjUAQAwR7GLkzSijDqNFSOtc8+nu4RKClQvDXXhC4enZmpB4ywmw+0nQg0NQFg86+LIhk/sL56AStDK0hVxGNqXiIq2ldz5xN6fNFVKb9JNm9Wx1NboEpxqLWou8qAgxvKzpL59kNZw8amk8TKO4BdBW+5W2GibSDz5nwQVl4fFsUe4cB+X4UQl1uC7o2l7mSn63oLgHcA2OnYl6QPVINm0YRfF9dPVhIQOBeleWdtFZFOVbv+QexbSrBEmFwolaF4/Ilkn+TIxh17Bx4FQJe8IDaQbk8Csp7NuZ02TQz"}},"currentUserId":"qq512436430"}},"multiplexNameList":[],"storage":{"name":"default","options":{"type":"file"},"absFileName":"/Users/jiaruili/git/rui/wechaty/default.memory-card.json"}}}})
17:36:18 VERB PuppetManager resolve({wechaty: Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default), puppet: padchat, puppetOptions: undefined})
17:36:18 VERB PuppetManager resolveName(wechaty-puppet-padchat)
17:36:18 VERB PuppetManager checkModule(wechaty-puppet-padchat)
17:36:18 SILL PuppetManager checkModule() wechaty-puppet-padchat installed version 0.9.22 satisfied range ^0.9.12
17:36:18 SILL Config WECHATY_LOG set level to silly
17:36:18 VERB Puppet constructor({"timeout":240}) #0
17:36:18 VERB StateSwitch constructor(name=PuppetPadchat)
17:36:18 VERB MemoryCard constructor(undefined)
17:36:18 VERB MemoryCard getStorage() for storage type: N/A
17:36:18 VERB Puppet constructor() watchdog timeout set to 240 seconds
17:36:18 VERB HotImport callerResolve(., /Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js)
17:36:18 SILL HotImport callerResolve() callsites() file=/Users/jiaruili/git/rui/wechaty/node_modules/hot-import/dist/src/hot-import.js, type=Object
17:36:18 SILL HotImport callerResolve() callsites() file=/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
17:36:18 SILL HotImport callerResolve() callsites() file=/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js, type=null
17:36:18 SILL HotImport callerResolve() callerFile=/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js
17:36:18 VERB Puppet constructor() childClassPath=/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src
17:36:18 VERB Puppet setMemory()
17:36:18 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0)
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(login) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(logout) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(message) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(scan) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(dong) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(error) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(ready) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(reset) registered
17:36:18 VERB Wechaty initPuppetEventBridge() puppet.on(watchdog) registered
17:36:18 VERB Wechaty initAccessory(Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0)
17:36:18 SILL Accessory <Contact> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <ContactSelf> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <Friendship> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <Message> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <Room> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <RoomInvitation> static set wechaty = "Wechaty#cjknsr2de0000vgwdhzjkhkx3<>(default)"
17:36:18 SILL Accessory <Contact> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <ContactSelf> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <Friendship> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <Message> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <Room> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <RoomInvitation> static set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 SILL Accessory <Wechaty> set puppet = "Puppet#0<PuppetPadchat>(default)/PuppetPadchat#0"
17:36:18 VERB PuppetPadchat start() with default
17:36:18 SILL StateSwitch <PuppetPadchat> on() is false
17:36:18 SILL StateSwitch <PuppetPadchat> on() is false
17:36:18 VERB StateSwitch <PuppetPadchat> on(pending) <- (false)
17:36:18 VERB PadchatRpc constructor(ws://54.223.73.175:8788/wx, 3456789087654345678987654345678)
17:36:18 VERB PuppetPadchatManager constructor()
17:36:18 VERB PuppetPadchat startManager()
17:36:18 SILL StateSwitch <PuppetPadchat> off() is false
17:36:18 VERB PuppetPadchatManager start()
17:36:18 VERB PadchatRpc start()
17:36:18 VERB PadchatRpc initWebSocket()
17:36:19 SILL PadchatRpc initWebSocket() Promise() ws.on(open)
17:36:19 VERB PadchatRpc initJsonRpc()
17:36:19 VERB PadchatRpc startQueues()
17:36:19 VERB PadchatRpc initHeartbeat()
17:36:19 SILL PadchatRpc rpcCall(init, [])
17:36:19 SILL PadchatRpc pre login rpcCall(init, [])
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"init","data":"%7B%22message%22%3A%22%E5%88%9D%E5%A7%8B%E5%8C%96%E8%BF%9E%E6%8E%A5%E6%88%
17:36:19 SILL PadchatRpc init result: {"message":"初始化连接成功","status":0}
17:36:19 VERB PadchatRpc WXInitialize()
17:36:19 SILL PadchatRpc rpcCall(WXInitialize, [])
17:36:19 SILL PadchatRpc pre login rpcCall(WXInitialize, [])
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXInitialize","data":"%7B%22message%22%3A%22%E5%88%9D%E5%A7%8B%E5%8C%96%E5%BE%AE%E4%BF%A
17:36:19 SILL PadchatRpc WXInitialize result: {"message":"初始化微信信息成功","status":0}
17:36:19 VERB MemoryCard <puppet> get(WECHATY_PUPPET_PADCHAT)
17:36:19 VERB PuppetPadchatManager tryLoad62Data()
17:36:19 SILL PuppetPadchatManager tryLoad62Data() 62 data found: "YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDVkYzE3YTY0MWQ3NTY0MmMyMzA5ZjM1MDY5MTQ0Y2Y2XxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw=="
17:36:19 SILL PadchatRpc rpcCall(WXLoadWxDat, ["YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDVkYzE3YTY0MWQ3NTY0MmMyMzA5ZjM1MDY5MTQ0Y2Y2XxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQAAAAAAAAANAAAAAAAAAAAAAAAAAAAAfw=="])
17:36:19 SILL PadchatRpc pre login rpcCall(WXLoadWxDat, ["YnBsaXN0MDDUAQIDBAUGCQpYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKIHCFUkbnVsbF8QIDVkYzE3YTY0MWQ3NTY0MmMyMzA5ZjM1MDY5MTQ0Y2Y2XxAPTlNLZXllZEFyY2hpdmVy0QsMVHJvb3SAAQgRGiMtMjc6QGN1eH0AAAAAAAABAQ)
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXLoadWxDat","data":"%7B%22message%22%3A%22%22%2C%22status%22%3A0%7D%0A","msgId":"-90071
17:36:19 SILL PadchatRpc WXLoadWxDat result: {"message":"","status":0}
17:36:19 VERB PuppetPadchatManager tryAutoLogin(qq512436430)
17:36:19 SILL PadchatRpc rpcCall(WXAutoLogin, ["+kLRS1fw/BEIiDITxNKuK4zByjJIbtcX+1OP6Xv/cZNqqldW8D9a1MRX2+mko5+tIXNeihfZijUUwuQ5LLLmhFNGURQh2cYiXR3UOi97Dpwta4WmXkvLVFLH+aRTVLsqMyzLZfDFPbc4pS99t+faK5wFGOkxx4705fy7OFklWmDl46DTAKM1rqUtPJeS+ZeQ85Y4cpOD2mYQcNStTHSVLFmBahocPFo/MD5pemCThsBE6jwFOI/NJ812+Q5L3kMPJEq8hedJOBCt3zofaAL5N4tLGTqQ3lcNcL9U2kWpAUqTygYJTea805PP/ueOfck9Hm58RROmu3esz7H3Ot86pL1EjUAQAwR7GLkzSijDqNFSOtc8+nu4RKClQvDXXhC4enZmpB4ywmw+0nQg0NQFg86+LIhk/sL56AStDK0hVxGNqXiIq2ldz5xN6fNFVKb9JNm9Wx1NboEpxqLWou8qAgxvKzpL59kNZw8amk8TKO4BdBW+5W)
17:36:19 SILL PadchatRpc pre login rpcCall(WXAutoLogin, ["+kLRS1fw/BEIiDITxNKuK4zByjJIbtcX+1OP6Xv/cZNqqldW8D9a1MRX2+mko5+tIXNeihfZijUUwuQ5LLLmhFNGURQh2cYiXR3UOi97Dpwta4WmXkvLVFLH+aRTVLsqMyzLZfDFPbc4pS99t+faK5wFGOkxx4705fy7OFklWmDl46DTAKM1rqUtPJeS+ZeQ85Y4cp)
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXAutoLogin","data":"%7B%22email%22%3A%22%22%2C%22external%22%3A%220%22%2C%22long_link_s
17:36:19 SILL PadchatRpc WXAutoLogin result: {"email":"","external":"0","long_link_server":"","message":"\n\u0010Everything is ok","nick_name":"","phone_number":"","qq":0,"short_link_server":"","status":0,"uin":121141715,"user_name":"qq512436430"}, type: object
17:36:19 VERB PuppetPadchatManager login(qq512436430)
17:36:19 VERB PuppetPadchatManager stopCheckScan()
17:36:19 VERB PuppetPadchatManager refresh62Data(qq512436430, undefined)
17:36:19 SILL PadchatRpc rpcCall(WXHeartBeat, [])
17:36:19 SILL PadchatRpc pre login rpcCall(WXHeartBeat, [])
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXHeartBeat","data":"%7B%22status%22%3A0%2C%22message%22%3A%22ok%22%7D","msgId":"-900719
17:36:19 SILL PadchatRpc WXHeartBeat result: {"status":0,"message":"ok"}
17:36:19 SILL PuppetPadchatManager refresh62Data() userId did not change since last login, keep the data as the same
17:36:19 SILL PadchatRpc rpcCall(WXGetLoginToken, [])
17:36:19 SILL PadchatRpc pre login rpcCall(WXGetLoginToken, [])
17:36:19 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXGetLoginToken","data":"%7B%22message%22%3A%22%22%2C%22status%22%3A0%2C%22token%22%3A%2
17:36:19 SILL PadchatRpc WXGetLoginToken result: {"message":"","status":0,"token":"CyTQMTsHoyMNKBJCWNJAw1Um38hHGkuN9g8U0izQiXHT709HPi5Bt44l5+nlY35FKptTZliYdkb+rKAvcS1+hN8DkLUT2qtng+bsr63Yq/iWlMwJK5PIh/qwRVHOQMYphGCGNIm/YpUyhjeIwM7dlaEOAlKr/wbnvrSuv3Er1it2EHuJY8xy4Trx7cYhbPbx9EHKrThMmfhT2gbqXWytOMSb6CRI8ObzBzuo/4iZRIXlhGXqwolD2OypgjpipN/9K0PXlMipimCPK49fx+W6fB0JwDyAPB3N7VEx404Fkp5IlrkWJbUcCUeodN+YtTlYdS/HzZT39szo5ZNBFp0p5KvA8qgg1CfxKs9VbgzxQl525f3o1WbP+uncU70f6LoOzdzinlzpiXb0W5M33614cXS/R1UpiR/0mEFB7k99VyKriqLH9ze68yxjAyigqpCWuSSDi8jkcnpJDNt+eW6+wc8AxhD4NBtofssyhy3rlCNaMAxtOnHtac9SJS30eam0Ba5tFa2AjkE5cK3j/L6CmfXvULUExFGu4/JWN0B4xkDb5nqMjllsXwbmHuMA9rAVvBPeRt50Ju5os/OsfVvPJCky87UVfiiiRmouodTySVPNexoOVXt6EEPTy52ycZLx","uin":121141715}
17:36:19 VERB MemoryCard <puppet> set(WECHATY_PUPPET_PADCHAT, [object Object])
17:36:19 VERB MemoryCard <default>puppet save() to N/A
17:36:19 VERB MemoryCard <default> save() to StorageFile</Users/jiaruili/git/rui/wechaty/default.memory-card.json>
17:36:19 VERB StorageFile save() to /Users/jiaruili/git/rui/wechaty/default.memory-card.json
17:36:19 VERB PuppetPadchatManager initCache(3456789087654345678987654345678, qq512436430)
TypeError: task.finally is not a function
    at FlashStoreSync.asyncBusyAdd (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:757:50)
    at new FlashStoreSync (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:709:18)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:139:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
    at <anonymous>
17:36:19 ERR Wechaty start() exception: task.finally is not a function
Bot error: TypeError: task.finally is not a function
    at FlashStoreSync.asyncBusyAdd (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:757:50)
    at new FlashStoreSync (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:709:18)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:139:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
    at <anonymous>
17:36:19 INFO Wechaty <padchat> stop() v#git[e648ce5] is stoping ...
17:36:19 SILL StateSwitch <Wechaty> off() is false
17:36:19 SILL StateSwitch <WechatyReady> off() is true
17:36:19 VERB StateSwitch <WechatyReady> off(true) <- (true)
17:36:19 SILL StateSwitch <Wechaty> off() is false
17:36:19 VERB StateSwitch <Wechaty> off(pending) <- (false)
17:36:19 VERB MemoryCard <default> save() to StorageFile</Users/jiaruili/git/rui/wechaty/default.memory-card.json>
17:36:19 VERB StorageFile save() to /Users/jiaruili/git/rui/wechaty/default.memory-card.json
17:36:19 VERB PuppetPadchat stop()
17:36:19 SILL StateSwitch <PuppetPadchat> off() is false
17:36:19 SILL StateSwitch <PuppetPadchat> off() is false
17:36:19 VERB StateSwitch <PuppetPadchat> off(pending) <- (false)
17:36:19 VERB PuppetPadchat logout()
17:36:19 WARN PuppetPadchat logout() this.id not exist
17:36:19 VERB PuppetPadchatManager stop()
17:36:19 VERB PuppetPadchatManager stopCheckScan()
17:36:19 VERB PadchatRpc stop()
17:36:19 VERB PadchatRpc stopQueues()
17:36:19 VERB PuppetPadchatManager releaseCache()
17:36:19 VERB PuppetPadchatManager releaseCache() cache not exist.
17:36:19 SILL StateSwitch <PuppetPadchat> off() is pending
17:36:19 VERB StateSwitch <PuppetPadchat> off(true) <- (pending)
17:36:19 SILL StateSwitch <Wechaty> off() is pending
17:36:19 VERB StateSwitch <Wechaty> off(true) <- (pending)
```
</details>

**Comment by lijiarui** [comment]
When I get the delete the memory-card and restart, get the following error

```
18:04:31 VERB MemoryCard <puppet> set(WECHATY_PUPPET_PADCHAT, [object Object])
18:04:31 VERB MemoryCard <lijiarui>puppet save() to N/A
18:04:31 VERB MemoryCard <lijiarui> save() to StorageFile</Users/jiaruili/git/rui/wechaty/lijiarui.memory-card.json>
18:04:31 VERB StorageFile save() to /Users/jiaruili/git/rui/wechaty/lijiarui.memory-card.json
18:04:31 VERB PuppetPadchatManager initCache(3456789087654345678987654345678, qq512436430)
18:04:31 ERR Config ###########################
18:04:31 ERR Config unhandledRejection: TypeError: task.finally is not a function [object Promise]
18:04:31 ERR Config ###########################
18:04:31 ERR Config process.on(unhandledRejection) promise.catch(task.finally is not a function)
Config TypeError: task.finally is not a function
    at FlashStoreSync.asyncBusyAdd (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:757:50)
    at new FlashStoreSync (/Users/jiaruili/git/rui/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:709:18)
    at PadchatManager.<anonymous> (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:139:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/rui/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
    at <anonymous>
(node:77279) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
18:04:38 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"","data":"%5B%7B%22continue%22%3A1%2C%22msg_type%22%3A2048%2C%22status%22%3A1%2C%22uin%2
```

**Comment by zixia** [comment]
You have to use Node.js v10 or above.
