### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined     at AnotherOriginalClass.type 

### ISSUE THREAD

**Issue by TbhT** [Chatie/wechaty#1545]
`
TypeError: Cannot read property 'type' of undefined
    at AnotherOriginalClass.type (*******\node_modules\_wechaty@0.18.5@wechaty\dist\src\user\contact.js:384:29)
`

the example [from-here](https://github.com/Chatie/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/contact-bot.ts) .

when i use `contact.type()`, it happens. so i have to use `personal()` or `official()` instead.

**Comment by zixia** [comment]
Because you did neither provide any version information and detailed log messages, nor any reproduce steps, so I'm afraid that I can not be able to find the reason for this `TypeError`.

However, if you can use `personal()` and `official()` without the problem, please use them as a wrokaround.

If you still want to use `contact.type()`, please clone the getting-started project from <https://github.com/Chatie/wechaty-getting-started> and use it to provide the reproduce steps with the detailed log messages.

Have a nice day.

**Comment by TbhT** [comment]
my `wechaty` version is `0.18.5`, but the `wechaty-getting-started` version is `0.19.153`.

`
>>>>>>>>>>>>>>>>>>> Error: no payload
    at AnotherOriginalClass.type (D:\wechaty-getting-started\node_modules\_wechaty@0.19.153@wechaty\dist\src\user\contact.js:448:19)
    at main (D:\wechaty-getting-started\examples\basic\contact-bot.js:65:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`


well , i use the `cnpm` to run this project , maybe it has no influence for the project .  

the error is stil.

**Comment by zixia** [comment]
Confirmed this is a bug related with `Contact.findAll()` and `Room.findAll()`, they did not prepare the data in a proper manner.

**Comment by TbhT** [comment]
does it occurs all versions or `0.18`  or higher?

**Comment by zixia** [comment]
I'm not sure when this bug had been introduced in, but it should be fixed in v0.19.154.

Please try again by check out the latest code from the wechaty-getting-started repo.

**Comment by TbhT** [comment]
well ,  when i run the `node examples\advanced\room-bot.js` ,  the global event `room-join, room-leave, room-topic`, errors happens.  

it is in the project [https://github.com/Chatie/wechaty-getting-started](https://github.com/Chatie/wechaty-getting-started).
