### ISSUE TITLE
friendship send msg failed .

### ISSUE THREAD

**Issue by TbhT** [Chatie/wechaty#1548]
```javascript
11:01:13 ERR PuppetPuppeteerBridge send() exception: send fail
11:01:13 ERR PuppetPuppeteer messageSendText() exception: send fail
(node:5040) UnhandledPromiseRejectionWarning: Error: send fail
    at Bridge.<anonymous> (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:429:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:23:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
11:01:13 ERR PuppetPuppeteerBridge send() exception: send fail
11:01:13 ERR PuppetPuppeteer messageSendText() exception: send fail
(node:5040) UnhandledPromiseRejectionWarning: Error: send fail
    at Bridge.<anonymous> (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:429:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\wechaty-getting-started\node_modules\_wechaty@0.19.154@wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:23:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by zixia** [comment]
```diff
await friendship.accept()
+ await new Promise(r => setTimeout(r, 10 * 1000))
```

Can you try again with the above code modification? (wait another 10 seconds)

There might need some time before the server updates your new friend and make it valid to be sent message.

**Comment by TbhT** [comment]
oh , right !  does the framework can do this job for devlopers?

**Comment by zixia** [comment]
Did that modifications resolve your problem?

If you can confirm this fix, maybe we can consider doing this kind of jobs in the framework for developers in the future.

**Comment by TbhT** [comment]
yeah, it works now.  hope paticipate in the project later to make it better for developers.

**Comment by zixia** [comment]
Glad to hear that, cheers.

**Comment by zixia** [comment]
Would you like to send a pull request to add this workaround to our friendship example?

It will be much valuable for others who try our examples.

**Comment by zixia** [comment]
Thank you very much for the PR! 

It was merged.

Could you please add my wechat 918999? I'd like to invite you to the contributor list.
