### ISSUE TITLE
something was wrong when i use the method  --room.add()

### ISSUE THREAD

**Issue by zilongliang** [Chatie/wechaty#1554]
```
09:48:32 WARN PadchatRpc WXAddChatRoomMember() status = 0 but message is not OK: 
MemberList are wrong
(node:34) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'big_head' of undefined
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1081:30)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:21:12)
    at PuppetPadchat.roomMemberRawPayloadParser (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:824:16)
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet/src/puppet.ts:1073:35)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by kis87988** [comment]
FYI: This may refer to wechaty-puppet-padchat issue: https://github.com/lijiarui/wechaty-puppet-padchat/issues/113

**Comment by zixia** [comment]
@kis87988 Thanks for point this out!

Merge this issue to https://github.com/lijiarui/wechaty-puppet-padchat/issues/113
