### ISSUE TITLE
ubuntu 18.04下无法正常启动chrome

### ISSUE THREAD

**Issue by zhuangbiaowei** [Chatie/wechaty#1637]
ubuntu 18.04，已经安装过google chrome最新版（70.0.xx），采用的是wechaty最新代码（Nov 2, 2018最新提交的master分支）

在执行npm start是，报错：

21:43:37 ERR PuppetPuppeteerBridge start() exception: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Bot error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at PuppetPuppeteer.puppet.on.error (/home/zbw/wechaty/src/wechaty.ts:602:32)
    at PuppetPuppeteer.emit (events.js:182:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:442:20)
    at PuppetPuppeteer.emit (/home/zbw/wechaty/node_modules/wechaty-puppet/src/puppet.ts:298:18)
    at Bridge.bridge.on.e (/home/zbw/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:296:43)
    at Bridge.emit (events.js:182:13)
    at Bridge.EventEmitter.emit (domain.js:442:20)
    at Bridge.<anonymous> (/home/zbw/wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:114:12)
    at Generator.throw (<anonymous>)
    at rejected (/home/zbw/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:24:65)

**Comment by mxue12138** [comment]
这个应该是Chrome未下载，你可以手动下载或者修改为国内地址或者把Ubuntu翻墙，然后就可以正常下载了

**Comment by mxue12138** [comment]
https://github.com/Chatie/wechaty-puppet-puppeteer#note-for-developers-in-china，参考这个链接

**Comment by zhuangbiaowei** [comment]
谢谢

**Comment by klren0312** [comment]
> 这个应该是Chrome未下载，你可以手动下载或者修改为国内地址或者把Ubuntu翻墙，然后就可以正常下载了

请问手动下载的 放到哪个目录...
