### ISSUE TITLE
electron中调试模式下可以正常启动，打包后无法使用

### ISSUE THREAD

**Issue by travelk** [Chatie/wechaty#1694]
wechaty: 0.22.6
electron: 4.0.1
node: 10.11.0
打包运行后，报错信息如下：
```
 16:09:58 INFO Wechaty <default> start() v0.22.6 is starting...
16:10:00 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

16:10:00 ERR PuppetPuppeteer initBridge() exception: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

16:10:00 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
16:10:00 ERR PuppetPuppeteer start() exception: Error: Error: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:182:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:442:20)
    at PuppetPuppeteer.emit (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty-puppet\dist\src\puppet.js:171:22)
    at PuppetPuppeteer.<anonymous> (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:23:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
16:10:00 ERR Wechaty start() exception: Error: Error: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:13076) UnhandledPromiseRejectionWarning: Error: Error: Error: Error: Failed to launch chrome! spawn E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-609904\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.puppet.on.error (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:182:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:442:20)
    at PuppetPuppeteer.emit (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty-puppet\dist\src\puppet.js:171:22)
    at PuppetPuppeteer.<anonymous> (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (E:\project\build\win-unpacked\resources\app.asar\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:23:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by huan** [comment]
Could you please provide a minimum repository so that I could reproduce it and look into it for you?

I could not help you without any reproduce-able code.

**Comment by travelk** [comment]
我发现electron-builder打包的时候不启用asar就可以正常启动
官网的说明 [Node API 的局限性](https://electronjs.org/docs/tutorial/application-packaging#node-api-%E7%9A%84%E5%B1%80%E9%99%90%E6%80%A7)
我想应该和这有关系
