### ISSUE TITLE
这是什么

### ISSUE THREAD

**Issue by zaoqi-unsafe** [Chatie/wechaty#1703]
npm:
> puppeteer@1.11.0 install C:\Users\zaoqi\node_modules\wechaty\node_modules\puppeteer
> node install.js

**Comment by zaoqi-unsafe** [comment]
v0.22.6 is starting...
16:53:29 ERR PuppetPuppeteerBridge start() exception: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
16:53:29 ERR PuppetPuppeteer initBridge() exception: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
16:53:29 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
16:53:29 ERR PuppetPuppeteer start() exception: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Error: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at PuppetPuppeteer.puppet.on.error (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:189:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:441:20)
    at PuppetPuppeteer.emit (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet\dist\src\puppet.js:171:22)
    at PuppetPuppeteer.<anonymous> (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:23:65)
16:53:29 ERR Wechaty start() exception: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
Error: Error: Error: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at PuppetPuppeteer.puppet.on.error (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:189:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:441:20)
    at PuppetPuppeteer.emit (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet\dist\src\puppet.js:171:22)
    at PuppetPuppeteer.<anonymous> (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\zaoqi\bot\wechaty-getting-started-master\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:23:65)

**Comment by lijiarui** [comment]
Please follow the issue template, or we could not help you since there isn't enough information. 

I will close this issue and feel free to open a new one with issue template, thanks!
