### ISSUE TITLE
WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???

### ISSUE THREAD

**Issue by hoo-ge** [Chatie/wechaty#1715]
## 1. Versions
- What is your wechaty version?
Answer: 0.23.40

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: puppeteer

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: puppeteer

- What is your node version? (run `node --version`)
Answer: 11.0

- What os are you using
Answer: macOS

## 2. Describe the bug
rename room topic error.

# 6. Full Output Logs
`
12:26:20 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:21 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:22 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:23 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:24 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:25 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:26 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:27 ERR PuppetPuppeteer roomRawPayload(@694880f1ead94b706a28cff484f6d7704915d073a311a098232a5) exception: no payload
(node:82896) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (/Users/tii/Projects/bot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:603:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tii/Projects/bot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:58)
(node:82896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

## 7. Additional context
Thanks !

[bug]

**Comment by lijiarui** [comment]
We need the reproduce code: a minimum code can run directly and reproduce your bug.

**Comment by hoo-ge** [comment]
Thank you very much for your reply.

My steps are as follows:
1. git clone https://github.com/wechaty/wechaty-getting-started.git
2. npm install
3. npm start
4. scan qrcode
5. in wechat (macOS) rename room name
6. Program prompt error
```
12:26:20 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:21 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:22 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:23 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:24 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:25 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:26 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
12:26:27 ERR PuppetPuppeteer roomRawPayload(@694880f1ead94b706a28cff484f6d7704915d073a311a098232a5) exception: no payload
(node:82896) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (/Users/tii/Projects/bot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:603:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tii/Projects/bot/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:58)
(node:82896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**This process does not make any modifications to the program**
