### ISSUE TITLE
一扫码登录就会报错

### ISSUE THREAD

**Issue by Curtains415** [Chatie/wechaty#2765]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (G:\test\wechat-bot\test-wechat\node_modules\wechat4u\lib\util\global.js:69:24)
    at G:\test\wechat-bot\test-wechat\node_modules\wechat4u\lib\core.js:229:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (G:\\test\\wechat-bot\\test-wechat\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at G:\\test\\wechat-bot\\test-wechat\\node_modules\\wechat4u\\lib\\core.js:229:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

To handle uncaught exceptions from the wechat4u library, we could add a try-catch block around the puppet initialization in the PuppetMixin. This would allow us to catch and properly handle any errors thrown during the puppet startup process.

You can review changes in this commit: https://github.com/wwqwq2313/wechaty-wechaty-2765/commit/da33c51fdcc0c04ba054dae5b4cf3e4f293a75c6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
