### ISSUE TITLE
error on room join: TypeError: room.topic is not a function

### ISSUE THREAD

**Issue by dcsan** [Chatie/wechaty#383]
crash when a user is invited to a room

I guess this is a system message being received which doesn't have the `room.topic()`
also it could be because I changed our code to also respond to self messages.

https://github.com/Chatie/wechaty/blob/master/example/room-bot.ts#L109-L116

```
  .on('room-join', function (self, room, inviteeList, inviter) {
    let roomName = room.topic();
    log.info('Bot', 'EVENT: room-join - Room %s got new member %s, invited by %s'
      , roomName
      , inviteeList.map(c => c.name()).join(',')
      , inviter.name()
    );
```

```
08:52:37 INFO Bot "Juan Caliz 胡安" invited "Li  Lei" to the group chat
08:52:37 INFO Bot isNew: true
08:52:37 INFO Bot botMsg { sender: 'user',
  room: 'CDCmovieClub: GITS',
  text: '"Juan Caliz 胡安" invited "Li  Lei" to the group chat' }
08:53:35 WARN PuppetWebFirer fireRoomJoin() reject() inviteeContactList: , inviterContact: Juan Caliz 胡安
08:53:35 ERR PuppetWebFirer exception: TypeError: room.topic is not a function
    at Wechaty.<anonymous> (/bot/Kbot.js:59:25)
    at emitThree (events.js:116:13)
    at Wechaty.emit (events.js:197:7)
    at PuppetWeb.puppet.on.args (/wechaty/dist/src/wechaty.js:235:31)
    at emitThree (events.js:116:13)
    at PuppetWeb.emit (events.js:197:7)
    at PuppetWeb.<anonymous> (/wechaty/dist/src/puppet-web/firer.js:232:18)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/firer.js:20:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by lijiarui** [comment]
could you add `console.log(room)` before `let roomName = room.topic()` to see whether you got the room?

**Comment by dcsan** [comment]
could this be maybe room is not ready yet when `room.topic()` is called?

**Comment by lijiarui** [comment]
I'm not sure, only log can talk ^-^

**Comment by dcsan** [comment]
can't repro it for now... >.<
