### ISSUE TITLE
should add`phantomjs-prebuilt` in package.json

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#385]
when I run unit test to test the code in a new environment, it occurs the following error:

``` shell
➜  wechaty git:(functionMember) ✗ npm run nycava

> wechaty@0.7.55 nycava /Users/lijiarui/git/rui/wechaty
> WECHATY_HEAD=chrome nyc ava --serial --fail-fast --verbose --timeout=3m "dist/{src,test}/**/*.spec.js"


Error: Cannot find module 'phantomjs-prebuilt'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lijiarui/git/rui/wechaty/dist/test/webdriver-phantomjs.spec.js:7:345)
    at Module._compile (module.js:573:32)
    at Module.replacementCompile (/Users/lijiarui/git/rui/wechaty/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/Users/lijiarui/git/rui/wechaty/node_modules/require-precompiled/index.js:13:11)
    at /Users/lijiarui/git/rui/wechaty/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/lijiarui/git/rui/wechaty/node_modules/ava/lib/process-adapter.js:105:4)
    at Object.<anonymous> (/Users/lijiarui/git/rui/wechaty/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```

maybe it should add to package.json by default

after I installed `phantomjs-prebuilt` and do as [Test](https://github.com/Chatie/wechaty/wiki/Test#mac) which I have tried successfully before,
it occurs the following error:
```
    at process._tickCallback (internal/process/next_tick.js:103:7)
  ✖ src › puppet-web › browser › quit() Error: initChromeDriver() got invalid driver
Unhandled Rejection: dist/src/puppet-web/browser.spec.js
  Error: Server terminated early with status 1
    earlyTermination.catch.e (node_modules/selenium-webdriver/remote/index.js:252:52)

Unhandled Rejection: dist/src/puppet-web/browser.spec.js
  Error: Server terminated early with status 1
    earlyTermination.catch.e (node_modules/selenium-webdriver/remote/index.js:252:52)

Unhandled Rejection: dist/src/puppet-web/browser.spec.js
  Error: Server terminated early with status 1
    earlyTermination.catch.e (node_modules/selenium-webdriver/remote/index.js:252:52)

Unhandled Rejection: dist/src/puppet-web/browser.spec.js
  Error: Server terminated early with status 1
    earlyTermination.catch.e (node_modules/selenium-webdriver/remote/index.js:252:52)
```

**Comment by zixia** [comment]
### Short answer: 

No, we need not do that before we fix the phantomjs issue.

### Long answer:

PhantomJS did not work after for serval months.

It only can pass unit tests, but `wechaty-bro.js` does not work inside phantomjs anymore, which should be debugged & fix in the future.

So I believe it's not necessary to install it and waste disk space for the user before it be fixed.
