### ISSUE TITLE
Failed due to EAI_AGAIN registry.yarnpkg.com:443

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#408]
Not sure if it's just me or everyone, but I am having this error.

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
```
# I can't get the run doctor to work either. Not sure if it's related - (xinbenlv@)
npm run doctor

> wechaty@0.7.61 doctor /Users/zzn/Documents/ws/wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.7.61 check-node-version /Users/zzn/Documents/ws/wechaty
> check-node-version --node ">= 6.9"

node: 6.9.1
npm: 3.10.8
yarn: 0.19.1

/usr/local/lib/node_modules/ts-node/src/index.ts:286
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
bin/doctor.ts (10,21): Cannot find module 'os'. (2307)
bin/doctor.ts (39,22): Cannot find name 'process'. (2304)
bin/doctor.ts: Emit skipped
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:286:17)
    at /usr/local/lib/node_modules/ts-node/src/index.ts:312:18
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:462:17)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:369:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:372:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
```
### Expected behavior

Ding-Dong Bot runs

### Actual behavior
Ding-Dong Bot failed to run due to error 
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fselenium-webdriver: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".
```

### Steps to reproduce the behavior (and fixes, if any)

```
git clone https://github.com/Chatie/wechaty.git
cd wechaty
docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty example/ding-dong-bot.ts
```

Current git commit id
``` 
commit b699dbf5c286037c0cd05e6f15ca4edd28d63f26
Author: Huan LI <zixia@zixia.net>
Date:   Sun Apr 9 07:34:44 2017 +0800

0.7.61
```
### Paste the full output logs here with `WECHATY_LOG=silly` set

```
 $ ▶docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty example/ding-dong-bot.ts 

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  ____                            _   _
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _
 / ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/


Starting Wechaty ... v0.7.20

Working directory: /bot
Install dependencies modules ...
yarn install v0.19.1
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fselenium-webdriver: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/bot/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
^[[I^[[O^[[I
 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  _____      _ _     _
 | ____|_  _(_) |_  / |
 |  _| \ \/ / | __| | |
 | |___ >  <| | |_  | |
 |_____/_/\_\_|\__| |_|
```

**Comment by zixia** [comment]
Your docker image seems is very outdated: `v0.7.20`, which the latest should be `v0.7.61`

Please try the latest by run:
```shell
docker pull zixia/wechaty
```

**Comment by xinbenlv** [comment]
Actually, it turns out the solution is to re-install yarn by 
```
brew unlink yarn
brew install yarn
```

**Comment by zixia** [comment]
Great to hear that!

**Comment by gamusta** [comment]
I had same error with jquery
It was due to vpn network enabled
