### ISSUE TITLE
ding-dong-bot-ts cannot run normally on Mac

### ISSUE THREAD

**Issue by amyhuangxbd** [Chatie/wechaty#410]
### Actual behavior
Executing ts-node ding-dong-bot.ts

/wechaty/node_modules/ts-node/src/index.ts:312
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
ding-dong-bot.ts (76,13): Argument of type 'MediaMessage' is not assignable to parameter of type 'string'. (2345)
    at getOutput (/wechaty/node_modules/ts-node/src/index.ts:312:15)
    at /wechaty/node_modules/ts-node/src/index.ts:343:16
    at Object.compile (/wechaty/node_modules/ts-node/src/index.ts:485:17)
    at Module.m._compile (/wechaty/node_modules/ts-node/src/index.ts:395:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/wechaty/node_modules/ts-node/src/index.ts:398:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)

### Steps to reproduce the behavior (and fixes, if any)
1.  run docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty ding-dong-bot.ts on Mac terminal
2. Then you will see the error message: ding-dong-bot.ts (76,13): Argument of type 'MediaMessage' is not assignable to parameter of type 'string'. (2345)
![Uploading image.png…]()

**Comment by lijiarui** [comment]
maybe your docker is outdated, please 
## Run npm run doctor or wechaty run doctor(for docker user), paste output here

**Comment by zixia** [comment]
Update your docker by `docker pull zixia/wechaty` to update to the latest version might be help.

Will close this issue unless there's more information provided.

**Comment by amyhuangxbd** [comment]
Thanks for your help, The ding-dong-bot.ts can run normally after updating to the latest wechaty version by `docker pull zixia/wechaty`

**Comment by zixia** [comment]
Great to hear that. Have a nice day!
