### ISSUE TITLE
can't run the example

### ISSUE THREAD

**Issue by shuhankuang** [Chatie/wechaty#423]
Ubuntu 14.04.5 LTS \n \l

node -v 
v6.10.2

npm -v
4.5.0

ChromeDriver 2.22

```
16:44:14 INFO Wechaty v0.7.64 initializing...
16:44:21 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
16:44:21 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
16:44:21 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:44:21 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
16:44:28 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
16:44:28 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
16:44:28 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:44:28 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
```

```
npm run docker
```

```
> wechaty@0.7.66 doctor /var/www/oschina/wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.7.66 check-node-version /var/www/oschina/wechaty
> check-node-version --node ">= 6.9"

node: 6.10.2
npm: 4.5.0
yarn: 0.22.0

  #### Wechaty Doctor

  1. Wechaty version: #git[8f8f119 Limit video file size (#421)]
  2. Linux x64 version 3.13.0-116-generic memory 64/992 MB
  3. Docker: false
  4. Node version: v6.10.2
  5. Tcp IPC TEST: PASS
  6. Chromedriver: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /var/www/oschina/wechaty/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

**Comment by shuhankuang** [comment]
npm run demo
```
> wechaty@0.7.66 demo /var/www/oschina/wechaty
> ts-node example/ding-dong-bot.ts


| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


17:04:21 INFO Wechaty v#git[8f8f119 Limit video file size (#421)] initializing...
17:04:22 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
17:04:22 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/var/www/oschina/wechaty/src/puppet-web/browser-driver.ts:138:21)
    at next (native)
    at fulfilled (/var/www/oschina/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
17:04:22 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
17:04:22 ERR PuppetWebBrowser quit() this.driver.quit() exception Server terminated early with status 1
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Server terminated early with status 1
17:04:22 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
17:04:22 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/var/www/oschina/wechaty/src/puppet-web/browser-driver.ts:138:21)
    at next (native)
    at fulfilled (/var/www/oschina/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
17:04:22 INFO Bot error: Error: initChromeDriver() got invalid driver
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: can not say before login
(node:12675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'quit' of undefined
17:04:29 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
17:04:29 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
17:04:29 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
17:04:29 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
```

**Comment by zixia** [comment]
Thank you for following the template.

Could you please post the output of the following command to have a look on your chromedriver?

```shell
tree /var/www/oschina/wechaty/node_modules/chromedriver/
```

**Comment by shuhankuang** [comment]
```
/var/www/oschina/wechaty/node_modules/chromedriver/
├── appveyor.yml
├── bin
│   └── chromedriver
├── Dockerfile
├── install.js
├── lib
│   └── chromedriver.js
├── package.json
├── README.md
├── test-driver.sh
└── testInstall.js

2 directories, 9 files
```

**Comment by zixia** [comment]
The problem is: your `test-driver.sh` want to find chromedriver inside a non-exist directory `/var/www/oschina/wechaty/node_modules/chromedriver/lib/chromedriver/chromedriver`.

However, you can run `chromedriver -v` in your shell, so it's very strange.

I suggest you run `which chromedriver` to see which directory your chromedriver is installed, then create the above non-exist directory to put a chromedriver inside it to test.

It's more likely belongs your environment problem.

**Comment by lijiarui** [comment]
@shuhankuang I guess you download from the official page and extract it.

if so, could you try `sudo chmod +x chromedriver`

**Comment by lijiarui** [comment]
I get the same problem when using npm to run wechaty on a new debian server too.

### Reproduce:
create a new debian server on digital ocean:
``` sh
aptitude install sudo
sudo apt-get install software-properties-common

curl https://raw.githubusercontent.com/creationix/nvm/v0.11.1/install.sh | bash
nvm install 7
nvm alias default 7

sudo apt-get update
sudo apt-get install git-core

npm install -g ts-node
npm install -g typescript

git clone https://github.com/Chatie/wechaty.git
cd wechaty 
npm install
ts-node example/ding-dong-bot.ts
```

when I run wechaty, the following log shows it
 cannot find chromedriver (I use digital ocean server, so no need to concern about the wall... )

``` ts

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


14:25:22 INFO Wechaty v#git[8f8f119 Limit video file size (#421)] initializing...
14:25:23 ERR PuppetWebBrowserDriver initChromeDriver() Wechaty require `chromedriver` to be installed.(try to run: "npm install chromedriver" to fix this issue)
14:25:23 ERR PuppetWebBrowser init() exception: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
14:25:23 WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
14:25:23 WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
14:25:23 ERR PuppetWeb initBrowser() exception: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
14:25:23 ERR PuppetWeb init() exception: Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
    at ServiceBuilder (/root/wechaty/node_modules/selenium-webdriver/chrome.js:191:13)
    at getDefaultService (/root/wechaty/node_modules/selenium-webdriver/chrome.js:280:22)
    at Function.createSession (/root/wechaty/node_modules/selenium-webdriver/chrome.js:700:44)
    at createDriver (/root/wechaty/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/root/wechaty/node_modules/selenium-webdriver/index.js:639:16)
    at BrowserDriver.<anonymous> (/root/wechaty/src/puppet-web/browser-driver.ts:130:24)
    at Generator.next (<anonymous>)
    at /root/wechaty/src/puppet-web/browser-driver.ts:7:71
    at __awaiter (/root/wechaty/src/puppet-web/browser-driver.ts:3:12)
    at BrowserDriver.initChromeDriver (/root/wechaty/src/puppet-web/browser-driver.ts:53:16)
14:25:23 INFO Bot error: Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
(node:2887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: can not say before login
(node:2887) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'quit' of undefined
```
I tree chromedriver as follows
```
root@test-chromedriver:~/wechaty/node_modules/chromedriver# tree
.
├── appveyor.yml
├── bin
│   └── chromedriver
├── chromedriver
│   ├── chromedriver
│   └── chromedriver_linux64.zip
├── Dockerfile
├── install.js
├── lib
│   ├── chromedriver
│   │   ├── chromedriver
│   │   └── chromedriver_linux64.zip
│   └── chromedriver.js
├── package.json
├── README.md
├── test-driver.sh
└── testInstall.js
```

#### Then I move chrome driver as follows:

``` sh
root@test-chromedriver:~/wechaty# cp node_modules/chromedriver/lib/chromedriver/chromedriver .
```

and I get the `driver.getSession` error too

``` sh
root@test-chromedriver:~/wechaty# ts-node example/ding-dong-bot.ts

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


16:11:59 INFO Wechaty v#git[8f8f119 Limit video file size (#421)] initializing...
16:11:59 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 127
(node:11946) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
16:11:59 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
16:11:59 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/root/wechaty/src/puppet-web/browser-driver.ts:138:21)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
16:11:59 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
16:11:59 ERR PuppetWebBrowser quit() this.driver.quit() exception Server terminated early with status 127
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Server terminated early with status 127
16:11:59 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
16:11:59 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/root/wechaty/src/puppet-web/browser-driver.ts:138:21)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
16:11:59 INFO Bot error: Error: initChromeDriver() got invalid driver
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: can not say before login
(node:11946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'quit' of undefined
16:12:06 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
16:12:06 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
16:12:06 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
16:12:06 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
```

**Comment by lijiarui** [comment]
@shuhankuang did you move chromedriver to a higher directory than node_module too?

**Comment by shuhankuang** [comment]
@lijiarui 
No, I didn't. now I run the example with docker in my ubuntu with the code.
```
$ wechaty mybot.ts
```
but also I can't run with 
```
$ node mybot.js
```
I don't know why. :(

**Comment by lijiarui** [comment]
@shuhankuang Could you reopen the issue please? I think maybe it is a bug and should be fix.
I'm trying to find the reason

**Comment by lijiarui** [comment]
@shuhankuang hi, did you install chrome (not chrome driver) before? 

see more #48 

I guess it may fix.

**Comment by zixia** [comment]
I'll close this issue because it is not reproducable.

Please submit a new issue if there still have problem with this.

**Comment by yangboz** [comment]
Maybe missing steps on install chromedriver on ubuntu:
```
sudo apt-get install unzip

wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip

unzip chromedriver_linux64.zip

chmod +x chromedriver

sudo mv -f chromedriver /usr/local/share/chromedriver

sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
```
@see: https://christopher.su/2015/selenium-chromedriver-ubuntu/
