### ISSUE TITLE
Always getSession timeout

### ISSUE THREAD

**Issue by chenzhutian** [Chatie/wechaty#463]
### Network Information
1. In HongKong
2. On my own PC.

### doctor info  by running `npm run doctor` 
```
bash-4.3# npm run doctor

> wechaty@0.7.89 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.7.89 check-node-version /wechaty
> check-node-version --node ">= 6.9"

node: 7.9.0
npm: 4.4.4
yarn: 0.23.3

  #### Wechaty Doctor

  1. Wechaty version: 0.7.89
  2. Linux x64 version 4.9.13-moby memory 329/1980 MB
  3. Docker: true
  4. Node version: v7.9.0
  5. Tcp IPC TEST: PASS
  6. Chromedriver: ChromeDriver 2.25 (5a911c1ac99b36efadff2041357740080cc27220)
```

### Expected behavior
Run the `ding-dong-bot.ts` properly.

### Actual behavior
show me driver.getSession() timeout(halt?)
```
05:40:48 INFO Wechaty v0.7.89 initializing...
05:40:55 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:40:55 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:40:55 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:40:55 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
05:41:02 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:41:02 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:41:02 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:41:02 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
05:41:09 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:41:09 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:41:09 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:41:09 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
05:41:16 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:41:16 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:41:16 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:41:16 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/wechaty/src/puppet-web/browser-driver.ts:146:21)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
05:41:16 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
05:41:48 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:139) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
05:41:55 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:42:02 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:42:09 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:42:09 ERR PuppetWebBrowser quit() this.driver.quit() exception unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:42:09 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
05:42:09 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/wechaty/src/puppet-web/browser-driver.ts:146:21)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
05:42:09 INFO Bot error: Error: initChromeDriver() got invalid driver
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: can not say before login
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'quit' of undefined
```

### Steps to reproduce the behavior (and fixes, if any)
1. git clone https://github.com/Chatie/wechaty.git
2. cd wechaty
3. docker build --rm -t my-wechaty .
4. docker run -it my-wechaty bash
5. npm run ts-node example/ding-dong-bot.ts

### Paste the full output logs here with `WECHATY_LOG=silly` set
```
> wechaty@0.7.89 ts-node /wechaty
> ts-node "ding-dong-bot.ts"


| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


05:45:16 INFO Wechaty v0.7.89 initializing...
05:45:23 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:45:23 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:45:23 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:45:23 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
05:45:30 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:45:30 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:45:30 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:45:30 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
05:45:37 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:45:37 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:45:37 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:45:37 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
05:45:44 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
05:45:44 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
05:45:44 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
05:45:44 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/wechaty/src/puppet-web/browser-driver.ts:146:21)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
05:45:44 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
05:46:16 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:251) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
05:46:23 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:46:30 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:46:37 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:46:37 ERR PuppetWebBrowser quit() this.driver.quit() exception unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.9.13-moby x86_64)
05:46:37 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
05:46:37 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/wechaty/src/puppet-web/browser-driver.ts:146:21)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
05:46:37 INFO Bot error: Error: initChromeDriver() got invalid driver
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: can not say before login
(node:251) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'quit' of undefined
```

**Comment by lijiarui** [comment]
see this: https://github.com/Chatie/wechaty/wiki/faq#6-how-to-install--run-wechaty-using-npm-instead-of-docker

check whether you have installed chrome correctly and set path

**Comment by chenzhutian** [comment]
Yes I have installed chrome correctly.
After digging into the `entrypoint.sh` file, I fix this problem by running the command below before I run my bot.
`PATH=$PATH:/wechaty/bin:/wechaty/node_modules/.bin`

**Comment by chenzhutian** [comment]
I think this is one of the key issues to run the wechaty correctly. Maybe it should be documented.

**Comment by lijiarui** [comment]
good job！ thanks!   I'll add this issue to FAQ.
