### ISSUE TITLE
Error: unknown error: o.isBrandContact is not a function

### ISSUE THREAD

**Issue by xinbenlv** [Chatie/wechaty#486]
Very frequently when the bot is being ran, this error shows up after waiting for a while (like a few hours), has anyone seen this as well?

```
00:47:16 WARN PuppetWebBrowser execute() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver i, WebDriverError: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
00:47:16 WARN PuppetWebBridge execute() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
00:47:16 WARN PuppetWebBridge proxyWechaty() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
00:47:16 ERR PuppetWebBridge send() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
00:47:16 ERR PuppetWeb send() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 54): WebDriverError: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-66-generic x86_64)
^C Script terminated by Control-C
```

**Comment by zixia** [comment]
Duplicated with #81 

Provide a reproducible code snip is needed.
