### ISSUE TITLE
[docker] onbuild failed to start when we put `wechaty` as dependency in package.json

### ISSUE THREAD

**Issue by imWildCat** [Chatie/wechaty#500]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) Out of China, Europe
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? OVH, with Rancher

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
```bash
bash-4.3# /wechaty/bin/entrypoint.sh wechaty run doctor

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  ____                            _   _
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _
 / ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/

Starting Wechaty v0.8.3 with Node.js v7.9.0 ...
npm ERR! path /bot/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/bot/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2017-05-08T17_34_41_487Z-debug.log


```

### Expected behaviour
I started to build a micro service of WeChaty: https://github.com/imWildCat/wechaty-slave.
While dockerizing it, I hope that the app can start successfully.

### Actual behavior
Errors related to puppets:
```shell
08/05/2017 18:30:44
08/05/2017 18:30:44 __        __        _           _
08/05/2017 18:30:44 \ \      / /__  ___| |__   __ _| |_ _   _
08/05/2017 18:30:44  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
08/05/2017 18:30:44   \ V  V /  __/ (__| | | | (_| | |_| |_| |
08/05/2017 18:30:44    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
08/05/2017 18:30:44                                     |___/
08/05/2017 18:30:44____________________________________________________
08/05/2017 18:30:44            https://www.wechaty.io
08/05/2017 18:30:44  ____                            _   _
08/05/2017 18:30:44 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
08/05/2017 18:30:44| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
08/05/2017 18:30:44| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
08/05/2017 18:30:44 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
08/05/2017 18:30:44                                              |___/
08/05/2017 18:30:44  ____ _           _   ____        _
08/05/2017 18:30:44 / ___| |__   __ _| |_| __ )  ___ | |_ ___
08/05/2017 18:30:44| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
08/05/2017 18:30:44| |___| | | | (_| | |_| |_) | (_) | |_\__ \
08/05/2017 18:30:44 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
08/05/2017 18:30:44
08/05/2017 18:30:45
08/05/2017 18:30:45Starting Wechaty v0.8.3 with Node.js v7.9.0 ...
08/05/2017 18:30:46
08/05/2017 18:30:46> wechaty-slave@0.0.1 start /app
08/05/2017 18:30:46> NODE_ENV=production ts-node ./src/wechaty_slave.ts
08/05/2017 18:30:46
08/05/2017 18:30:49ENV: NODE_ENV production
08/05/2017 18:30:49ENV: MASTER_HOST undefined
08/05/2017 18:30:49ENV: MASTER_PORT undefined
08/05/2017 18:30:49ENV: MASTER_PROTOCOL undefined
08/05/2017 18:30:49ENV: MASTER_PATH undefined
08/05/2017 18:30:49ENV: MASTER_TOKEN undefined
08/05/2017 18:30:49ENV: NODE_ENV production
08/05/2017 18:30:49ENV: MASTER_HOST undefined
08/05/2017 18:30:49ENV: MASTER_PORT undefined
08/05/2017 18:30:49ENV: MASTER_PROTOCOL undefined
08/05/2017 18:30:49ENV: MASTER_KEY undefined
08/05/2017 18:30:50chromie-worker-1
08/05/2017 18:30:5017:30:50 INFO Wechaty v0.8.16 initializing...
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
08/05/2017 18:30:50(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 1
08/05/2017 18:30:50(node:40) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
08/05/2017 18:30:50(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
08/05/2017 18:30:50(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
08/05/2017 18:30:50    at BrowserDriver.<anonymous> (/app/node_modules/wechaty/src/puppet-web/browser-driver.ts:146:21)
08/05/2017 18:30:50    at Generator.next (<anonymous>)
08/05/2017 18:30:50    at fulfilled (/app/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
08/05/2017 18:30:50    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
08/05/2017 18:30:5017:30:50 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 ERR PuppetWebBrowser quit() this.driver.quit() exception Server terminated early with status 1
08/05/2017 18:30:50(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Server terminated early with status 1
08/05/2017 18:30:5017:30:50 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
08/05/2017 18:30:5017:30:50 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
08/05/2017 18:30:50    at BrowserDriver.<anonymous> (/app/node_modules/wechaty/src/puppet-web/browser-driver.ts:146:21)
08/05/2017 18:30:50    at Generator.next (<anonymous>)
08/05/2017 18:30:50    at fulfilled (/app/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
08/05/2017 18:30:50    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
08/05/2017 18:30:50Wechaty error: Error: initChromeDriver() got invalid driver
08/05/2017 18:30:50    at BrowserDriver.<anonymous> (/app/node_modules/wechaty/src/puppet-web/browser-driver.ts:146:21)
08/05/2017 18:30:50    at Generator.next (<anonymous>)
08/05/2017 18:30:50    at fulfilled (/app/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
08/05/2017 18:30:50    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
08/05/2017 18:30:50(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'quit' of undefined
08/05/2017 18:30:5717:30:57 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
08/05/2017 18:30:5717:30:57 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
08/05/2017 18:30:5717:30:57 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
08/05/2017 18:30:5717:30:57 WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
```

### Steps to reproduce the behavior (and fixes, if any)
```shell
docker run -it wildcat/wechaty-slave
```

**Comment by mukaiu** [comment]
Get rid of wechaty dependency in your package.json if you are using Docker solution. #281

**Comment by imWildCat** [comment]
@mukaiu Thanks!

Fixed by add these lines into `Dockerfile`:
```dockerfile
RUN rm -rf /app/node_modules/wechaty
RUN rm -rf /app/node_modules/chromedriver
```

**Comment by zixia** [comment]
You two are so fast!

I think this problem should be documented better, and also I want to find out the reason that causes wechaty start fail.

Because as my experience, put a wechaty dependency in your package.json should not cause your code start fail.

**Comment by zixia** [comment]
I think I finally found out the reason for this issue. 

1. We specified a `VOLUME [ "/bot"]` in our Dockerfile of Wechaty, 
1. We use `FROM zixia/wechaty` as a base image
1. We use `WORKDIR /bot`, in our child Dockerfile, which `/bot` is a VOLUME set by the base image
1. BUG: here will have trouble: **Docker build will not keep the contents that RUN command write to a VOLUME directory**.

**Comment by zixia** [comment]
Do not set VOLUME in Dockerfile anymore. 
See: https://github.com/Chatie/wechaty/commit/191b1c300327bc66b2516f09a5ee75f5734bf5ca
