### ISSUE TITLE
example/hot-reload-bot/index.js do NOT WORK in 0.8.18 docker

### ISSUE THREAD

**Issue by liyuanzao** [Chatie/wechaty#503]
```shell
Howards-Air:wechaty howard$ docker run -ti --rm --volume="$(pwd)":/bot zixia/wechaty example/hot-reload-bot/index.js 

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           

Starting Wechaty v0.8.18 with Node.js v7.10.0 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended by your bot script.
Executing node example/hot-reload-bot/index.js
fs.js:1400
    throw error;
    ^

Error: watch ./listener ENOENT
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1398:19)
    at Object.fs.watch (fs.js:1424:11)
    at Object.<anonymous> (/bot/example/hot-reload-bot/index.js:60:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
  ____  _   _  ____   ____  _____ ____   ___  ____ _____  
 | __ )| | | |/ ___| |  _ \| ____|  _ \ / _ \|  _ \_   _| 
 |  _ \| | | | |  _  | |_) |  _| | |_) | | | | |_) || |   
 | |_) | |_| | |_| | |  _ <| |___|  __/| |_| |  _ < | |   
 |____/ \___/ \____| |_| \_\_____|_|    \___/|_| \_\|_|   
                                                          
Press ENTER to continue ... 

### 1. source code of example/hot-reload-bot/index.js

/**
 * Wechaty hot load dots demo
 *
 * DEV: docker run -ti -e --rm --volume="$(pwd)":/bot zixia/wechaty index.js
 * PROD: docker run -ti -e NODE_ENV=production --rm --volume="$(pwd)":/bot zixia/wechaty index.js
 * 
 * @author: Gcaufy
 * 
 */
const fs = require('fs');
const path = require('path');
const Wechaty = require('wechaty').default;

const isProd = process.env.NODE_ENV === 'production';
const bot = Wechaty.instance();

const EVENT_LIST = ['scan', 'logout', 'login', 'friend', 'room-join', 'room-leave', 'room-topic', 'message', 'heartbeat', 'error'];


// Load lisenter
const loadListener = (evt) => {
    let fn;
    try {
        fn = require(`./listener/${evt}`);
        console.log(`binded listener: ${evt}`);
    } catch (e) {
        fn = () => void 0;
        if (e.toString().indexOf('Cannot find module') > -1) {
            console.warn(`listener ${evt} is not defined.`);
        } else {
            console.error(e);
        }
    }
    return fn;
}

// purge require cache
const purgeCache = (moduleName) => {
    var mod = require.resolve(moduleName);
    if (mod && ((mod = require.cache[mod]) !== undefined)) {
        (function traverse(mod) {
            mod.children.forEach(function (child) {
                traverse(child);
            });
            delete require.cache[mod.id];
        }(mod));
    }
    
    Object.keys(module.constructor._pathCache).forEach(function(cacheKey) {
        if (cacheKey.indexOf(moduleName)>0) {
            delete module.constructor._pathCache[cacheKey];
        }
    });
};

let eventHandler = {};


if (!isProd) { // start a watcher only if it's not production environment.
    fs.watch('./listener', (e, filename) => {
        let evt = filename.substring(0, filename.length - 3);
        console.log(`${e}: ${filename}`);

        if (EVENT_LIST.indexOf(evt) > -1) {
            if (e === 'change') {
                console.log(`${evt} listener reloaded.`);
                purgeCache(`./listener/${evt}`);
                // It may read an empty file, if not use setTimeout
                setTimeout(() => {
                    bot.removeListener(evt, eventHandler[evt]);
                    //console.log('filecontent: ' + fs.readFileSync(`./listener/${evt}.js`));
                    eventHandler[evt] = loadListener(evt);
                    bot.on(evt, eventHandler[evt]);
                }, 1000);
            } else if (e === 'rename') {
                console.log(`${evt} listener removed.`);
                bot.removeListener(evt, eventHandler[evt]);
                eventHandler[evt] = () => void 0;
                bot.on(evt, eventHandler[evt]);
            }
        }
    });
}

// Bind events
EVENT_LIST.forEach(evt => {
    eventHandler[evt] = loadListener(evt);
    bot.on(evt, eventHandler[evt]);
});


bot.init();

### 2. directory structor of /bot

total 136
-rw-r--r--  1 root root 27187 May  9 09:44 CHANGELOG.md
-rw-r--r--  1 root root  1150 May  9 09:44 CONTRIBUTING.md
-rw-r--r--  1 root root  2710 May  9 09:44 Dockerfile
-rw-r--r--  1 root root  1535 May  9 09:44 Dockerfile.node
-rw-r--r--  1 root root   247 May  9 09:44 Dockerfile.onbuild
-rw-r--r--  1 root root 11360 May  9 09:44 LICENSE
-rw-r--r--  1 root root 17493 May  9 09:44 README.md
-rw-r--r--  1 root root   345 May  9 12:22 WECHATY_IO_TOKEN.wechaty.json
-rw-r--r--  1 root root   635 May  9 09:44 app.json
-rw-r--r--  1 root root   742 May  9 09:44 appveyor.yml
drwxr-xr-x  9 root root   306 May  9 09:44 bin
-rw-r--r--  1 root root   544 May  9 09:44 circle.yml
-rw-r--r--  1 root root  1537 May  9 12:54 demo.wechaty.json
drwxr-xr-x  5 root root   170 May  9 09:44 doc
drwxr-xr-x  4 root root   136 May  9 09:44 docs
drwxr-xr-x 13 root root   442 May  9 09:44 example
drwxr-xr-x  8 root root   272 May  9 09:44 image
-rw-r--r--  1 root root   923 May  9 09:44 index.ts
-rw-r--r--  1 root root   288 May  9 12:24 mybot.js
-rw-r--r--  1 root root  5604 May  9 09:44 package.json
-rw-r--r--  1 root root 15747 May  9 12:55 rawObj.log
drwxr-xr-x  8 root root   272 May  9 09:44 script
drwxr-xr-x 19 root root   646 May  9 09:44 src
drwxr-xr-x 14 root root   476 May  9 09:44 test
-rw-r--r--  1 root root   667 May  9 09:44 tsconfig.json
-rw-r--r--  1 root root  2600 May  9 09:44 tslint.json

### 3. package.json

{
  "name": "wechaty",
  "version": "0.8.18",
  "description": "Wechat for Bot(Personal Account)",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "wechaty": {
    "DEFAULT_HEAD": "chrome",
    "DEFAULT_PUPPET": "web",
    "DEFAULT_PROFILE": "demo",
    "DEFAULT_PORT": 8788,
    "DEFAULT_PROTOCOL": "io|0.0.1",
    "DEFAULT_TOKEN": "WECHATY_IO_TOKEN",
    "DEFAULT_APIHOST": "api.chatie.io",
    "CMD_CHROMIUM": "/wechaty/bin/xvfb-chromium"
  },
  "scripts": {
    "ava": "ava --verbose --extension ts",
    "ts-node": "ts-node",
    "dist": "npm run clean && tsc && shx cp package.json dist/ && shx cp src/puppet-web/*.js dist/src/puppet-web/",
    "doc": "npm run dist && jsdoc2md dist/src/{wechaty,room,contact,friend-request,message}.js > docs/index.md",
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    "changelog": "github_changelog_generator -u chatie -p wechaty && sed -i'' /greenkeeper/d CHANGELOG.md",
    "doctor": "npm run check-node-version && ts-node bin/doctor",
    "clean": "shx rm -fr dist/*",
    "check-node-version": "check-node-version --node \">= 6.9\"",
    "lint": "npm run check-node-version && npm run eslint && npm run tslint",
    "nycava": "WECHATY_HEAD=chrome nyc ava --serial --fail-fast --verbose --timeout=3m \"dist/{src,test}/**/*.spec.js\"",
    "eslint": "eslint \"{bin,example,src,test}/**/*.js\" --ignore-pattern=\"test/fixture/**\"",
    "tslint": "tslint --project tsconfig.json --type-check \"{bin,example,src,test}/**/*.ts\" --exclude=\"test/fixture/**\" --exclude=\"dist/\" && npm run clean && tsc --noEmit",
    "shlint": "bash -n bin/*.sh",
    "pretest": "npm run clean && npm run lint && npm run dist",
    "sloc": "sloc bin example src test index.ts --details --format cli-table --keys total,source,comment && sloc bin example src test index.ts",
    "test": "npm run test:chrome",
    "posttest": "npm run clean && npm run sloc",
    "test:phantomjs": "cross-env LC_ALL=C WECHATY_HEAD=phantomjs ava --verbose --fail-fast --serial --timeout=3m \"dist/{src,test}/**/*.spec.js\"",
    "test:chrome": "cross-env LC_ALL=C WECHATY_HEAD=chrome ava --serial --fail-fast --verbose --timeout=3m \"dist/{src,test}/**/*.spec.js\"",
    "test:chrome:fast": "cross-env LC_ALL=C WECHATY_HEAD=chrome ava --fail-fast --timeout=3m \"dist/{src,test}/**/*.spec.js\"",
    "testdev": "cross-env LC_ALL=C WECHATY_LOG=silly ava --ext ts --serial --verbose --fail-fast --timeout=2m",
    "testdist": "cross-env WECHATY_LOG=SILLY WECHATY_HEAD=chrome ava --ext ts --verbose --fail-fast --timeout=2m",
    "io-client": "ts-node bin/io-client",
    "dev": "ts-node dev.ts",
    "demo": "ts-node example/ding-dong-bot.ts",
    "start": "npm run demo"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/chatie/wechaty.git"
  },
  "bin": {
    "wechaty-io-client": "dist/bin/io-client.js",
    "wechaty-doctor": "dist/bin/doctor.js",
    "wechaty-version": "dist/bin/version.js"
  },
  "keywords": [
    "wechat",
    "微信",
    "weixin",
    "personal",
    "bot",
    "robot",
    "chatbot",
    "framework",
    "wechaty",
    "chatie",
    "微信控"
  ],
  "author": {
    "name": "Zhuohuan LI",
    "email": "zixia@zixia.net",
    "url": "www.zixia.net"
  },
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/chatie/wechaty/issues"
  },
  "homepage": "https://github.com/chatie/wechaty#readme",
  "eslintConfig": {
    "env": {
      "browser": true,
      "node": true,
      "es6": true
    },
    "plugins": [
      "ava"
    ],
    "parser": "babel-eslint",
    "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "module",
      "ecmaFeatures": {
        "impliedStrict": true
      },
      "extends": "plugin:ava/recommended"
    }
  },
  "ava": {
    "require": [
      "ts-node/register"
    ]
  },
  "engines": {
    "node": ">= 6.9.0"
  },
  "dependencies": {
    "@types/selenium-webdriver": "3.0.3",
    "@types/socket.io": "1.4.29",
    "bl": "1.2.1",
    "body-parser": "1.17.1",
    "brolog": "1.1.16",
    "chromedriver": "2.29.0",
    "express": "5.0.0-alpha.5",
    "is-ci": "1.0.10",
    "is-docker": "1.1.0",
    "moment": "2.18.1",
    "ps-tree": "1.1.0",
    "retry-promise": "1.0.0",
    "selenium-webdriver": "3.4.0",
    "socket.io": "1.7.4",
    "state-switch": "0.1.13",
    "ws": "2.3.1"
  },
  "devDependencies": {
    "@types/body-parser": "1.16.3",
    "@types/express": "4.0.35",
    "@types/fluent-ffmpeg": "2.1.0",
    "@types/mime": "0.0.29",
    "@types/node": "7.0.18",
    "@types/request": "0.0.43",
    "@types/sinon": "2.2.1",
    "@types/ws": "0.0.41",
    "apiai": "4.0.2",
    "ava": "0.18.2",
    "babel-eslint": "7.2.3",
    "check-node-version": "2.1.0",
    "codelyzer": "3.0.1",
    "cookie-parser": "1.4.3",
    "coveralls": "2.13.1",
    "cross-env": "4.0.0",
    "eslint": "3.18.0",
    "eslint-plugin-ava": "4.2.0",
    "finis": "0.0.2",
    "fluent-ffmpeg": "2.1.2",
    "jsdoc-to-markdown": "3.0.0",
    "nyc": "10.3.2",
    "qrcode-terminal": "0.11.0",
    "request": "2.81.0",
    "shx": "0.2.2",
    "sinon": "2.2.0",
    "sloc": "0.2.0",
    "ts-node": "3.0.4",
    "tslint": "5.2.0",
    "tslint-jsdoc-rules": "0.1.2",
    "tuling123-client": "0.0.1",
    "typescript": "2.3.2",
    "yarn": "0.23.4"
  },
  "files_comment__whitelist_npm_publish": "http://stackoverflow.com/a/8617868/1123955",
  "files": [
    "CHANGELOG",
    "LICENSE",
    "README.md",
    "package.json",
    "*.js",
    "*.js.map",
    "*.d.ts",
    "bin/",
    "dist/",
    "src/"
  ],
  "publishConfig": {
    "tagBak": "next",
    "tag": "latest"
  }
}

### 4. directory structor inside /bot/node_modules

ls: cannot access '/bot/node_modules': No such file or directory
No node_modules

### 5. wechaty doctor


  #### Wechaty Doctor

  1. Wechaty version: 0.8.18
  2. Linux x64 version 4.9.13-moby memory 598/1999 MB
  3. Docker: true
  4. Node version: v7.10.0
  5. Tcp IPC TEST: PASS
  6. Chromedriver: ChromeDriver 2.25 (5a911c1ac99b36efadff2041357740080cc27220)


  
  ____        _               _ _             ___ ____ ____  _   _ _____  
 / ___| _   _| |__  _ __ ___ (_) |_    __ _  |_ _/ ___/ ___|| | | | ____| 
 \___ \| | | | '_ \| '_ ` _ \| | __|  / _` |  | |\___ \___ \| | | |  _|   
  ___) | |_| | |_) | | | | | | | |_  | (_| |  | | ___) |__) | |_| | |___  
 |____/ \__,_|_.__/|_| |_| |_|_|\__|  \__,_| |___|____/____/ \___/|_____| 
                                                                          
_____________________________________________________________
####### please paste all the above diagnose messages #######

Wechaty Issue https://github.com/chatie/wechaty/issues

Press ENTER to continue ... 

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _     _  
 | ____|_  _(_) |_  / | 
 |  _| \ \/ / | __| | | 
 | |___ >  <| | |_  | | 
 |_____/_/\_\_|\__| |_| 
```

**Comment by galendai** [comment]
try to run the docker under `./example/hot-reload-bot' directory. it should resolve the problem.
