### ISSUE TITLE
static Contact.find() / static Contact.findAll() throws exception

### ISSUE THREAD

**Issue by galendai** [Chatie/wechaty#520]
### Actual behavior
Contact.find() related functions always throw exceptions:
>static Contact.find(query: Query) Promise
>static Contact.findAll(query: Query) Promise

### Steps to reproduce the behavior (and fixes, if any)

```
try {
    const contactFindByName = await Contact.findAll( );
} catch (ex) {
   console.log(`${ex}`);
}

Log output:
========
Error: id must be string. found: undefined
    at new Contact (/wechaty/dist/src/contact.js:45:19)
    at Wechaty.onMessage (/bot/controller/message.js:83:19)
    at emitOne (events.js:96:13)
    at Wechaty.emit (events.js:191:7)
    at PuppetWeb.<anonymous> (/wechaty/dist/src/wechaty.js:235:31)
    at emitOne (events.js:96:13)
    at PuppetWeb.emit (events.js:191:7)
    at PuppetWeb._callee5$ (/wechaty/dist/src/puppet-web/event.js:289:18)
    at tryCatch (/wechaty/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/wechaty/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/wechaty/node_modules/regenerator-runtime/runtime.js:117:21)
    at fulfilled (/wechaty/dist/src/puppet-web/event.js:4:58)
    at tryCatcher (/bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/bot/node_modules/bluebird/js/release/promise.js:614:10)

```
----
```
try {
    const contactFindByName = await Contact.find({ name:"ContactName"} );
} catch (ex) {
   console.log(`${ex}`);
}

Log output:
========
Error: id must be string. found: undefined
    at new Contact (/wechaty/dist/src/contact.js:45:19)
    at Wechaty.onMessage (/bot/controller/message.js:83:19)
    at emitOne (events.js:96:13)
    at Wechaty.emit (events.js:191:7)
    at PuppetWeb.<anonymous> (/wechaty/dist/src/wechaty.js:235:31)
    at emitOne (events.js:96:13)
    at PuppetWeb.emit (events.js:191:7)
    at PuppetWeb._callee5$ (/wechaty/dist/src/puppet-web/event.js:289:18)
    at tryCatch (/wechaty/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/wechaty/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/wechaty/node_modules/regenerator-runtime/runtime.js:117:21)
    at fulfilled (/wechaty/dist/src/puppet-web/event.js:4:58)
    at tryCatcher (/bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/bot/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by lijiarui** [comment]
Have you import `Contact` as you import `wechaty` do?

**Comment by galendai** [comment]
Yes, already imported. 
`const { Message, MediaMessage, MsgType, Contact } = require('wechaty');`

**Comment by lijiarui** [comment]
Well, could you try the following code:
```ts
import { Wechaty, Contact } from 'wechaty'
```

**Comment by zixia** [comment]
@lijiarui No, this problem will not appear if the `import`/`require` fail.

@galendai Could you please provide the full shortest code that can reproduce this error?

I'm afraid that there's some bug in your code because inside the Wechaty Framework itself, we will always provide the right `id` .

**Comment by galendai** [comment]
@zixia ouch, u are definitely correct. I incidentally create an new instance without giving `id` in constructor and it's not related to the static methods at all. 

Really appreciated for both of you & @lijiarui 's attentions. 

this issue is safe to close now.

**Comment by zixia** [comment]
Great to hear that, cheers!
