### ISSUE TITLE
memoryCheck() memory not enough

### ISSUE THREAD

**Issue by kk3hi3123** [Chatie/wechaty#597]
### Provide Your Network Information

Where is the location of your server? (i.e. City, or In/Out China)
Hong Kong

### Expected behavior

The bot keeps running forever.

### Actual behavior

The bot stops running after 8 hours with error message:
```
WARN PuppetWebWatchdog memoryCheck() memory not enough: free 3 < require 4 MB
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: memory not enough: free 3 < require 4 MB
    at PuppetWeb.memoryCheck (/Users/BullB/Documents/Gitlab/phonebetting-wechat/node_modules/wechaty/dist/src/puppet-web/watchdog.js:135:19)
    at PuppetWeb.onFeed (/Users/BullB/Documents/Gitlab/phonebetting-wechat/node_modules/wechaty/dist/src/puppet-web/watchdog.js:72:17)
    at emitOne (events.js:115:13)
    at PuppetWeb.emit (events.js:210:7)
    at PuppetWeb.onServerDing (/Users/BullB/Documents/Gitlab/phonebetting-wechat/node_modules/wechaty/dist/src/puppet-web/event.js:110:10)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Socket.client.on.data (/Users/BullB/Documents/Gitlab/phonebetting-wechat/node_modules/wechaty/dist/src/puppet-web/server.js:136:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
```

### Steps to reproduce the behavior (and fixes, if any)

Run the bot for more than 8 hours.

**Comment by zixia** [comment]
The message itself is clear enough: you are run out of memory.

You should:
1. Add more swap to your server, or
1. Switch to run Wechaty on a new server with enough memory. e.g. 2GB.

**Comment by zixia** [comment]
Hope you had already fixed it.
