### ISSUE TITLE
Bot log out frequently and got some strange error between it logout and relogin automatically

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#612]
I found the bot is logged out very frequently(no more than 10 minutes), and between during it logout and re-login, it has the following error.(I have deleted some repeated errors)
``` shell
3号PPT助教 logout
12:26:28 WARN PuppetWebBrowser execute() exception: unknown error: session deleted because of page crash
from unknown error: cannot determine loading s, WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
12:26:28 WARN PuppetWebBridge execute() exception: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
12:26:28 WARN PuppetWebBrowser execute() exception: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platfo, WebDriverError: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
12:26:28 WARN PuppetWebBridge execute() exception: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
12:26:28 WARN PuppetWebBridge proxyWechaty() exception: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)


12:26:29 WARN PuppetWebBrowser execute() this.dead() Error: Browser.execute() browser dead
    at Browser.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/browser.ts:391:17)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/browser.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:3:12)
    at Browser.execute (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:328:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:498:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.execute (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:455:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:450:36)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:389:16)
    at attempt (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:348:19)
    at attempt (/bot/node_modules/retry-promise/lib/index.js:19:7)
    at Timeout._onTimeout (/bot/node_modules/retry-promise/lib/index.js:24:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

12:26:29 WARN PuppetWebBridge execute() exception: Browser.execute() browser dead
12:26:29 WARN PuppetWebBridge execute() exception: Browser.execute() browser dead

12:26:29 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: Browser.execute() browser dead
    at Browser.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/browser.ts:391:17)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/browser.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:3:12)
    at Browser.execute (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:328:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:498:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.execute (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:455:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:450:36)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:389:16)
    at attempt (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:348:19)
    at attempt (/bot/node_modules/retry-promise/lib/index.js:19:7)
    at Timeout._onTimeout (/bot/node_modules/retry-promise/lib/index.js:24:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

12:26:29 WARN PuppetWebBrowser execute() exception: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platfo, WebDriverError: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
12:26:29 WARN PuppetWebBridge execute() exception: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
12:26:29 WARN PuppetWebBridge proxyWechaty() noWechaty exception: WebDriverError: no such session
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 4.4.0-77-generic x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

12:26:30 WARN PuppetWebBrowser execute() exception: Cannot read property 'executeScript' of undefined, TypeError: Cannot read property 'executeScript' of undefined
    at BrowserDriver.executeScript (/bot/node_modules/wechaty/src/puppet-web/browser-driver.ts:387:91)
    at Browser.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/browser.ts:398:45)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/browser.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:3:12)
    at Browser.execute (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:328:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:498:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.execute (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:455:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:450:36)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:389:16)
    at attempt (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:348:19)
    at attempt (/bot/node_modules/retry-promise/lib/index.js:19:7)
    at Timeout._onTimeout (/bot/node_modules/retry-promise/lib/index.js:24:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

12:26:30 WARN PuppetWebBridge execute() exception: Cannot read property 'executeScript' of undefined
12:26:30 WARN PuppetWebBridge execute() exception: Cannot read property 'executeScript' of undefined

12:26:30 WARN PuppetWebBridge proxyWechaty() noWechaty exception: TypeError: Cannot read property 'executeScript' of undefined
    at BrowserDriver.executeScript (/bot/node_modules/wechaty/src/puppet-web/browser-driver.ts:387:91)
    at Browser.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/browser.ts:398:45)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/browser.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:3:12)
    at Browser.execute (/bot/node_modules/wechaty/dist/src/puppet-web/browser.js:328:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:498:32)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.execute (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:455:16)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:450:36)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:3:12)
    at Bridge.proxyWechaty (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:389:16)
    at attempt (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:348:19)
    at attempt (/bot/node_modules/retry-promise/lib/index.js:19:7)
    at Timeout._onTimeout (/bot/node_modules/retry-promise/lib/index.js:24:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

12:26:37 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: there is no WechatyBro in browser(yet)
    at Bridge.<anonymous> (/bot/node_modules/wechaty/src/puppet-web/bridge.ts:452:19)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/puppet-web/bridge.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

12:26:48 WARN Contact parse() got empty rawObj!

3号PPT助教login
3号PPT助教登陆成功！
```

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by lijiarui** [comment]
@zixia  I suggest changing this strange log to throw an error. How do you think about it?

**Comment by zixia** [comment]
I have no idea about your suggestion because I do not know why you are purposing a behavior like this.

**Comment by lijiarui** [comment]
I have no idea too and fix this error.

**Comment by xinghu0164** [comment]
@lijiarui I met the same problem as you. Could you give me some suggestion how to solve it? Thanks

**Comment by zixia** [comment]
@xinghu0164 What Wechaty version are you using?

**Comment by xinghu0164** [comment]
@zixia  0.8.234 currently. Could it help if I upgrade? Thanks

**Comment by zixia** [comment]
@xinghu0164 Yes. Please upgrade to v0.11 and try again. I believe this issue should not exist anymore.

**Comment by kainy** [comment]
I meet this problem too wechaty version is 0.13.32。

**Comment by zixia** [comment]
Please submit a new issue if you can reproduce it, thanks!
