### ISSUE TITLE
windows 10 throws PuppetWeb initBrowser() exception: got invalid driver at ttl 0

### ISSUE THREAD

**Issue by francishero** [Chatie/wechaty#688]
05:15:46 ERR PuppetWeb initBrowser() exception: got invalid driver at ttl 0
05:15:46 ERR PuppetWeb init() exception: Error: got invalid driver at ttl 0

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:
$ node app.js
05:15:24 INFO Wechaty v0.8.129 initializing...
05:15:32 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
05:15:32 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
05:15:32 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 2
05:15:39 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
05:15:39 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
05:15:39 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 1
05:15:46 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
05:15:46 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
05:15:46 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 0
05:15:46 WARN PuppetWebBrowserDriver getChromeDriver() invalid after ttl expired: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (C:\Users\Francis\Desktop\xiaochengxu\wechaty_bots\node_modules\wechaty\dist\src\puppet-web\browser-driver.js:150:35)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Francis\Desktop\xiaochengxu\wechaty_bots\node_modules\wechaty\dist\src\puppet-web\browser-driver.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
05:15:46 ERR PuppetWebBrowser init() exception: got invalid driver at ttl 0
05:15:46 WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
05:15:46 WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
05:15:46 ERR PuppetWeb initBrowser() exception: got invalid driver at ttl 0
05:15:46 ERR PuppetWeb init() exception: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (C:\Users\Francis\Desktop\xiaochengxu\wechaty_bots\node_modules\wechaty\dist\src\puppet-web\browser-driver.js:150:35)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Francis\Desktop\xiaochengxu\wechaty_bots\node_modules\wechaty\dist\src\puppet-web\browser-driver.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
05:15:46 ERR Wechaty init() exception: got invalid driver at ttl 0
(node:5808) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: got invalid driver at ttl 0
(node:5808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
 exit code.



```
</details>

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

The more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment]
Hi @francishero , Had you solved your problem?

**Comment by francishero** [comment]
no, but someone advised me to use docker. Did you find a solution?

**Comment by zixia** [comment]
I have no problem with windows system, because all the unit tests are passed under windows system.

So I'll close issue for now, please feel free submit a new issue if you have other problems.
