### ISSUE TITLE
Error after restart  vps              invalid driver at ttl 0

### ISSUE THREAD

**Issue by ouweipeng8888** [Chatie/wechaty#788]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
tokyo
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
ubuntu
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

npm run 

### Full Output Logs

root@vultr:~/wechaty# WECHATY_LOG=silly npm run ts-node example/ding-dong-bot.ts

> wechaty@0.8.219 ts-node /root/wechaty
> ts-node "example/ding-dong-bot.ts"

09:42:58 SILL Brolog WECHATY_LOG set level to silly
09:42:58 INFO Config registering process.on("unhandledRejection") for development/debug

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/chatie/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...

09:42:59 SILL StateSwitch constructor(Wechaty, standby)
09:42:59 VERB Wechaty contructor()
09:42:59 VERB Wechaty addListener(logout, function)
09:42:59 VERB Wechaty addListener(login, function)
09:42:59 VERB Wechaty addListener(error, function)
09:42:59 VERB Wechaty addListener(scan, function)
09:42:59 VERB Wechaty addListener(message, function)
09:42:59 INFO Wechaty v#git[9c2f97e] initializing...
09:42:59 VERB Wechaty puppet: web
09:42:59 VERB Wechaty head: chrome
09:42:59 VERB Wechaty profile: demo.wechaty.json
09:42:59 VERB Wechaty uuid: 161248ae-1756-4d79-ae8e-9ddea4ba1b62
09:42:59 SILL StateSwitch Wechaty:current() is standby
09:42:59 VERB StateSwitch Wechaty:target(ready) <- (standby)
09:42:59 VERB StateSwitch Wechaty:current(ready,false) <- (standby,true)
09:42:59 SILL StateSwitch constructor(Puppet, dead)
09:42:59 VERB Config puppetInstance(PuppetWeb)
09:42:59 VERB PuppetWeb init() with head:chrome, profile:demo.wechaty.json
09:42:59 VERB StateSwitch Puppet:target(live) <- (dead)
09:42:59 VERB StateSwitch Puppet:current(live,false) <- (dead,true)
09:42:59 SILL UtilLib getPort(18788)
09:42:59 SILL UtilLib getPort(18788) return: 19826
09:42:59 VERB PuppetWeb init() getPort 19826
09:42:59 VERB PuppetWeb initServer()
09:42:59 SILL StateSwitch Puppet:target() is live
09:42:59 VERB PuppetWebServer init() on port 19826
09:42:59 VERB PuppetWebServer createHttpsServer() listen on port 19826
09:42:59 VERB PuppetWeb initServer() done
09:42:59 VERB PuppetWeb initBrowser()
09:42:59 SILL StateSwitch constructor(Browser, close)
09:42:59 VERB PuppetWebBrowser constructor() with head(chrome) sessionFile(demo.wechaty.json)
09:42:59 VERB PuppetWebBrowserDriver constructor(chrome)
09:42:59 VERB PuppetWebBrowserCookie constructor(BrowserDriver, demo.wechaty.json)
09:42:59 SILL StateSwitch Puppet:target() is live
09:42:59 VERB PuppetWebBrowser init()
09:42:59 SILL StateSwitch Browser:current() is close
09:42:59 VERB StateSwitch Browser:target(open) <- (close)
09:42:59 VERB StateSwitch Browser:current(open,false) <- (close,true)
09:42:59 VERB PuppetWebBrowserCookie hostname()
09:42:59 VERB PuppetWebBrowserCookie getCookiesFromFile() from demo.wechaty.json
09:42:59 SILL PuppetWebBrowserCookie hostname() no valid cookie in files, return default hostname
09:42:59 VERB PuppetWebBrowserDriver init() for head: chrome
09:42:59 VERB PuppetWebBrowserDriver getChromeDriver()
09:42:59 VERB PuppetWebBrowserDriver getChromeDriver() ttl: 2
09:42:59 VERB PuppetWebBrowserDriver getChromeDriver() new Builder()
09:42:59 VERB PuppetWebBrowserDriver getChromeDriver() new Builder() done
09:42:59 VERB PuppetWebBrowserDriver valid()
09:42:59 VERB PuppetWebBrowserDriver validDriverSession()
09:42:59 VERB PuppetWebBrowserDriver validDriverSession() getSession()
09:43:06 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
09:43:06 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
09:43:06 VERB PuppetWebBrowserDriver getChromeDriver() valid() is false at ttl 2
09:43:06 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 2
09:43:06 VERB PuppetWebBrowserDriver getChromeDriver() driver.quit() at ttl 2
09:43:06 VERB PuppetWebBrowserDriver getChromeDriver() ttl: 1
09:43:06 VERB PuppetWebBrowserDriver getChromeDriver() new Builder()
09:43:06 VERB PuppetWebBrowserDriver getChromeDriver() new Builder() done
09:43:06 VERB PuppetWebBrowserDriver valid()
09:43:06 VERB PuppetWebBrowserDriver validDriverSession()
09:43:06 VERB PuppetWebBrowserDriver validDriverSession() getSession()
09:43:13 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
09:43:13 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
09:43:13 VERB PuppetWebBrowserDriver getChromeDriver() valid() is false at ttl 1
09:43:13 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 1
09:43:13 VERB PuppetWebBrowserDriver getChromeDriver() driver.quit() at ttl 1
09:43:13 VERB PuppetWebBrowserDriver getChromeDriver() ttl: 0
09:43:13 VERB PuppetWebBrowserDriver getChromeDriver() new Builder()
09:43:13 VERB PuppetWebBrowserDriver getChromeDriver() new Builder() done
09:43:13 VERB PuppetWebBrowserDriver valid()
09:43:13 VERB PuppetWebBrowserDriver validDriverSession()
09:43:13 VERB PuppetWebBrowserDriver validDriverSession() getSession()
09:43:20 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() timeout(halt?)
09:43:20 WARN PuppetWebBrowserDriver validDriverSession() driver.getSession() exception: validDriverSession() driver.getSession() timeout(halt?)
09:43:20 VERB PuppetWebBrowserDriver getChromeDriver() valid() is false at ttl 0
09:43:20 WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver at ttl 0
09:43:20 VERB PuppetWebBrowserDriver getChromeDriver() driver.quit() at ttl 0
09:43:20 WARN PuppetWebBrowserDriver getChromeDriver() invalid after ttl expired: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (/root/wechaty/src/puppet-web/browser-driver.ts:212:21)
    at next (native)
    at fulfilled (/root/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
09:43:20 ERR PuppetWebBrowser init() exception: got invalid driver at ttl 0
09:43:20 VERB PuppetWebBrowser quit()
09:43:20 SILL StateSwitch Browser:current() is open
09:43:20 VERB StateSwitch Browser:target(close) <- (open)
09:43:20 VERB StateSwitch Browser:current(close,false) <- (open,false)
09:43:20 WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
09:43:20 WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
09:43:20 VERB StateSwitch Browser:current(close,true) <- (close,false)
09:43:20 ERR PuppetWeb initBrowser() exception: got invalid driver at ttl 0
09:43:20 ERR PuppetWeb init() exception: Error: got invalid driver at ttl 0
    at BrowserDriver.<anonymous> (/root/wechaty/src/puppet-web/browser-driver.ts:212:21)
    at next (native)
    at fulfilled (/root/wechaty/src/puppet-web/browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
09:43:20 INFO Bot error: Error: got invalid driver at ttl 0
09:43:20 VERB Wechaty say(Wechaty error: got invalid driver at ttl 0)
09:43:20 SILL StateSwitch Puppet:target() is live
09:43:20 SILL StateSwitch Puppet:current() is live
09:43:20 SILL StateSwitch Puppet:stable() is false
09:43:20 VERB PuppetWeb quit() state target(live) current(live) stable(false)
09:43:20 SILL StateSwitch Puppet:current() is live
09:43:20 VERB PuppetWeb quit() kill watchdog before do quit
09:43:20 SILL PuppetWebWatchdog onFeed: 60000, POISON[PuppetWeb.quit()]
09:43:20 VERB PuppetWebWatchdog onFeed(type=POSISON) WANG! I dead!
09:43:20 VERB PuppetWebWatchdog clearWatchDogTimer() nothing to clear
09:43:20 VERB StateSwitch Puppet:target(dead) <- (live)
09:43:20 VERB StateSwitch Puppet:current(dead,false) <- (live,false)
09:43:20 WARN PuppetWeb quit() no this.bridge
09:43:20 VERB PuppetWebServer quit()
09:43:20 VERB PuppetWebServer closing socketServer
09:43:20 VERB PuppetWebServer closing httpsServer
09:43:20 VERB PuppetWeb quit() server.quit() done
09:43:20 WARN PuppetWeb quit() no this.browser
09:43:20 VERB StateSwitch Puppet:current(dead,true) <- (dead,false)
09:43:20 VERB StateSwitch Puppet:target(dead) <- (dead)
09:43:20 ERR Wechaty init() exception: got invalid driver at ttl 0
09:43:20 ERR Bot init() fail: Error: got invalid driver at ttl 0
09:43:20 VERB Wechaty quit()
09:43:20 SILL StateSwitch Wechaty:current() is ready
09:43:20 SILL StateSwitch Wechaty:inprocess() is true
09:43:20 ERR Wechaty quit() must run on a inited instance.
Wechaty exit -1 because of exit 
09:43:20 VERB Wechaty say(Wechaty exit -1 because of exit )

npm ERR! Linux 3.13.0-129-generic
npm ERR! argv "/root/.nvm/v6.11.3/bin/node" "/root/.nvm/v6.11.3/bin/npm" "run" "ts-node" "example/ding-dong-bot.ts"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wechaty@0.8.219 ts-node: `ts-node "example/ding-dong-bot.ts"`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the wechaty@0.8.219 ts-node script 'ts-node "example/ding-dong-bot.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wechaty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node "example/ding-dong-bot.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wechaty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wechaty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/wechaty/npm-debug.log

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
You can not run chrome browser without a graphical desktop environment.

I suggest you to use Docker to run Wechaty because that will be lots of easier.

**Comment by zixia** [comment]
You can try the latest version v0.10 or above which is not require graphic environment anymore.
