### ISSUE TITLE
Unable to launch Web Wechat

### ISSUE THREAD

**Issue by MaheshSundaramurthy** [Chatie/wechaty#876]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
Out China
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
This is currently development mode, am running it from my laptop
#### Wechaty Doctor

 1. Wechaty version: #git[6d6ca6c]
 2. Windows_NT x64 version 10.0.15063 memory 7855/16086 MB
 3. Docker: false
 4. Node version: v6.9.2
 5. Tcp IPC TEST: PASS
 6. Chromedriver: Error: spawnSync chromedriver ENOENT

Getting Error:
For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com

### Expected behavior

Web.wechat launched after QR Scan

### Actual behavior

For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com

### Steps to reproduce the behavior (and fixes, if any)

```shell
[200] Scan QR Code in above url to login:
18:27:05 WARN PuppetWebBrowser execute() exception: unexpected alert open: {Alert text : For account security, newly registered WeChat account
s are una, UnexpectedAlertOpenError: unexpected alert open: {Alert text : For account security, newly registered WeChat accounts are unable to
 log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
    at WebDriverError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:27:5)
    at UnexpectedAlertOpenError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:282:5)
    at Object.checkLegacyResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:536:13)
    at parseHttpResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
18:27:05 WARN PuppetWebBridge execute() exception: unexpected alert open: {Alert text : For account security, newly registered WeChat accounts
 are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
18:27:05 WARN PuppetWebBridge proxyWechaty() noWechaty exception: UnexpectedAlertOpenError: unexpected alert open: {Alert text : For account s
ecurity, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at
 http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
    at WebDriverError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:27:5)
    at UnexpectedAlertOpenError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:282:5)
    at Object.checkLegacyResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:536:13)
    at parseHttpResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
18:27:05 ERR PuppetWebBridge getUserName() exception: unexpected alert open: {Alert text : For account security, newly registered WeChat accou
nts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
18:27:05 ERR PuppetWebEvent onServerLogin() exception: UnexpectedAlertOpenError: unexpected alert open: {Alert text : For account security, ne
wly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wec
hat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
UnexpectedAlertOpenError: unexpected alert open: {Alert text : For account security, newly registered WeChat accounts are unable to log in to
Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
    at WebDriverError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:27:5)
    at UnexpectedAlertOpenError (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:282:5)
    at Object.checkLegacyResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\error.js:536:13)
    at parseHttpResponse (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\M_PROJECTS\IOT\BOT_Platform\BOT_Platform_W9\wechaty\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
(node:18596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): UnexpectedAlertOpenError: unexpected alert open:
 {Alert text : For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Win
dows WeChat or Mac WeChat at http://wechat.com}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.15063 x86_64)
```

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Duplicated with #872
