### ISSUE TITLE
在登录失败时的异常提示优化

### ISSUE THREAD

**Issue by Gcaufy** [Chatie/wechaty#898]
在网页端登录失败时返回：
```
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>
```

在wechatylog中是：
```
VERB PuppetWebBridge inject() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env. stack: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.<anonymous> (/wechaty/dist/src/puppet-web/bridge.js:66:27)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/bridge.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
ERR PuppetWebEvent onServerDisconnect() setTimeout() bridge.init() exception: [Error: execute proxyWechaty(init) error: 503, init() without a ready angular env]
```

很难根据错误信息定位到报错原因。

**Comment by Gcaufy** [comment]
https://github.com/Chatie/wechaty/blob/13e402a37049da3d0d58d2f2b40abc3b863a23ac/src/puppet-web/bridge.ts#L634-L640

I see

**Comment by zixia** [comment]
Yes, please use the latest version of master branch.
