### ISSUE TITLE
"PromiseRejectionHandledWarning: Promise rejection was handled asynchronously" when Wechat says "当前登录环境异常"

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#925]
v0.11.17

Deal with #603
```
https://login.weixin.qq.com/qrcode/QY2tzrUsdQ==
[408] Scan QR Code in above url to login: 
 10:25:26 VERB PuppetWebEvent onScan({code: 201, url: https://login.weixin.qq.com/qrcode/QY2tzrUsdQ==})
10:25:26 VERB Profile set(cookies, [object Object],[object Object],[object Object],[object Object],[object Object])
10:25:26 VERB Profile save() file: /home/zixia/chatie/wechaty/demo.wechaty.json
https://login.weixin.qq.com/qrcode/QY2tzrUsdQ==
[201] Scan QR Code in above url to login: 
10:25:28 VERB PuppetWebBridge initPage() on(load) https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=A8U8OrxD3a_6wksSjgfcGD-C@qrticket_0&uuid=QY2tzrUsdQ==&lang=en_US&scan=1509157529
10:25:28 VERB PuppetWebBridge readyAngular()
10:25:38 VERB PuppetWebBridge readyAngular() timeout
10:25:38 VERB PuppetWebBridge testBlockedMessage(<pre style="word-wrap: break-word; white-space: pr)
10:25:38 VERB PuppetWebBridge preHtmlToXml()
10:25:38 WARN PuppetWebBridge testBlockedMessage() error.ret=1203
10:25:38 ERR PuppetWebBridge init() initPage() onLoad() exception: Error: 当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。
10:25:38 ERR Config ###########################
10:25:38 ERR Config unhandledRejection: Error: 当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。 [object Promise]
10:25:38 ERR Config ###########################
10:25:38 ERR Config unhandledRejection::catch(当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。)
Config Error: 当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。
    at Bridge.<anonymous> (/home/zixia/chatie/wechaty/src/puppet-web/bridge.ts:210:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/zixia/chatie/wechaty/src/puppet-web/bridge.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:594) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
10:25:58 ERR Config ###########################
10:25:58 ERR Config unhandledRejection: Error: waiting failed: timeout 30000ms exceeded [object Promise]
10:25:58 ERR Config ###########################
10:25:58 ERR Config unhandledRejection::catch(waiting failed: timeout 30000ms exceeded)
Config Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/zixia/chatie/wechaty/node_modules/puppeteer/lib/FrameManager.js:502:58)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
(node:594) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

**Comment by leinue** [comment]
error:

Scan QrCode to login: 201

**Comment by zixia** [comment]
@leinue What did you mean?
