### ISSUE TITLE
can't upload video over 1 MB

### ISSUE THREAD

**Issue by samhoo** [Chatie/wechaty#932]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
Beijing
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
Local Mac 
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
localhost:wechaty-getting-started samhoo$ npm run doctor
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "doctor"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! missing script: doctor
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/heido/highlightmoment/chatd/docker/wechaty-getting-started/npm-debug.log

### Expected behavior
When trying to send video file by modifying mybot.js,  I get an "socket hang up" error  if  file size over 1MB.  And everything would be ok if size of file is less than 1MB

According wechat protocol, it should be split to chunks to post, when uploading a large file. 

here is code snippet(modified from mybot.js):
.....
    if (/hello/.test(content)) {
        m.say("hello how are you")
        m.say(new MediaMessage('chunks.mp4'))
    }
.....

localhost:wechaty-getting-started xxx$ ls -l chunks.mp4
-rw-r--r--@ 1 samhoo  admin  1506366 10 29 11:20 chunks.mp4

### Steps to reproduce the behavior (and fixes, if any)
1.start bot : node mybot.js
2.send message to bot: hello
3.bot echo message: hello how are you.  & send a video

### Full Output Logs

```shell
$ export WECHATY_LOG=VERBOSE
node mybot.js
.........
https://login.weixin.qq.com/qrcode/IYUGv47fuw==
12:37:13 VERB PuppetWebEvent onServerLog(login(scan code 200))
12:37:13 VERB PuppetWebEvent onServerLogin(scan code 200, 0)
12:37:13 VERB PuppetWebBridge getUserName()
12:37:13 VERB PuppetWebBridge proxyWechaty(getUserName, )
12:37:13 VERB PuppetWebBridge proxyWechaty(getContact, @55664da21cb0c1414931c8efb5740606131b8a6cfb5de154436eead51df31695)
12:37:14 VERB PuppetWebBrowserCookie save() no store file
MYBOTBOT login
12:37:21 VERB PuppetWebBridge proxyWechaty(getContact, @b954144672bf8d31116c63b4ff7976ad)
Contact: GOPUP Content: hello
12:37:21 VERB Message say(hello how are you, undefined)
12:37:21 VERB PuppetWebBridge proxyWechaty(send, @b954144672bf8d31116c63b4ff7976ad, hello how are you)
12:37:21 VERB Message say(chunks.mp4, undefined)
Contact: MYBOTBOT Content: hello how are you
12:37:21 VERB PuppetWebBridge getBaseRequest()
12:37:21 VERB PuppetWebBridge proxyWechaty(getBaseRequest, )
12:37:21 VERB PuppetWebBridge getPassticket()
12:37:21 VERB PuppetWebBridge proxyWechaty(getPassticket, )
12:37:21 VERB PuppetWebBridge getUploadMediaUrl()
12:37:21 VERB PuppetWebBridge proxyWechaty(getUploadMediaUrl, )
12:37:21 VERB PuppetWebBrowserCookie read()
12:37:21 VERB PuppetWeb self()
12:37:21 ERR Config ###########################
12:37:21 ERR Config unhandledRejection: Error: socket hang up [object Promise]
12:37:21 ERR Config ###########################
12:37:21 ERR Config unhandledRejection::catch(socket hang up)
Config { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
(node:45915) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

# or 


```

**Comment by zixia** [comment]
What's the version number of the Wechaty that you were using?

It seems it's not the latest version, please try the latest version by runing `npm install wechaty`, this command will install the v0.11.x for you.

If it still has issue, please post the **FULL** output with `WECHATY_LOG=silly` set.

**Comment by samhoo** [comment]
I have updated wechaty to version 0.11.26, still get the same error "socket hang up". 

```shell
localhost:wbot samhoo$ ls -l video1460k.mp4 
-rw-r--r--@ 1 samhoo  admin  1506366 10 30 10:46 video1460k.mp4
localhost:wbot samhoo$ npm ls |grep wechaty
└─┬ wechaty@0.11.26
localhost:wbot samhoo$ cat mybot.js
const { Wechaty, Room, MediaMessage } = require('wechaty')

Wechaty.instance()
    .on('scan', (url, code) => {
        let loginUrl = url.replace('qrcode', 'l')
        require('qrcode-terminal').generate(loginUrl)
        console.log(url)
    })

.on('login', user => {
    console.log(`${user} login`)
})

.on('friend', function(contact, request) {
    if (request) {
        request.accept().then(function() {
            console.log(`Contact: ${contact.name()} send request ${request.hello}`)
        })
    }
})

.on('message', function(m) {
    const contact = m.from()
    const content = m.content()
    const room = m.room()


    if (m.self()) {
        return
    }

    if (/hello/.test(content)) {
        m.say(new MediaMessage('video1460k.mp4'))
        m.say("bye.")
    }

})

.init()


localhost:wbot samhoo$ node mybot.js
https://login.weixin.qq.com/qrcode/QebC04E-TQ==
11:09:06 SILL PuppetWebEvent bridge.getUserName: @e62ea866d9ead937761ab2ab8719011ca9864eddb5b779d0f2c6e13a52683b88
11:09:06 SILL Contact constructor(@e62ea866d9ead937761ab2ab8719011ca9864eddb5b779d0f2c6e13a52683b88)
11:09:06 SILL Contact get contact via PuppetWeb
11:09:06 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
11:09:06 SILL PuppetWebBridge proxyWechaty(getContact , @e62ea866d9ead937761ab2ab8719011ca9864eddb5b779d0f2c6e13a52683b88)
11:09:06 SILL Contact contactGetter(@e62ea866d9ead937761ab2ab8719011ca9864eddb5b779d0f2c6e13a52683b88) resolved
11:09:06 SILL PuppetWebEvent onLogin() user 小HM机器人 logined
11:09:06 SILL StateSwitch <Puppet> on() is true
11:09:06 VERB Profile set(cookies, [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object])
11:09:06 VERB Profile save() file: null
11:09:06 VERB Profile save() no file, NOOP
11:09:06 VERB PuppetWeb readyStable()
11:09:06 SILL PuppetWeb readyStable() stable() counter=-1
11:09:06 VERB Cotnact findAll({ name: /.*/ })
11:09:06 SILL PuppetWebBridge proxyWechaty(contactFind , (function (c) { return /.*/.test(c.NickName) }))
11:09:06 SILL Contact constructor(@caa75bd1157a274164c76306ceef668c)
11:09:06 SILL Contact constructor(weixin)
11:09:06 SILL Contact get contact via PuppetWeb
11:09:06 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
11:09:06 SILL PuppetWebBridge proxyWechaty(getContact , @caa75bd1157a274164c76306ceef668c)
11:09:06 SILL Contact get contact via PuppetWeb
11:09:06 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
11:09:06 SILL PuppetWebBridge proxyWechaty(getContact , weixin)
11:09:06 SILL Contact contactGetter(@caa75bd1157a274164c76306ceef668c) resolved
11:09:06 SILL Contact contactGetter(weixin) resolved
11:09:07 SILL PuppetWeb readyStable() stable() counter=2
11:09:07 VERB Cotnact findAll({ name: /.*/ })
11:09:07 SILL PuppetWebBridge proxyWechaty(contactFind , (function (c) { return /.*/.test(c.NickName) }))
11:09:07 SILL Contact constructor(@de66d4e532f441eecafa05ecf8f7ffa7)
11:09:07 SILL Contact get contact via PuppetWeb
11:09:07 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
11:09:07 SILL PuppetWebBridge proxyWechaty(getContact , @de66d4e532f441eecafa05ecf8f7ffa7)
11:09:07 SILL Contact contactGetter(@de66d4e532f441eecafa05ecf8f7ffa7) resolved
11:09:08 SILL PuppetWeb readyStable() stable() counter=3
11:09:08 VERB Cotnact findAll({ name: /.*/ })
11:09:08 SILL PuppetWebBridge proxyWechaty(contactFind , (function (c) { return /.*/.test(c.NickName) }))
11:09:08 VERB PuppetWeb readyStable() stable() READY counter=3
Contact<小HM机器人> login
11:09:10 SILL PuppetWebEvent onDing(heartbeat@browser)
11:09:10 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed, food={type=undefined, data=heartbeat@browser})
11:09:10 SILL Wechaty memoryCheck() free: 31 MB, require: 4 MB
11:09:22 SILL Message constructor() SN:0
11:09:22 SILL Message ready()
11:09:22 SILL Message ready()
11:09:22 SILL Message constructor() SN:1
11:09:22 VERB Message say(video1460k.mp4, undefined)
11:09:22 VERB MediaMessage readyStream()
11:09:22 VERB Message say(bye., undefined)
11:09:22 SILL Message constructor() SN:2
11:09:22 SILL PuppetWeb send() destination: @caa75bd1157a274164c76306ceef668c, content: bye.)
11:09:22 SILL PuppetWebBridge proxyWechaty(send , @caa75bd1157a274164c76306ceef668c, bye.)
11:09:22 VERB PuppetWebBridge getBaseRequest()
11:09:22 SILL PuppetWebBridge proxyWechaty(getBaseRequest)
11:09:22 SILL Message constructor() SN:3
11:09:22 SILL Message ready()
11:09:22 SILL Message ready()
11:09:22 VERB PuppetWebBridge getPassticket()
11:09:22 SILL PuppetWebBridge proxyWechaty(getPassticket)
11:09:22 VERB PuppetWebBridge getUploadMediaUrl()
11:09:22 SILL PuppetWebBridge proxyWechaty(getUploadMediaUrl)
11:09:22 VERB PuppetWebBridge getCheckUploadUrl()
11:09:22 SILL PuppetWebBridge proxyWechaty(getCheckUploadUrl)
11:09:22 VERB PuppetWeb self()
11:09:22 VERB PuppetWebBridge hostname()
11:09:22 SILL PuppetWebBridge hostname() got wx.qq.com
11:09:22 SILL PuppetWeb uploadMedia() headers:{"Referer":"https://wx.qq.com","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36","Cookie":"wxpluginkey=1509324122; wxloadtime=1509332944_expired; last_wxuin=417675550; MM_WX_NOTIFY_STATE=1; webwx_auth_ticket=CIsBEJj4xYQPGoABYFJgsoetwAv9mKTR5uJtMrldm9a41d3z32txTN2ALjSKoHnbvDvFts2ipF2mSsgwRC6eHtf3WM04C4kH1Utes3ARFi/SVTbgSEOEKjkoXTzM1P8A3oKHARsZ84Gg5YkttLyU6xLTH7rf22Yt3MTuEClS/Mqyev6d/KooTDgKaqk=; login_frequency=1; webwx_data_ticket=gSeGLeW+si/BM2+/IpKxcIS+; webwxuvid=8712d45aaa0aff2a9ace5fa4d7e494cef3c5169260e8b7d9e028cadfeed79c63f95529ab30392309c967ceb0357b6644; wxsid=obzJiUOT1Dv7slvR; mm_lang=en_US; wxuin=417675550; MM_WX_SOUND_STATE=1"}
11:09:22 VERB PuppetWeb uploadMedia() webwx_data_ticket: gSeGLeW+si/BM2+/IpKxcIS+
11:09:22 VERB PuppetWeb uploadMedia() pass_ticket: 1e3zgMHDjjWjiMVPHPaZxQJx4IFVf%2B4Im4%2FUqTvDwlNeKHAMWKbUjBPEtRkdWcv6
11:09:23 ERR PuppetWeb uploadMedia() uploadMedia exception: socket hang up
11:09:23 ERR PuppetWeb sendMedia() exception: uploadMedia err: socket hang up
11:09:25 SILL PuppetWebEvent onDing(heartbeat@browser)
11:09:25 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed, food={type=undefined, data=heartbeat@browser})
11:09:25 SILL Wechaty memoryCheck() free: 59 MB, require: 4 MB
```

**Comment by zixia** [comment]
Thanks for the update.

I remember your log include the follow error message last time:
```
12:37:21 ERR Config ###########################
12:37:21 ERR Config unhandledRejection: Error: socket hang up [object Promise]
12:37:21 ERR Config ###########################
12:37:21 ERR Config unhandledRejection::catch(socket hang up)
Config { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
(node:45915) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

Which `ECONNRESET` looks some wrong with your local network with Tencent server.

CC @ax4 @mukaiu

**Comment by samhoo** [comment]
Thanks for your comment.

In my opinion, there are 2 clue should be notice:
1.I uploaded small file(280kBytes) successfully  last time & this time. 
2.According wechat protocol, it should be split to chunks(512k/chunk) to post, when uploading a large file more than 512k.   The following snippet was captured by chrome developer console. NOTICE: parameter chunk & chunks.

Anyway, I will try QCloud.


```shell
POST /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json HTTP/1.1
Host: file.wx.qq.com
Connection: keep-alive
Content-Length: 526140
Origin: https://wx.qq.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarySb6QGj1TBIBFaWkl
Accept: */*
Referer: https://wx.qq.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.8
Cookie: webwxuvid=c16c0d789381bc76f58aaae1a9ce25c6796372bf7ab65da4735ae8a4fa7576a580958cecd57955f364cba50714307fbf; pgv_pvid=8163044763; pgv_pvi=2628132864; RK=PIN/Fni7TN; ptcz=34cf7f650d424457924cf126c3ee096791d4d256ad212f119b47087dacfa350f; pt2gguin=o0069351960; mm_lang=zh_CN; webwx_auth_ticket=CIsBEK2195EKGoABSkI0qrVkP5KgbNb2U2FMiSAfl1caH28BPkkG362j/KBESJlEww+toMdR74+lAtZm6dQQZuZaNfOS/jBeVZs0SwqALhADQaNXMC+H08Lfg/j4/UexCCy+N7qOdZaU2Me+HWNaExioxdqRuW7yMXq/Fz8Rs2lGrYR6ko+ltqCL2hc=; wxloadtime=1509153991_expired; wxpluginkey=1509151202; wxuin=373136640; wxsid=LrfHKJc7NSVC9ytr; webwx_data_ticket=gSf4js4G+jXEx6G5zmEwW9b/

------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="id"

WU_FILE_0
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="name"

NB11.mp4
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="type"

video/mp4
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="lastModifiedDate"

Thu Oct 26 2017 21:39:29 GMT+0800 (CST)
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="size"

1506366
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="chunks"

3
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="chunk"

0
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="mediatype"

video
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="uploadmediarequest"

{"UploadType":2,"BaseRequest":{"Uin":373136640,"Sid":"LrfHKJc7NSVC9ytr","Skey":"@crypt_a6c4e648_46be2a410b0e7e9a5a59be773722bdfb","DeviceID":"e446538637172809"},"ClientMediaId":1509154542997,"TotalLen":1506366,"StartPos":0,"DataLen":1506366,"MediaType":4,"FromUserName":"@434b1662119ee9f9cb8da8938cec4c36","ToUserName":"@88781c52c2b73f0605277f003e7d5737163cfa978d25c2669b83038f884659bb","FileMd5":"7bf0d5fbc6e849fd99b647332cb9c93c"}
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="webwx_data_ticket"

gSf4js4G+jXEx6G5zmEwW9b/
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="pass_ticket"

be1csr+gqP3j5huP6LQbJN1NIhbzWMBP/le68K5uzPPAxpn/Q5hlbRxb4T3ZfYcQ
------WebKitFormBoundarySb6QGj1TBIBFaWkl
Content-Disposition: form-data; name="filename"; filename="NB11.mp4"
Content-Type: application/octet-stream
```

**Comment by samhoo** [comment]
I got the error on QCloud when uploading large size. At the same time, chat bot uploaded small size sucessfully. 

```shell
Enviroment: 
wechaty@0.12.2 (updated from zixia/wechaty:latest docker image)
docker  : 1.12.6
Linux VM_42_86_centos 3.10.0-514.26.2.el7.x86_64
QCloud

bot@bb1080801a9f:/wechaty$ ls -l media/*.mp4
-rw-r--r-- 1 root root 1506366 Oct 31 04:25 media/video1460k.mp4
-rw-r--r-- 1 root root  282475 Oct 31 04:25 media/video280k.mp4
-rw-r--r-- 1 root root  998429 Oct 31 04:25 media/video970k.mp4

bot@bb1080801a9f:/wechaty$ cat mybot.js
const { Wechaty, Room, MediaMessage } = require('wechaty')

Wechaty.instance()
    .on('scan', (url, code) => {
        let loginUrl = url.replace('qrcode', 'l')
        require('qrcode-terminal').generate(loginUrl)
        console.log(url)
    })

.on('login', user => {
    console.log(`${user} login`)
})

.on('friend', function(contact, request) {
    if (request) {
        request.accept().then(function() {
            console.log(`Contact: ${contact.name()} send request ${request.hello}`)
        })
    }
})

.on('message', function(m) {
    const contact = m.from()
    const content = m.content()
    const room = m.room()


    if (m.self()) {
        return
    }

    if (/hello/.test(content)) {
        m.say(new MediaMessage('media/video280k.mp4'))
        m.say(new MediaMessage('media/video1460k.mp4'))
        m.say("bye.")
    }

})

.init()

bot@bb1080801a9f:/wechaty$ node mybot.js
https://login.weixin.qq.com/qrcode/Af591KM3qg==
04:37:41 SILL PuppetWebEvent bridge.getUserName: @2c2acfa076a8dfe9d00cf1ce86a9194c122ce4c671cf1cb2210af88ab3707011
04:37:41 SILL Contact constructor(@2c2acfa076a8dfe9d00cf1ce86a9194c122ce4c671cf1cb2210af88ab3707011)
04:37:41 SILL Contact get contact via PuppetWeb
04:37:41 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
04:37:41 SILL PuppetWebBridge proxyWechaty(getContact , @2c2acfa076a8dfe9d00cf1ce86a9194c122ce4c671cf1cb2210af88ab3707011)
04:37:41 SILL Contact contactGetter(@2c2acfa076a8dfe9d00cf1ce86a9194c122ce4c671cf1cb2210af88ab3707011) resolved
04:37:41 SILL PuppetWebEvent onLogin() user 小HM机器人 logined
04:37:41 SILL StateSwitch <Puppet> on() is true
04:37:41 VERB Profile set(cookies, [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object])
04:37:41 VERB Profile save() file: null
04:37:41 VERB Profile save() no file, NOOP
04:37:41 VERB PuppetWeb readyStable()
04:37:41 SILL PuppetWeb readyStable() stable() counter=-1
04:37:41 VERB Cotnact findAll({ name: /.*/ })
04:37:41 SILL PuppetWebBridge proxyWechaty(contactFind , (function (c) { return /.*/.test(c.NickName) }))
04:37:41 SILL Contact constructor(@cd1995665a6d00038986475f99fc57b8)
04:37:41 SILL Contact constructor(@d00e2adf7c60b4535bc892cee0a3840a)
04:37:41 SILL Contact constructor(weixin)
04:37:41 SILL Contact get contact via PuppetWeb
04:37:41 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
04:37:41 SILL PuppetWebBridge proxyWechaty(getContact , @cd1995665a6d00038986475f99fc57b8)
04:37:41 SILL Contact get contact via PuppetWeb
04:37:41 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
04:37:41 SILL PuppetWebBridge proxyWechaty(getContact , @d00e2adf7c60b4535bc892cee0a3840a)
04:37:41 SILL Contact get contact via PuppetWeb
04:37:41 SILL PuppetWebBridge getContact() retryPromise: attampt 1/35 time for timeout 306250
04:37:41 SILL PuppetWebBridge proxyWechaty(getContact , weixin)
04:37:41 SILL Contact contactGetter(@cd1995665a6d00038986475f99fc57b8) resolved
04:37:41 SILL Contact contactGetter(@d00e2adf7c60b4535bc892cee0a3840a) resolved
04:37:41 SILL Contact contactGetter(weixin) resolved
04:37:42 SILL PuppetWeb readyStable() stable() counter=3
04:37:42 VERB Cotnact findAll({ name: /.*/ })
04:37:42 SILL PuppetWebBridge proxyWechaty(contactFind , (function (c) { return /.*/.test(c.NickName) }))
04:37:42 VERB PuppetWeb readyStable() stable() READY counter=3
Contact<小HM机器人> login
04:37:52 SILL PuppetWebEvent onDing(heartbeat@browser)
04:37:52 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed, food={type=undefined, data=heartbeat@browser})
04:37:52 SILL Wechaty memoryCheck() free: 87 MB, require: 4 MB
04:37:54 SILL Message constructor() SN:0
04:37:54 SILL Message ready()
04:37:54 SILL Message ready()
04:37:54 SILL Message constructor() SN:1
04:37:54 VERB Message say(video280k.mp4, undefined)
04:37:54 VERB MediaMessage readyStream()
04:37:54 SILL Message constructor() SN:2
04:37:54 VERB Message say(video1460k.mp4, undefined)
04:37:54 VERB MediaMessage readyStream()
04:37:54 VERB Message say(bye., undefined)
04:37:54 SILL Message constructor() SN:3
04:37:54 SILL PuppetWeb send() destination: @cd1995665a6d00038986475f99fc57b8, content: bye.)
04:37:54 SILL PuppetWebBridge proxyWechaty(send , @cd1995665a6d00038986475f99fc57b8, bye.)
04:37:54 VERB PuppetWebBridge getBaseRequest()
04:37:54 SILL PuppetWebBridge proxyWechaty(getBaseRequest)
04:37:54 VERB PuppetWebBridge getBaseRequest()
04:37:54 SILL PuppetWebBridge proxyWechaty(getBaseRequest)
04:37:54 SILL Message constructor() SN:4
04:37:54 SILL Message ready()
04:37:54 SILL Message ready()
04:37:54 VERB PuppetWebBridge getPassticket()
04:37:54 SILL PuppetWebBridge proxyWechaty(getPassticket)
04:37:54 VERB PuppetWebBridge getPassticket()
04:37:54 SILL PuppetWebBridge proxyWechaty(getPassticket)
04:37:54 VERB PuppetWebBridge getUploadMediaUrl()
04:37:54 SILL PuppetWebBridge proxyWechaty(getUploadMediaUrl)
04:37:54 VERB PuppetWebBridge getUploadMediaUrl()
04:37:54 SILL PuppetWebBridge proxyWechaty(getUploadMediaUrl)
04:37:54 VERB PuppetWebBridge getCheckUploadUrl()
04:37:54 SILL PuppetWebBridge proxyWechaty(getCheckUploadUrl)
04:37:54 VERB PuppetWebBridge getCheckUploadUrl()
04:37:54 SILL PuppetWebBridge proxyWechaty(getCheckUploadUrl)
04:37:54 VERB PuppetWeb self()
04:37:54 VERB PuppetWebBridge hostname()
04:37:54 VERB PuppetWeb self()
04:37:54 VERB PuppetWebBridge hostname()
04:37:54 SILL PuppetWebBridge hostname() got wx.qq.com
04:37:54 SILL PuppetWebBridge hostname() got wx.qq.com
04:37:54 SILL PuppetWeb uploadMedia() headers:{"Referer":"https://wx.qq.com","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36","Cookie":"wxpluginkey=1509412202; wxloadtime=1509424661_expired; last_wxuin=417675550; MM_WX_NOTIFY_STATE=1; webwx_auth_ticket=CIsBEI3xndAHGoABv0aKFm9L/jYV112hj7+HobQq/m1/iDFU6bWP6vK55JtAmp9XdHBxqmsB197SKsHLjMcRPKZHETBZsJbRUP1NTd5XYPS2dTqzget0/n5CYfGHwhO9gFK9VXEqVVx0GZV0BI4d34Gswyz2CLRiAi91kyhqZoM6XGJaMZxhhsaoH1Q=; login_frequency=1; webwx_data_ticket=gScRn10YLG/JusTdCkIGsDru; webwxuvid=e64d430523a2fcb94f0fb1d443d3b27f52804a5eca045391f0628b0f9bd45e21256808f2e387ef12d256ec6fca6f707b; wxsid=mzCr4PPpRNPU2TQT; mm_lang=en_US; wxuin=417675550; MM_WX_SOUND_STATE=1"}
04:37:54 VERB PuppetWeb uploadMedia() webwx_data_ticket: gScRn10YLG/JusTdCkIGsDru
04:37:54 VERB PuppetWeb uploadMedia() pass_ticket: 4i%2Bv2HaB3iigbAteeSIDH4pVODxa4ZW7eQOuNIS8QHnvo9XQQc5Y8xS2ABPI1xA8
04:37:54 SILL PuppetWeb uploadMedia() headers:{"Referer":"https://wx.qq.com","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36","Cookie":"wxpluginkey=1509412202; wxloadtime=1509424661_expired; last_wxuin=417675550; MM_WX_NOTIFY_STATE=1; webwx_auth_ticket=CIsBEI3xndAHGoABv0aKFm9L/jYV112hj7+HobQq/m1/iDFU6bWP6vK55JtAmp9XdHBxqmsB197SKsHLjMcRPKZHETBZsJbRUP1NTd5XYPS2dTqzget0/n5CYfGHwhO9gFK9VXEqVVx0GZV0BI4d34Gswyz2CLRiAi91kyhqZoM6XGJaMZxhhsaoH1Q=; login_frequency=1; webwx_data_ticket=gScRn10YLG/JusTdCkIGsDru; webwxuvid=e64d430523a2fcb94f0fb1d443d3b27f52804a5eca045391f0628b0f9bd45e21256808f2e387ef12d256ec6fca6f707b; wxsid=mzCr4PPpRNPU2TQT; mm_lang=en_US; wxuin=417675550; MM_WX_SOUND_STATE=1"}
04:37:54 VERB PuppetWeb uploadMedia() webwx_data_ticket: gScRn10YLG/JusTdCkIGsDru
04:37:54 VERB PuppetWeb uploadMedia() pass_ticket: 4i%2Bv2HaB3iigbAteeSIDH4pVODxa4ZW7eQOuNIS8QHnvo9XQQc5Y8xS2ABPI1xA8
04:37:54 ERR PuppetWeb uploadMedia() uploadMedia exception: read ECONNRESET
04:37:54 ERR PuppetWeb sendMedia() exception: uploadMedia err: read ECONNRESET
04:37:56 SILL PuppetWeb Upload completed, new rawObj:{"ToUserName":"@cd1995665a6d00038986475f99fc57b8","MediaId":"@crypt_bcfa2c53_ea8855b2619da3815ee738e2b43454d9872a7517aeea9cb07275933e5ba4aa945fa8f8b8fec1a4f2504cbdc859b2ef7ecf4b28f93a0b79c36f65de42ed3248ea8aad3a75ad9e3b4b536c8fedb8ec7937","FileName":"video280k.mp4","FileSize":282475,"FileMd5":"29a40d82d9529ab2f60a6f023ad673ec","MMFileExt":"mp4"}
04:37:56 SILL PuppetWeb sendMedia() destination: @cd1995665a6d00038986475f99fc57b8, mediaId: @crypt_bcfa2c53_ea8855b2619da3815ee738e2b43454d9872a7517aeea9cb07275933e5ba4aa945fa8f8b8fec1a4f2504cbdc859b2ef7ecf4b28f93a0b79c36f65de42ed3248ea8aad3a75ad9e3b4b536c8fedb8ec7937, MsgType; 43)
04:37:56 SILL PuppetWebBridge proxyWechaty(sendMedia , [object Object])
04:37:56 SILL Message constructor() SN:5
04:37:56 SILL Message ready()
04:37:56 VERB PuppetWebEvent onMessage() EMOTICON/IMAGE/VIDEO/VOICE/MICROVIDEO message
04:37:56 SILL Message constructor() SN:6
04:37:56 SILL MediaMessage ready()
04:37:56 SILL Message ready()
04:37:56 VERB PuppetWebBridge getMsgVideo(15094246765310802)
04:37:56 SILL PuppetWebBridge proxyWechaty(getMsgVideo , 15094246765310802)
04:38:07 SILL PuppetWebEvent onDing(heartbeat@browser)
04:38:07 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed, food={type=undefined, data=heartbeat@browser})
04:38:07 SILL Wechaty memoryCheck() free: 73 MB, require: 4 MB
```

**Comment by samhoo** [comment]
any comment？

**Comment by zixia** [comment]
@samhoo Sorry I did not get time to reproduce this issue.

Could you confirm that if you could send large picture files over 1MB, like 2MB?

**Comment by samhoo** [comment]
@zixia thanks for the reply.

I am pretty sure that could not sent video file over 1MB. In fact, I have tested some 2MB/7MB video files that all failed to upload.  At the same time, any video file less than 1MB could be upload successfully.

I'm sorry if I make you fell pushing your to resolve the issue.  Take your time to enjoy hacking:)

···shell

bot@bb1080801a9f:/wechaty$ ls -l media/*.mp4
-rw-r--r-- 1 root root 1506366 Oct 31 04:25 media/video1460k.mp4
-rw-r--r-- 1 root root  282475 Oct 31 04:25 media/video280k.mp4
-rw-r--r-- 1 root root  998429 Oct 31 04:25 media/video970k.mp4

bot@bb1080801a9f:/wechaty$ cat mybot.js
【ignore some code not matter 。。。。】
    if (/hello/.test(content)) {
        m.say(new MediaMessage('media/video280k.mp4'))
        m.say(new MediaMessage('media/video1460k.mp4'))
        m.say("bye.")
    }

})

```

**Comment by zixia** [comment]
Thanks, I'll take a look when I get time.

CC @binsee

**Comment by zixia** [comment]
This issue might be related to #951.

If so, then wechaty should also not be able to send large picture file when size is very large, i.e.: 2MB.

Need to be confirmed.

**Comment by zixia** [comment]
Merge to #951
