### ISSUE TITLE
The latest docker get `ContactGetter` error when get wechat OA message

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#974]
### Provide Your Network Information
China/Aws

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

```
Starting Wechaty v0.13.30 with Node.js v8.9.1 ...

> wechaty@0.13.30 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.13.30 check-node-version /wechaty
> check-node-version --node ">= 7"

node: 8.9.1
┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /bot/.config │
└──────────────────────────────────────────────────┘
yarn: not installed

┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /bot/.config │
└──────────────────────────────────────────────────┘

  #### Wechaty Doctor

  1. Wechaty version: #git[faf661e]
  2. Linux x64 version 3.16.0-4-amd64 memory 1114/3962 MB
  3. Docker: true
  4. Node version: v8.9.1
  5. Tcp IPC TEST: PASS



┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /bot/.config │
└──────────────────────────────────────────────────┘
```

### Actual behavior

When there is an Wechat OA Service account（服务号） message push, it will occur the following result 
```
08:52:06 INFO Wechaty v0.13.30 starting...
Contact<李佳芮>login
#SERVERCHAN_{"msg":"SUCCESS"}
08:52:10 WARN Contact parse() got empty rawObj!
08:52:10 ERR Contact contactGetter(@fb9aa59dbe802ccdc513a34079b71dc3) exception: parse() got empty rawObj!
08:52:10 ERR Message ready() exception: Error: parse() got empty rawObj!
    at Contact.parse (/wechaty/src/contact.ts:150:17)
    at Contact.<anonymous> (/wechaty/src/contact.ts:615:26)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/contact.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
08:52:10 ERR PuppetWebEvent onMessage() exception: Error: parse() got empty rawObj!
    at Contact.parse (/wechaty/src/contact.ts:150:17)
    at Contact.<anonymous> (/wechaty/src/contact.ts:615:26)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/contact.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: parse() got empty rawObj!
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lijiarui** [comment]
before login, it will get this error too.
```
09:15:47 INFO Wechaty v0.13.72 starting...
info: Express Server listening on port 3300
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:03 WARN Contact parse() got empty rawObj!
09:16:04 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:07 WARN Contact parse() got empty rawObj!
09:16:08 WARN Contact parse() got empty rawObj!
09:16:08 WARN Contact parse() got empty rawObj!
09:16:08 WARN Contact parse() got empty rawObj!
09:16:08 WARN Contact parse() got empty rawObj!
info: Contact<Sara>login
09:16:09 WARN Contact parse() got empty rawObj!
info: Sara登陆成功！
```

**Comment by zixia** [comment]
Close this issue because it was outdated.
