### ISSUE TITLE
Sending pdf fille will get error

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#985]
The latest wechaty npm version will catch error when anyone send a pdf file. 

wechaty version: 0.13.32

log as follows

### Full Output Logs
```shell
08:22:11 ERR PuppetWebEvent onMessage() exception: Error: no MMAppMsgDownloadUrl
    at MediaMessage.<anonymous> (/home/ubuntu/workspace/node_modules/wechaty/src/message.ts:736:23)
    at next (native)
    at fulfilled (/home/ubuntu/workspace/node_modules/wechaty/dist/src/message.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
(node:55851) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: no MMAppMsgDownloadUrl

```

**Comment by zixia** [comment]
Move to <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/29>
